fix for install doc in develop
PaddlePaddle/docs pull request #1014
Opened 2019-07-18 09:11 UTC by JepsonWong

fix for install doc in develop。

2019-07-19 01:55 UTC, JepsonWong commented
[](url)

2019-07-19 01:58 UTC, JepsonWong commented
> fix for install doc in develop。

2019-07-19 02:03 UTC, JepsonWong commented
<img width="621" alt="屏幕快照 2019-07-19 上午10 02 16" src="https://user-images.githubusercontent.com/16509038/61503982-60b03180-aa0c-11e9-868b-412df89aa41a.png">
<img width="1241" alt="屏幕快照 2019-07-19 上午10 02 28" src="https://user-images.githubusercontent.com/16509038/61503990-63ab2200-aa0c-11e9-9d6a-b6a49621efc5.png">
<img width="620" alt="屏幕快照 2019-07-19 上午10 02 38" src="https://user-images.githubusercontent.com/16509038/61503993-660d7c00-aa0c-11e9-8abe-ccd596de230e.png">

2019-07-19 05:59 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +您可以选择“使用pip安装”、“使用docker安装”、“从源码编译安装” 三种方式中的任意一种种方式进行安装。
多了种

2019-07-19 05:59 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +    * CentOS
这块问下jiannan，修改下的

2019-07-19 06:03 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +- 注意：目前官方没有支持 `conda` 和 `anaconda` 进行支持，使用他们所附带的 `pip` 安装 `paddlepaddle` 也可能会带来冲突。所以建议使用纯净的 Python 环境的 `pip` 进行安装。
目前官方没有支持 `conda` 和 `anaconda` 进行支持 不通顺

2019-07-19 06:03 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +	[2]. **GPU版本**：如果您想使用CPU版本请参考如下命令安装
与1中的CPU版本格式错位了，而且[]也不一样

2019-07-19 06:10 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +    或如果您需要支持 `CUDA 8` 或者 `CUDA 9` 的版本，将上述命令的 `cuda10.0` 替换成 `cuda9.0` 或者 `cuda8.0` 即可，cuDNN 仅支持 `cuDNN 7.3+`
将上述命令的 `cuda10.0` 替换成 `cuda9.0` 或者 `cuda8.0` 即可，把8和9换个位置吧，和前面的保持一致

2019-07-19 06:12 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +- 如果您只是使用 `PaddlePaddle` 建议只使用 `pip` 和 `docker` 两种安装方式中选取一种安装方式进行安装。
如果您只是使用 `PaddlePaddle` 建议只使用 `pip` 和 `docker` 两种安装方式中选取一种安装方式进行安装。-》如果您只是使用 `PaddlePaddle` ，建议从 `pip` 和 `docker` 两种安装方式中选取一种进行安装即可。

2019-07-19 07:23 UTC, xsrobin commented on doc/fluid/beginners_guide/install/index_cn.rst
> +您可以选择“使用pip安装”、“使用docker安装”、“从源码编译安装” 三种方式中的任意一种种方式进行安装。
一种种方式

2019-07-21 09:37 UTC, xsrobin approved these changes

2019-07-22 03:31 UTC, JiabinYang requested changes
one comment

2019-07-22 03:31 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/index_cn.rst
> +    (2). **GPU版本**：如果您想使用CPU版本请参考如下命令安装
better to inform user the default cuda supported version since most of them will use `pip install paddlepaddle-gpu` instead of specified CUDA version

2019-07-24 02:59 UTC, JiabinYang approved these changes
LGTM

2019-07-24 10:48 UTC, lanxianghit approved these changes

2019-07-26 05:14 UTC, wanghaoshuang approved these changes

2019-07-26 08:15 UTC, merged