fix for install doc in release/1.5
PaddlePaddle/docs pull request #1015
Opened 2019-07-18 10:10 UTC by JepsonWong

fix for install doc in release/1.5

2019-07-19 02:04 UTC, JepsonWong commented
<img width="621" alt="屏幕快照 2019-07-19 上午10 02 16" src="https://user-images.githubusercontent.com/16509038/61504029-83424a80-aa0c-11e9-939b-82174bed07a3.png">
<img width="1241" alt="屏幕快照 2019-07-19 上午10 02 28" src="https://user-images.githubusercontent.com/16509038/61504031-850c0e00-aa0c-11e9-9a78-2f1e1bc76adb.png">
<img width="620" alt="屏幕快照 2019-07-19 上午10 02 38" src="https://user-images.githubusercontent.com/16509038/61504036-876e6800-aa0c-11e9-870a-e47458922cf0.png">

2019-07-19 02:06 UTC, JepsonWong commented
![屏幕快照 2019-07-18 下午9 20 47](https://user-images.githubusercontent.com/16509038/61504110-cdc3c700-aa0c-11e9-8bd8-b7b0ecbfe6d9.png)

2019-07-21 09:38 UTC, xsrobin approved these changes

2019-07-23 02:43 UTC, JiabinYang requested changes
some comments

2019-07-23 02:43 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/index_cn.rst
> +* 处理器支持 AVX指令集 和 MKL（可选）
不要求处理器支持avx指令集

2019-07-24 02:59 UTC, JiabinYang approved these changes
LGTM

2019-07-24 03:38 UTC, lanxianghit commented on doc/fluid/beginners_guide/install/index_cn.rst
> +        docker run --name paddle -it -v $PWD:/paddle hub.baidubce.com/paddlepaddle/paddle:1.5.1 /bin/bash
很多用户其实多docker操作并不熟悉，此处应该对docker参数做简要说明，使用户能够了解在自己环境下哪些需要修改；另外此处没有路径转移的操作，很可能用户照着文档操作后把根目录映射到镜像的paddle目录，但本意并非如此

2019-07-24 10:48 UTC, lanxianghit approved these changes

2019-07-25 07:03 UTC, merged