MKL-DNN Data transform doc design
PaddlePaddle/docs pull request #1132
Opened 2019-08-30 17:05 UTC by jczaja

Hi,

I'm one of developers responsible for PaddlePaddle Fluid integration with Intel MKL-DNN.
We would like to start to contribute documents describing various concepts of this integration.

This documentation is relevant to **PaddlePaddle Fluid 1.6 release** . I haven't seen relevant branch so I forked from develop (please advice if this is not proper)

Please review

2019-09-02 09:30 UTC, jczaja commented
@grygielski Please review

2019-09-02 09:55 UTC, grygielski requested changes
I found some minor mistakes, please check my corrections.

2019-09-02 09:55 UTC, grygielski commented on doc/fluid/design/mkldnn/data_transformation/data_transform.md
> +Tensors to be feed into MKL-DNN kernel, needs to be transformed to be of MKL-DNN layout. For this scenario conversion of Paddle Tensor to MKL-DNN Tensor is done by just :
I think `:` isn't necessary here.

2019-09-02 09:55 UTC, grygielski commented on doc/fluid/design/mkldnn/data_transformation/data_transform.md
> +changing layout flag to MKL-DNN and picking MKL-DNN format that match Paddle Tensor rank. This is computationally cheap operation as there is real data rearrangement.
`as there is real data rearrangement` -> `as there isn't real data rearrangement`

2019-09-02 09:55 UTC, grygielski commented on doc/fluid/design/mkldnn/data_transformation/data_transform.md
> +This scenario is marked on the picture with regular arrows. Starting from MKL-DNN op on the left side , following regular arrows finishing with fetch op on the right side of picture.
`finishing with fetch op on the right side of picture.` -> `finishing with Paddle(CPU) op on the right side of picture.`

2019-09-02 12:05 UTC, grygielski approved these changes
LGTM

2019-09-02 12:40 UTC, jczaja commented
I have rebased branch using newer develop.

@luotao1 could you please review this PR? This is how it looks rendered:
https://github.com/jczaja/FluidDoc/blob/prv-data-transform/doc/fluid/design/mkldnn/data_transformation/data_transform.md

2019-09-02 13:33 UTC, luotao1 commented
@bingyanghuang Please review it. 
BTW, I could not see the `data_transform.svg`  and `data_transform.dot` in the https://github.com/jczaja/FluidDoc/blob/prv-data-transform/doc/fluid/design/mkldnn/data_transformation/data_transform.md

2019-09-02 14:17 UTC, jczaja commented
@luotao1 data_transform.svg is used in data_transform.md . Those files are stored in images and scripts directories (respectively). You can see directory structure here:
https://github.com/jczaja/FluidDoc/tree/prv-data-transform/doc/fluid/design/mkldnn/data_transformation

2019-09-03 09:09 UTC, jczaja commented
@luotao1 Let me know if you have any concerns or further questions about this PR.

2019-09-10 03:42 UTC, bingyanghuang commented
@jczaja This document is the first MKL-DNN doc in FLuidDoc which will be published for all the PaddlePaddle users. If you want to let Paddle users understand MKL-DNN accelerations  in Paddle , I think we should create a more complete and systematic doc including the following explanations: 

- What is MKL-DNN?

- How MKL-DNN integrate to Paddle?(Data transformation can be a part of this setion)

- What's kind of performance gain user can get from MKL-DNN(E.g. CNN models acceleration, INT8)

- ......
If you just want to explain what you do for the MKL-DNN data transformation optimization, I think this doc should be merged under paddle/fluid/operators/mkldnn/.

2019-09-10 04:57 UTC, luotao1 commented
> If you just want to explain what you do for the MKL-DNN data transformation optimization, I think this doc should be merged under paddle/fluid/operators/mkldnn/.

I agree with it.

2019-09-10 11:05 UTC, jczaja commented
Ok, I have moved this PR into PaddlePaddle PRs (https://github.com/PaddlePaddle/Paddle/pull/19743)
So, I'm closing this PR

2019-09-10 11:05 UTC, closed without merging

2019-09-10 11:15 UTC, luotao1 commented
> data_transform.svg is used in data_transform.md . Those files are stored in images and scripts directories (respectively). You can see directory structure here:

Could you directly put a jpg or png in the new doc? We can see the picture in your document.

2019-09-10 11:21 UTC, jczaja commented
@luotao1 I'm not sure what you mean. There is a picture (SVG) in MD:
https://github.com/jczaja/Paddle/blob/prv-mkldnn-doc-data-transformation/paddle/fluid/operators/mkldnn/doc/data_transformation/data_transform.md
So when you click that link you should see picture in document. Picture was added with:
`![](images/data_transform.svg)`

When you look at data_transform.md then can you see picture rendered?

2019-09-10 12:07 UTC, luotao1 commented
Got it. Maybe there is something wrong with my chrome, after I change to firefox, I can see the picture.
![image](https://user-images.githubusercontent.com/6836917/64612486-8b17dd00-d406-11e9-89e0-abfa20dc1ff2.png)

2019-09-10 12:10 UTC, grygielski commented
In my Chrome (Version 76.0.3809.132 (Official Build) (64-bit)) everything is fine @luotao1

2019-09-12 09:45 UTC, jczaja commented
@luotao1 I could not reopen this PR (I have deleted branch and force replacement of branch is not enough to have PR reopened). So please review #1153