new file for the strided_slice cn doc
PaddlePaddle/docs pull request #1160
Opened 2019-09-17 06:21 UTC by wangchaochaohu

chinese doc for strided_slice op

2019-09-17 07:04 UTC, kuke commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +我们可以接住numpy数组的索引行为理解这个OP，如果你对numpy数组熟悉的话，应该知道通过[start1：end1：step1，start2：end2：step2，... startN：endN：stepN]的语法可以进行切片，从而通过一种十分简洁的方式获取数组的某些元素。strided_slice是的我们可以通过Paddle语法的方式完成相应的切割获取相应的元素。例如numpy中#inpu
`接住` -> `借助`？`k控制` -> `控制`

2019-09-17 07:16 UTC, wangchaochaohu commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +我们可以接住numpy数组的索引行为理解这个OP，如果你对numpy数组熟悉的话，应该知道通过[start1：end1：step1，start2：end2：step2，... startN：endN：stepN]的语法可以进行切片，从而通过一种十分简洁的方式获取数组的某些元素。strided_slice是的我们可以通过Paddle语法的方式完成相应的切割获取相应的元素。例如numpy中#inpu
已修改

2019-09-18 02:01 UTC, jiangjiajun requested changes

2019-09-18 02:01 UTC, jiangjiajun commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +    out = fluid.layers.slice(input, axes=axes, starts=starts, ends=ends, strides=strides)
代码示例写错了，应该是strided_slice，而非slice

2019-09-18 02:01 UTC, jiangjiajun commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +.. py:function:: paddle.fluid.layers.strided_slice(input, axes, starts, ends, strides=strides)
这里接口中strides参数为什么要写上strides=strides

2019-09-18 03:24 UTC, wangchaochaohu commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +.. py:function:: paddle.fluid.layers.strided_slice(input, axes, starts, ends, strides=strides)
已改

2019-09-18 03:24 UTC, wangchaochaohu commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +    out = fluid.layers.slice(input, axes=axes, starts=starts, ends=ends, strides=strides)
已改

2019-09-18 04:40 UTC, jiangjiajun requested changes

2019-09-18 04:40 UTC, jiangjiajun commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +                     ends=[1,0]
这里为什么不用指定axes参数

2019-09-18 04:40 UTC, jiangjiajun commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +我们可以借助numpy数组的索引行为理解这个OP，如果你对numpy数组熟悉的话，应该知道通过[start1：end1：step1，start2：end2：step2，... startN：endN：stepN]的语法可以进行切片，从而通过一种十分简洁的方式获取数组的某些元素。strided_slice使得我们可以通过Paddle语法的方式完成相应的切割并获取相应的元素。例如numpy中inpu
示例里面都写成starts1:ends1这样子吧，另外里面有中英文『:』的混用

2019-09-19 02:22 UTC, wangchaochaohu commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +                     ends=[1,0]
Done

2019-09-19 02:22 UTC, wangchaochaohu commented on doc/fluid/api_cn/layers_cn/stride_slice_cn.rst
> +我们可以借助numpy数组的索引行为理解这个OP，如果你对numpy数组熟悉的话，应该知道通过[start1：end1：step1，start2：end2：step2，... startN：endN：stepN]的语法可以进行切片，从而通过一种十分简洁的方式获取数组的某些元素。strided_slice使得我们可以通过Paddle语法的方式完成相应的切割并获取相应的元素。例如numpy中inpu
Done

2019-09-19 03:33 UTC, jiangjiajun approved these changes

2019-09-19 12:50 UTC, heavengate approved these changes

2019-09-19 12:59 UTC, kuke approved these changes

2019-09-20 12:35 UTC, zq19 commented
Please add the PR to http://wiki.baidu.com/pages/viewpage.action?pageId=917662867

2019-09-26 03:42 UTC, closed without merging