Modify L1DecayRegularizer, L1Decay, L2DecayRegularizer and L2Decay
PaddlePaddle/docs pull request #1217
Opened 2019-09-21 08:22 UTC by juncaipeng

Modify L1DecayRegularizer, L1Decay, L2DecayRegularizer and L2Decay

![image](https://user-images.githubusercontent.com/52520497/65370486-d0040500-dc8b-11e9-9200-ea9a426e0c7b.png)

![image](https://user-images.githubusercontent.com/52520497/65370491-dd20f400-dc8b-11e9-947b-eddf338ecdc1.png)

![image](https://user-images.githubusercontent.com/52520497/65370501-eca03d00-dc8b-11e9-865b-e0e74d7df53a.png)

![image](https://user-images.githubusercontent.com/52520497/65370502-f75ad200-dc8b-11e9-97dc-cd41f69a87af.png)

2019-09-23 07:47 UTC, wzzju requested changes

2019-09-23 07:47 UTC, wzzju commented on doc/fluid/api_cn/regularizer_cn/L1DecayRegularizer_cn.rst
>      import paddle.fluid as fluid
加上适当的空行，便于代码阅读，如import之后空行。

2019-09-23 07:47 UTC, wzzju commented on doc/fluid/api_cn/regularizer_cn/L1Decay_cn.rst
> +    import paddle.fluid as fluid
加上适当的空行，便于代码阅读，如import之后空行。

2019-09-23 07:47 UTC, wzzju commented on doc/fluid/api_cn/regularizer_cn/L2DecayRegularizer_cn.rst
>      import paddle.fluid as fluid
同上。

2019-09-23 07:47 UTC, wzzju commented on doc/fluid/api_cn/regularizer_cn/L2Decay_cn.rst
> +    import paddle.fluid as fluid
同上。

2019-09-23 08:22 UTC, juncaipeng commented on doc/fluid/api_cn/regularizer_cn/L1DecayRegularizer_cn.rst
>      import paddle.fluid as fluid
> 加上适当的空行，便于代码阅读，如import之后空行。

Done

2019-09-23 08:22 UTC, juncaipeng commented on doc/fluid/api_cn/regularizer_cn/L1Decay_cn.rst
> +    import paddle.fluid as fluid
> 加上适当的空行，便于代码阅读，如import之后空行。

Done

2019-09-23 08:22 UTC, juncaipeng commented on doc/fluid/api_cn/regularizer_cn/L2DecayRegularizer_cn.rst
>      import paddle.fluid as fluid
> 同上。

Done

2019-09-23 08:22 UTC, juncaipeng commented on doc/fluid/api_cn/regularizer_cn/L2Decay_cn.rst
> +    import paddle.fluid as fluid
> 同上。

Done

2019-09-24 13:22 UTC, wzzju approved these changes
LGTM.

2019-09-25 02:32 UTC, Superjomn approved these changes
LGTM

2019-09-25 03:19 UTC, lanxianghit approved these changes
LGTM

2019-09-25 04:16 UTC, merged