update Conv2D_cn.rst, test=develop
PaddlePaddle/docs pull request #1235
Opened 2019-09-21 09:30 UTC by JepsonWong

update Conv2D_cn.rst.

2019-09-25 02:20 UTC, JepsonWong commented
![TreeConv](https://user-images.githubusercontent.com/16509038/65563992-08525e80-df7e-11e9-880f-acad338d50c8.png)
![Pool2D](https://user-images.githubusercontent.com/16509038/65563995-0b4d4f00-df7e-11e9-9957-11ad2e47766f.png)
![FC](https://user-images.githubusercontent.com/16509038/65563999-0d171280-df7e-11e9-804f-41440f387794.png)
![Conv2DTranspose](https://user-images.githubusercontent.com/16509038/65564003-0ee0d600-df7e-11e9-9f05-24d099180e61.png)
![Conv2D](https://user-images.githubusercontent.com/16509038/65564005-11433000-df7e-11e9-9246-2a6e57f1e1ba.png)

2019-09-25 06:39 UTC, JepsonWong commented
FC和Pool2D参照模型组的修改（已merge）

2019-09-25 10:03 UTC, JiabinYang reviewed
some comments

2019-09-25 10:03 UTC, JiabinYang commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +该接口将在神经网络中构建一个二维卷积转置层（Convlution2D Transpose Layer），其根据输入（input）、滤波器参数（num_filters、filter_size）、步长（stride）、填充（padding）、膨胀系数（dilation）、组数（groups）来计算得到输出特征图。输入和输出是 ``NCHW`` 格式，N是批数据大小，C是特征图个数，H是特征图高度，W
``MCHW`` 格式 ？

2019-09-25 10:03 UTC, JiabinYang commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +该接口将在神经网络中构建一个二维卷积转置层（Convlution2D Transpose Layer），其根据输入（input）、滤波器参数（num_filters、filter_size）、步长（stride）、填充（padding）、膨胀系数（dilation）、组数（groups）来计算得到输出特征图。输入和输出是 ``NCHW`` 格式，N是批数据大小，C是特征图个数，H是特征图高度，W
M？

2019-09-25 10:03 UTC, JiabinYang commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +    - :math:`b` ：偏移值，2-D ``Tensor`` ，维度为 ``[M,1]``
M是啥

2019-09-25 17:48 UTC, JepsonWong commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +    - :math:`b` ：偏移值，2-D ``Tensor`` ，维度为 ``[M,1]``
已修正

2019-09-25 17:48 UTC, JepsonWong commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +该接口将在神经网络中构建一个二维卷积转置层（Convlution2D Transpose Layer），其根据输入（input）、滤波器参数（num_filters、filter_size）、步长（stride）、填充（padding）、膨胀系数（dilation）、组数（groups）来计算得到输出特征图。输入和输出是 ``NCHW`` 格式，N是批数据大小，C是特征图个数，H是特征图高度，W
已修正

2019-09-26 06:23 UTC, JiabinYang reviewed
some comments

2019-09-26 06:23 UTC, JiabinYang commented on doc/fluid/api_cn/dygraph_cn/FC_cn.rst
> +该接口将在神经网络中构建一个全连接层。其输入可以是一个 ``Tensor`` 或多个 ``Tensor`` 组成的list（详见参数说明），该接口会为每个输入的Tensor创建一个权重（weights）变量，即一个从每个输入单元到每个输出单元的全连接权重矩阵。全连接层将每个输入Tensor和其对应的权重(weights)相乘得到shape为 :math:`[M, size]` 输出Tensor，
batch_size 多数按照 N来写

2019-09-26 06:23 UTC, JiabinYang commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +返回：无
另外，这个返回值不是无，是一个FC的对象，并且和用户说明，这个对象是callable的，通过（）操作符调用返回的是结果

2019-09-26 08:22 UTC, JepsonWong commented on doc/fluid/api_cn/dygraph_cn/Conv2DTranspose_cn.rst
> +返回：无
done

2019-09-26 08:30 UTC, JepsonWong commented on doc/fluid/api_cn/dygraph_cn/FC_cn.rst
> +该接口将在神经网络中构建一个全连接层。其输入可以是一个 ``Tensor`` 或多个 ``Tensor`` 组成的list（详见参数说明），该接口会为每个输入的Tensor创建一个权重（weights）变量，即一个从每个输入单元到每个输出单元的全连接权重矩阵。全连接层将每个输入Tensor和其对应的权重(weights)相乘得到shape为 :math:`[M, size]` 输出Tensor，
done

2019-09-26 08:45 UTC, JiabinYang approved these changes
LGTM

2019-09-26 08:47 UTC, JiabinYang requested changes
不是构建一个类而是构建类的对象，注意表述准确

2019-09-26 09:56 UTC, JepsonWong commented
> 不是构建一个类而是构建类的对象，注意表述准确

done

2019-09-26 11:16 UTC, JiabinYang approved these changes
LGTM

2019-09-27 08:25 UTC, XiaoguangHu01 approved these changes

2019-09-27 10:10 UTC, merged