Update the doc of save_vars and load_vars
PaddlePaddle/docs pull request #1251
Opened 2019-09-23 03:12 UTC by juncaipeng

![image](https://user-images.githubusercontent.com/52520497/65400076-dd87cf00-ddf2-11e9-83fb-9a2dfcecddde.png)
![image](https://user-images.githubusercontent.com/52520497/65400082-e4aedd00-ddf2-11e9-9f9b-a4f2d0765bcd.png)

![image](https://user-images.githubusercontent.com/52520497/65400093-ed9fae80-ddf2-11e9-85bc-ba59aa856910.png)
![image](https://user-images.githubusercontent.com/52520497/65400094-f3958f80-ddf2-11e9-8336-bef807c674c3.png)

2019-09-23 07:43 UTC, wzzju requested changes

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +该接口从指定目录加载程序中的变量。
“程序”一词改为“main_program指定的Program, ``Program`` 含义详见 :ref:`api_guide_Program`。”此处语句不通顺，可参考[#PR1218](https://github.com/PaddlePaddle/FluidDoc/pull/1218)。

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +通过 ``vars`` 指定需要加载的变量，或者通过 ``predicate`` 筛选需要加载的变量，``vars`` 和 ``predicate`` 不能同时为None。
从什么中筛选，指定筛选范围对象。

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> + - **executor**  (Executor) – 运行的执行器。
建议加上一些基本概念的引用介绍，如Executor和Variabel等，可参考[#PR1218](https://github.com/PaddlePaddle/FluidDoc/pull/1218)

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +    # 用vars来指定变量。
建议加上示例一

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +
建议加上示例二

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +该接口将程序中的变量保存到指定目录。
类似load_vars，改变一下程序的描述，并加上概念引用介绍。

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      - **executor** （Executor）- 运行的执行器。
请加上概念链接介绍。

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      # 用vars来指定变量。
请加上示例一。

2019-09-23 07:43 UTC, wzzju commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      # 通过predicate筛选变量。
请加上示例二。

2019-09-23 09:51 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +该接口从指定目录加载程序中的变量。
> “程序”一词改为“main_program指定的Program, `Program` 含义详见 :ref:`api_guide_Program`。”此处语句不通顺，可参考[#PR1218](https://github.com/PaddlePaddle/FluidDoc/pull/1218)。

程序修改为Program，Program的参考链接在参数说明中。

2019-09-23 09:51 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> + - **executor**  (Executor) – 运行的执行器。
> 建议加上一些基本概念的引用介绍，如Executor和Variabel等，可参考[#PR1218](https://github.com/PaddlePaddle/FluidDoc/pull/1218)

Done

2019-09-23 09:52 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +    # 用vars来指定变量。
> 建议加上示例一

Done

2019-09-23 09:52 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +
> 建议加上示例二

Done

2019-09-23 09:54 UTC, juncaipeng commented
更新截图
![image](https://user-images.githubusercontent.com/52520497/65416685-0035da00-de2b-11e9-8945-5ccb086d0224.png)
![image](https://user-images.githubusercontent.com/52520497/65416714-0f1c8c80-de2b-11e9-86dc-8faa298d03a0.png)

![image](https://user-images.githubusercontent.com/52520497/65416751-1e033f00-de2b-11e9-92f6-00547cc815fc.png)
![image](https://user-images.githubusercontent.com/52520497/65416765-28253d80-de2b-11e9-83f0-34d2305a0c7c.png)

2019-09-24 13:09 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      # 通过predicate筛选变量。
> 请加上示例二。

Done

2019-09-24 13:09 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      # 用vars来指定变量。
> 请加上示例一。

Done

2019-09-24 13:09 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      - **executor** （Executor）- 运行的执行器。
> 请加上概念链接介绍。

Done

2019-09-24 13:09 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +该接口将程序中的变量保存到指定目录。
> 类似load_vars，改变一下程序的描述，并加上概念引用介绍。

Done

2019-09-24 13:10 UTC, juncaipeng commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> +通过 ``vars`` 指定需要加载的变量，或者通过 ``predicate`` 筛选需要加载的变量，``vars`` 和 ``predicate`` 不能同时为None。
> 从什么中筛选，指定筛选范围对象。

Done

2019-09-24 13:15 UTC, wzzju approved these changes
LGTM.

2019-09-25 02:32 UTC, Superjomn approved these changes
LGTM

2019-09-25 03:38 UTC, lanxianghit commented on doc/fluid/api_cn/io_cn/load_vars_cn.rst
> + - **executor**  (Executor) – 运行的执行器，执行器的介绍请参考 :ref:`api_guide_model_save_reader` 。
执行器的介绍请参考 :ref:`api_guide_model_save_reader`
执行器的介绍，参考的是save_reader，请确认是否正确？

2019-09-25 03:38 UTC, lanxianghit commented on doc/fluid/api_cn/io_cn/save_vars_cn.rst
> +      - **executor** （Executor）- 运行的执行器，执行器的介绍请参考 :ref:`api_guide_model_save_reader` 。
同上

2019-09-25 04:17 UTC, merged