Refine DGCMomentumOptimizer doc
PaddlePaddle/docs pull request #1283
Opened 2019-09-23 14:08 UTC by wangxicoding

DGCMomentumOptimizer
![dgc](https://user-images.githubusercontent.com/10208305/65432724-3bc0ac00-de0b-11e9-8fec-f1d78488d699.jpg)

2019-09-24 01:35 UTC, gongweibao requested changes
句子不通顺，还是polish一下！

2019-09-24 14:06 UTC, wangxicoding commented
更新
![dgc_cn](https://user-images.githubusercontent.com/10208305/65518791-63c81200-ded4-11e9-9362-55c774581acf.png)

2019-09-25 07:25 UTC, gongweibao approved these changes
LGTM

2019-09-25 07:56 UTC, hutuxian approved these changes

2019-09-25 13:00 UTC, merged