[MKL-DNN] Design document on acquire API
PaddlePaddle/docs pull request #1420
Opened 2019-09-26 15:24 UTC by jczaja

This PR is providing document on design and usage (for developers of paddle mkl-dnn kernels) of Acquire API.

Rendered version:
https://github.com/jczaja/FluidDoc/blob/prv-acquire/doc/fluid/design/mkldnn/acquire_api/acquire_api.md

@grygielski, @Sand3r-, @bingyanghuang, @luotao1  Please review

2019-09-27 06:58 UTC, grygielski requested changes
Great work, really good explanation! I would suggest just one change I mentioned below.

2019-09-27 06:58 UTC, grygielski commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +            .data.format;
Please change it to `auto output_format = platform::GetMKLDNNFormat(dst_memory);` as this is the function doing exactly same thing, but it's much more clear and won't be outdated once mkl-dnn v1.0 come.

2019-09-27 08:36 UTC, jczaja commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +            .data.format;
@grygielski good suggestion. I have introduced requested modification

2019-09-27 08:38 UTC, grygielski approved these changes
Thanks for introducing suggested changes! LGTM

2019-09-30 13:41 UTC, jczaja commented
@luotao1 Could you please review this PR?

2019-10-10 00:40 UTC, bingyanghuang commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +MKL-DNN kernels that are using mkl-dnn API tend to be quite complex due to:
mkl-dnn --> MKL-DNN

2019-10-10 00:40 UTC, bingyanghuang commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +* number of mkl-dnn api calls needed, which in fact are mostly repeated across all  mkl-dnn kernels
mkl-dnn --> MKL-DNN Please unify the MKL-DNN in the doc.

2019-10-10 00:40 UTC, bingyanghuang commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +* caching mechanism of mkl-dnn objects  (similar concept in every paddle operator mkl-dnn kernel)
kernel --> kernels

2019-10-10 09:15 UTC, jczaja commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +* caching mechanism of mkl-dnn objects  (similar concept in every paddle operator mkl-dnn kernel)
ok

2019-10-10 09:15 UTC, jczaja commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +* number of mkl-dnn api calls needed, which in fact are mostly repeated across all  mkl-dnn kernels
ok

2019-10-10 09:15 UTC, jczaja commented on doc/fluid/design/mkldnn/acquire_api/acquire_api.md
> +MKL-DNN kernels that are using mkl-dnn API tend to be quite complex due to:
ok

2019-10-10 09:17 UTC, jczaja commented
@bingyanghuang Thanks for reviewing my changes. I have followed your suggestions.

2019-10-10 09:20 UTC, bingyanghuang commented
@jczaja LGTM. @luotao1 Please start your review.

2019-10-11 04:03 UTC, luotao1 approved these changes
LGTM

2019-10-11 04:03 UTC, merged