Add check nan inf tools doc
PaddlePaddle/docs pull request #1658
Opened 2019-12-12 12:55 UTC by wangxicoding

We rewrite check nan inf tools in this PR https://github.com/PaddlePaddle/Paddle/pull/21076
Add check_nan_inf_cn document to this tools。

2019-12-12 12:55 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FluidDoc?pullRequest=1658) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FluidDoc?pullRequest=1658) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FluidDoc?pullRequest=1658) it.</sub>

2019-12-12 12:58 UTC, wangxicoding commented
can preview this https://github.com/PaddlePaddle/FluidDoc/blob/b2b6109e455155ac611a3be95a03ab3bb44804db/doc/fluid/flags/check_nan_inf_cn.md

2019-12-13 02:33 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_cn.md
> +***`注意`：本文档的进阶使用、速度、原理目前仅在develop的paddle版本生效。***
本文档的进阶使用、速度、原理目前仅在develop的paddle版本生效，并将随1.7发布。

2019-12-13 11:24 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_cn.md
> +***`注意`：本文档的进阶使用、速度、原理目前仅在develop的paddle版本生效。***
Done.

2019-12-13 11:39 UTC, gongweibao approved these changes
LGTM

2019-12-16 03:42 UTC, Boyan-Liu approved these changes
LGTM

2019-12-16 03:47 UTC, Boyan-Liu requested changes
麻烦提交对应的英文文档。

2020-02-17 06:14 UTC, wangxicoding commented
英文文档，可以预览
https://github.com/PaddlePaddle/FluidDoc/blob/cd7dbdfd77cf3b03223ce9ac3c1a07f6e488b6ac/doc/fluid/flags/check_nan_inf_en.md
或者截图
![image](https://user-images.githubusercontent.com/10208305/74628146-d1c8ea80-518f-11ea-8c89-f10a4b131b6e.png)

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +`The speed may be different under different environment and different model datasets. The following speeds are only for reference`
environments.

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +# check nan inf tool
check_nan_inf tool?

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +***`Note`: The Advanced use, Speed, and Principles of this document are currently only effective in the develop version of the Paddle, and will be released with the 1.7 version of the Paddle.
The Advanced use: Speed, and Principles

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +Test environment: v100 32G single card, Resnet50 model, imagenet dataset.
Imagenet

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +However in `fp16` training, inf will be corrected in the back propagation, so it is generally necessary to skip the backward check, which is also the reason of add this function.
backpropagation

2020-02-17 07:40 UTC, gongweibao commented on doc/fluid/flags/check_nan_inf_en.md
> +However in `fp16` training, inf will be corrected in the back propagation, so it is generally necessary to skip the backward check, which is also the reason of add this function.
addition? of adding?

2020-02-17 10:31 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +`The speed may be different under different environment and different model datasets. The following speeds are only for reference`
done.

2020-02-17 10:35 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +***`Note`: The Advanced use, Speed, and Principles of this document are currently only effective in the develop version of the Paddle, and will be released with the 1.7 version of the Paddle.
Speed, and Principles do not belong to Advanced use.

2020-02-17 10:35 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +Test environment: v100 32G single card, Resnet50 model, imagenet dataset.
done.

2020-02-17 10:36 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +However in `fp16` training, inf will be corrected in the back propagation, so it is generally necessary to skip the backward check, which is also the reason of add this function.
done

2020-02-17 10:36 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +However in `fp16` training, inf will be corrected in the back propagation, so it is generally necessary to skip the backward check, which is also the reason of add this function.
done

2020-02-17 10:45 UTC, wangxicoding commented on doc/fluid/flags/check_nan_inf_en.md
> +However in `fp16` training, inf will be corrected in the back propagation, so it is generally necessary to skip the backward check, which is also the reason of add this function.
Chang to: which is why this feature is added.

2020-02-17 11:41 UTC, gongweibao approved these changes
LGTM

2020-02-18 12:25 UTC, wangxicoding commented
> 麻烦提交对应的英文文档。

Done.

2020-02-19 03:52 UTC, Boyan-Liu approved these changes

2020-02-19 03:59 UTC, merged