Repair DGC low bandwidth doc formula disorder
PaddlePaddle/docs pull request #1873
Opened 2020-03-03 14:16 UTC by wangxicoding

修复公式显示错乱。预览
![火狐截图_2020-03-03T14-02-24 302Z](https://user-images.githubusercontent.com/10208305/75784052-94be4400-5d9c-11ea-82fc-074c8fda2584.png)
![火狐截图_2020-03-03T14-02-30 089Z](https://user-images.githubusercontent.com/10208305/75784067-9ab42500-5d9c-11ea-95f9-74bfb4468a4d.png)

2020-03-04 16:05 UTC, wangxicoding commented
添加英文文档
![火狐截图_2020-03-04T15-57-12 495Z](https://user-images.githubusercontent.com/10208305/75898330-e20de480-5e74-11ea-94f3-93dd3f0fdc89.png)
![火狐截图_2020-03-04T15-57-18 872Z](https://user-images.githubusercontent.com/10208305/75898338-e5a16b80-5e74-11ea-9f05-8efb539b1ac3.png)

2020-03-06 08:20 UTC, gongweibao requested changes

2020-03-06 08:20 UTC, gongweibao commented on doc/fluid/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_low_bandwidth_dgc.md
> +DGC稀疏通信算法以DGCMomentumOptimizer接口的形式提供，目前只支持GPU多卡及GPU多机分布式，由于现有fuse策略会造成DGC失效，所以使用DGC时需设置`strategy.fuse_all_reduce_ops=False`关闭fuse。DGC只支持Momentum优化器，使用时把当前代码中的Momentum优化器替换为DGCMomentumOptimizer，并添加DG
这个地方使用DGC的时候我们自己可否检测到然后关闭这个选项？

2020-03-06 09:55 UTC, wangxicoding commented on doc/fluid/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_low_bandwidth_dgc.md
> +DGC稀疏通信算法以DGCMomentumOptimizer接口的形式提供，目前只支持GPU多卡及GPU多机分布式，由于现有fuse策略会造成DGC失效，所以使用DGC时需设置`strategy.fuse_all_reduce_ops=False`关闭fuse。DGC只支持Momentum优化器，使用时把当前代码中的Momentum优化器替换为DGCMomentumOptimizer，并添加DG
应该可以，我看下怎么加。不过后面加了也只能在1.7之前的版本了

2020-03-06 10:03 UTC, gongweibao commented on doc/fluid/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_low_bandwidth_dgc.md
> +DGC稀疏通信算法以DGCMomentumOptimizer接口的形式提供，目前只支持GPU多卡及GPU多机分布式，由于现有fuse策略会造成DGC失效，所以使用DGC时需设置`strategy.fuse_all_reduce_ops=False`关闭fuse。DGC只支持Momentum优化器，使用时把当前代码中的Momentum优化器替换为DGCMomentumOptimizer，并添加DG
加一下吧，如果需要记住的话，大概率出错。

2022-02-17 02:10 UTC, closed without merging