[oneDNN] Doc on how keys used for oneDNN cache are made of
PaddlePaddle/docs pull request #2912
Opened 2020-11-20 14:41 UTC by jczaja

This PR is adding an article on how keys used for caching mechanism of oneDNN objects are created.

Rendered version of document:
https://github.com/jczaja/FluidDoc/blob/prv-keys/doc/fluid/design/mkldnn/caching/keys.md

2020-11-20 15:13 UTC, jczaja commented
@jakpiase, @alesniak, @arogowie-intel  could you help with review?

2020-11-20 16:13 UTC, jakpiase requested changes
Some misspellings need to be corrected

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/caching.md
>  In more detail MKL-DNN Cache is stored inside MKL-DNN Device Context and it consists of three level of unordered maps based structure. Picture below outlines mentioned architecture:
levels*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +[Caching](./caching.md) is a mechanism using associative objects so there is a key and stored value. This document describe ideas behind
describes*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +construction of keys used for caching oneDNN objects. Maintaining of keys is an ongoing effort so they tend to evolve.
the construction

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +Key may consists of a several elements:
Key may consist of several elements

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +The foundation of generation of key is name of output Tensor of given instance of operator. The reason for that is operators in PaddlePaddle are stateless. So for example
The foundation of the generation of a key is the name of output Tensor of a given instance of an operator.

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +the same kernel implementing convolution operation will be used regardless the shapes and attributes of convolution. In practice this kernel for diffrent shapes, attributes, data format may require
So for example the same kernel implementing convolution operation will be used regardless of the shapes and attributes of convolution. In practice, this kernel for different shapes, attributes, data format may require

All this sentence that begins with "In practice" sounds weird to me

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +diffrent oneDNN convolution primitive. As instance of convolution is identified uniquely with name of its output tensor then this name of output tensor was used as part of caching key.
different oneDNN convolution primitive. As an instance of convolution is identified uniquely with the name of its output tensor then this name of output tensor was used as part of the caching key.

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +One of situations when output tensor name is not enough to uniquely identify the instance of operator is when operators are performing [inplace](../inplace/inplace.md) execution. In this situation
One of the situations, when output tensor name is not enough to uniquely identify the instance of the operator, is when operators are performing [inplace](../inplace/inplace.md) execution. In this situation

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +one of inputs and one of outputs of operator are the same Paddle Tensor and its name is the same so it is not enough to uniquely indentify instance of operator. So for that situation
one of the inputs and one of the outputs of the operator are the same Paddle Tensor and its name is the same so it is not enough to uniquely identify the instance of an operator. So for that situation

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +operators supprting inplace execution mode are having its caching key extended as follows:
supporting*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +* softmax's key is having a value of attribute of normalization axe added
an attribute

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +* activation's key is having an enum determining type of activation added
the type*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +Another situation is when PaddlePaddle is executing a model where the input shape can vary from iteration to iteration . This happens with NLP (BERT, ERNIE) models.
delete space between "iteration" and "."

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +Then given operator instance may process diffrent input signal each iteration and oneDNN primitive potentialy may use diffrent implementation , so to stay on save side
Then given operator instance may process different input signal each iteration and oneDNN primitive potentially may use a different implementation, so to stay on save side

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +we need to include input tensor shape information into caching key.
into the caching key*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +On a scenario when there are are multiple models executed in a interleaved mode e.g. one iteration of model A followed by one iteration of model B and then again one iteration of model A , it
In a scenario*
delete space between "model A" and ","

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +is needed to also add information to they key on what model is executed to avoid sitation that weights of one model will be used for weights of other model. Model during inference is connected
is needed to also add information to their key on what model is executed to avoid a situation that weights of one model will be used for weights of other models. A model during inference is connected

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +to Executor or Naive Executor so part of address of used Executor or Naive Executor is made a part of key as well.
the address*
the key*

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +When there is a multi-threaded execution of model e.g. Paralel Executor where there are multiple threads executing single model or number of threads where each of them is executing its own model
When there is a multi-threaded execution of model e.g. Parallel Executor where there are multiple threads executing a single model or a number of threads where each of them is executing its own model

but imo all the sentence sounds weird

2020-11-20 16:13 UTC, jakpiase commented on doc/fluid/design/mkldnn/caching/keys.md
> +then it is needed to add to the information on Thread ID which is a hash of thread id (provided by C++ thread structures). This element is only aplied when cache is working in a mode where
applied*

2020-11-23 07:52 UTC, wojtuss commented
General note: for persistables like weights and biases we want to use keys consisting of a thread id and the variable name only. These two features are enough to identify the tensors and are available when saving (INT8, in particular) models with the tensors taken from the mkldnn cache.

2020-11-23 13:54 UTC, jczaja commented
@jakpiase Thanks for enormous effort in pointing out mistakes. I introduced suggested fixes (all, I hope).

@wojtuss I agree with you , currently this is only implemented in fusion gru mkldnn op, but once this is done in other ops we could update this doc

2020-11-23 15:16 UTC, arogowie-intel approved these changes
Great you have documented it. Sounds clear. Just found few minor spelling things.

2020-11-23 15:16 UTC, arogowie-intel commented on doc/fluid/design/mkldnn/caching/keys.md
> +On a scenario when there are are multiple models executed in a interleaved mode e.g. one iteration of model A followed by one iteration of model B and then again one iteration of model A, it
```suggestion
On a scenario when there are multiple models executed in a interleaved mode e.g. one iteration of model A followed by one iteration of model B and then again one iteration of model A, it
```

2020-11-23 15:16 UTC, arogowie-intel commented on doc/fluid/design/mkldnn/caching/keys.md
> +is needed to also add information to they key on what model is executed to avoid a situation that weights of one model will be used for weights of other model. Model during inference is connected
```suggestion
is needed to also add information to the key on what model is executed to avoid a situation that weights of one model will be used for weights of other model. Model during inference is connected
```

2020-11-23 15:16 UTC, arogowie-intel commented on doc/fluid/design/mkldnn/caching/keys.md
> +Thread based information is needed as PaddlePaddle is often used in a multi-threaded execution of model e.g. Parallel Executor where there are multiple threads executing a single model or a number of
```suggestion
Thread based information is needed as PaddlePaddle is often used in a multi-threaded execution of model e.g. Parallel Executor where there are multiple threads executing a single model or a number of threads where each of them is executing its own model. Then it is needed to add to the key information about Thread ID which is a hash of thread id (provided by C++ thread structures). This element is only applied when cache is working in a mode where
```

2020-11-23 15:16 UTC, arogowie-intel commented on doc/fluid/design/mkldnn/caching/keys.md
> +the same kernel implementing convolution operation will be used regardless the shapes and attributes of convolution. In fact this kernel for different shapes, attributes, data format may require
```suggestion
the same kernel implementing convolution operation will be used regardless of the shapes and attributes of convolution. In fact this kernel for different shapes, attributes, data format may require
```

2020-11-23 17:52 UTC, jczaja commented
@arogowie-intel Thanks very much for insightful review. I fixed pointed mistakes

2020-11-23 17:53 UTC, jczaja commented
@luotao1 Could you please start your review?

2020-11-24 07:46 UTC, luotao1 approved these changes
LGTM!!!

2020-11-24 07:46 UTC, merged