Second 16 translation
PaddlePaddle/docs pull request #319
Opened 2018-11-08 09:35 UTC by Mddct

paddle 15个翻译

2018-11-08 09:53 UTC, shanyi15 commented
Thanks for your translation, please wait for the review.

2018-11-12 03:45 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +	- output_size (int|tuple|None) : 输出照片的大小。如果output_size是一个元组（tuple），则该元形式为（image_H,image_W),这两个值必须为整型。如果output_size=None,则内部会使用filter_size、padding和stride来计算output_size。如果output_size和filter_size是同时指定的
照片 ==》 图片

2018-11-12 08:37 UTC, tink2123 reviewed
cool！！只有一些格式问题需要修改~其中链接引用 请参照第一处链接相关的 comment 的格式调整一下。

2018-11-12 08:37 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +计算并返回噪音对比估计（ noise-contrastive estimation training loss）。请参考` See Noise-contrastive estimation: A new estimation principle for unnormalized statistical models <http://www.jmlr.org/proceedings/papers/
引用应写成

```
`请参考 See Noise-contrastive estimation: A new estimation principle for unnormalized statistical models <http://www.jmlr.org/proceedings/papers/v9/gutmann10a/gutmann10a.pdf>`_
```

2018-11-12 08:37 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +请参考` Hierarchical Probabilistic Neural Network Language Model <http://www.iro.umontreal.ca/~lisa/pointeurs/hierarchical-nnlm-aistats05.pdf>`_
同上 修改格式

2018-11-12 08:37 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +    ` http://www.cs.cmu.edu/~dyogatam/papers/wang+etal.iclrworkshop2016.pdf<http://www.cs.cmu.edu/~dyogatam/papers/wang+etal.iclrworkshop2016.pdf>`_
链接复制了两遍吗？

2018-11-12 08:37 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +    参数:
去掉参数部分多余的缩进，否则会和上面的例子写在一个块内

2018-11-12 08:37 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +.. math::       dice_loss = 1- frac{2 * intersection_area}{total_rea} = frac{((total_area−intersection_area)−intersection_area)}{total_area}=frac{union_area−intersection_area}{total_area}
.. math:: 表述段内公式，需要将公式放在下一行，且有两个缩进

2018-11-13 10:41 UTC, haowang101779990 requested changes

2018-11-13 10:41 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +该层根据 输入（input）、滤波器（filter）和卷积核膨胀（dilations）、步长（stride）、填充（padding）来计算输出。输入(Input)和输出(Output)为NCHW格式，其中N为batch大小，C为通道数（channel），H为特征高度，W为特征宽度。参数(膨胀、步长、填充)分别都包含两个元素。这两个元素分别表示高度和宽度。欲了解卷积转置层细节，请参考下面的说明和参
原文''therein‘’索引了个外部链接引用，参考添加如下~
**中文原文“参考文献”前面空格、后面跟  _  和 空格**，才能在官网正常显示~
```suggestion
该层根据 输入（input）、滤波器（filter）和卷积核膨胀（dilations）、步长（stride）、填充（padding）来计算输出。输入(Input)和输出(Output)为NCHW格式，其中N为batch大小，C为通道数（channel），H为特征高度，W为特征宽度。参数(膨胀、步长、填充)分别都包含两个元素。这两个元素分别表示高度和宽度。欲了解卷积转置层细节，请参考下面的说明和 参考文献_ 。如果参数bias_attr和act不为None，则在卷积的输出中加入偏置，并对最终结果应用相应的激活函数。

.. _参考文献: http://www.matthewzeiler.com/wp-content/uploads/2017/07/cvpr2010.pdf
```

2018-11-13 10:41 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +    输入张量的shape: （N，C_in， H_in， W_in)
公式需要修改一下，那个in作为一整个下标要用{}括起来要不然n会成为下一个项了哈
建议使用网页LateX公式显示器看下效果~出现这样的下标的公式比较多，辛苦改一下
```suggestion
    输入张量的shape: （N，C_{in}， H_{in}， W_{in})
```

2018-11-13 10:41 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +                        Out=σ(W∗X+b)
用公式打出来在网页里显示效果会好很多~
https://www.codecogs.com/latex/eqneditor.php
这个编辑器渲染出来的效果和官网相同，可以用这个显示看看~
请注意下.. math::要顶头，独立成行，前面没有空格，否则会因为“等式如下：”的冒号把公式显示成列表哦

```suggestion
.. math::
                        \\Out=\sigma (W*X+b)\\
                      
```

2018-11-13 10:41 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +    - Out：输出值，Out和X的shape可能不一样
为了保证在官网页面正常显示，行内公式重新统一格式为：
其中`为反引号，
字[空格]:math:`X=Y`[空格]后面的内容

烦请改一下

```suggestion
输入X和输出Out函数关系 :math:`X` 有等式如下：

.. math::
			   
                        \\Out=\sigma (W*X+b)\\

其中：
    -  :math:`X` : 输入张量，具有NCHW格式

    -  :math:`W` : 滤波器张量，，具有NCHW格式

    -  :math:`*` : 卷积操作

    -  :math:`b` : 偏置（bias），二维张量，shape为[m,1]

    -  :math:`σ` : 激活函数
 
    -  :math:`Out` : 输出值，Out和X的shape可能不一样
```

2018-11-13 10:41 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +    - Out：输出值，Out和X的shape可能不一样
##效果图
![image](https://user-images.githubusercontent.com/31058429/48408091-6ebdfc00-e773-11e8-8046-a55732cf5b36.png)
##对应样式代码（用于空格参考）
![image](https://user-images.githubusercontent.com/31058429/48408128-839a8f80-e773-11e8-8ace-caa73106e9c2.png)

2018-11-14 15:08 UTC, haowang101779990 requested changes

2018-11-14 15:08 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +	- name (str|None) : 该layer的名称(可选)。如果设置为None， 将自动命名该layer。默认值:True。
参数部分经过商议，在官网上不会把它们显示成粗体，脚本也不好改。。所以麻烦您把此次pr的和以后将要pr的作品参数部分这个样子，粗体部分会在github上有预览的~：
```suggestion
	-  **name** (str|None) -  该layer的名称(可选)。如果设置为None， 将自动命名该layer。默认值:True。
```
之前merge掉的作品我会替您改变这个样式~谢谢，辛苦辛苦！

2018-11-14 15:08 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +该层根据 输入（input）、滤波器（filter）和卷积核膨胀（dilations）、步长（stride）、填充来计算输出。输入(Input)和输出(Output)为NCDHW格式。其中N为batch大小，C为通道数（channel），D 为特征深度,H为特征高度，W为特征宽度。参数(膨胀、步长、填充)分别包含两个元素。这两个元素分别表示高度和宽度。欲了解卷积转置层细节，请参考下面的说明和参考
英文版本对于解释段落中的api名有代码样式高亮，中文版本应该统一。采用  ``some_api`` 的方式就可以啦~ 双反引号，前后都有一个空格，在github preview里面可以看到灰色背景的效果和参数部分一样之前merge掉的部分我帮您改掉，此次pr和以后的作品麻烦您留意一下~然后这里原文也是有外部链接的，已经帮您复制过来了
```suggestion
该层根据 输入（input）、滤波器（filter）和卷积核膨胀（dilations）、步长（stride）、填充来计算输出。输入(Input)和输出(Output)为NCDHW格式。其中N为batch大小，C为通道数（channel），D 为特征深度,H为特征高度，W为特征宽度。参数(膨胀、步长、填充)分别包含两个元素。这两个元素分别表示高度和宽度。欲了解卷积转置层细节，请参考下面的说明和 参考文献_ 。如果参数 ``bias_attr`` 和 ``act`` 不为None，则在卷积的输出中加入偏置，并对最终结果应用相应的激活函数

.. _参考文献: http://www.matthewzeiler.com/wp-content/uploads/2017/07/cvpr2010.pdf
```

因为网页端渲染的的有些出乎意料的不那么智能，麻烦您照着这些格式修改此次pr和以后pr的参数、段内api引用部分，感谢！

2018-11-28 02:57 UTC, tink2123 approved these changes
LGTM!Thanks~  plz resolve the conflict

2018-11-28 03:52 UTC, haowang101779990 approved these changes

2018-11-28 05:37 UTC, merged