Hy 2 21
PaddlePaddle/docs pull request #340
Opened 2018-11-14 14:02 UTC by HongyingG

1.modification according to review
2.21 new api trans
3.math problem still remain to be solved

2018-11-15 05:53 UTC, tink2123 commented
看到changes里提交了两个不同名的rst文档，但并不是两个完全不同的内容。关于提交PR的流程，可能还需要明确一下。

2018-11-15 06:49 UTC, HongyingG commented
> 看到changes里提交了两个不同名的rst文档，但并不是两个完全不同的内容。关于提交PR的流程，可能还需要明确一下。

是，两份rst文件的内容相同，文件名不同。以为第一份文件未提交成功，所以更改文件名重新提交了一次....

2018-11-19 02:50 UTC, haowang101779990 requested changes

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +=====
```suggestion
>>>>>>>>>>>>>>
```
请将今后所有的api大标题统一成示例格式 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst 中的 >>>>>>>>>，如果不这么做最后合并时与其他同学不同的符号会产生分级现象导致混乱（哭）。麻烦您及时更改并在以后的作品中注意这一点

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +=====
还有，符号的长度要长于标题字的长度~

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * x(Variable)-equal的第一个操作数
1. 参数部分，依旧参照 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst 部分，\* 不建议使用，因为可能有的参数为指针类型，带着\*会与前面这个\*联合起来使列表失效。格式按照示例中的要求就可以了。

2. 参数：
    这里不要有空行，否则渲染出来的效果不一样（哭）
    请严格按照示例~

3. 参数名应该用粗体高亮，比如  - **somev** (Variable) - balabala
      在github中能看到粗体就ok

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +
请删除此空行，解释在下面

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * x(Variable)-equal的第一个操作数
粗体语法：   [空格]\*\*要粗体的东西\*\*[空格]

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +该层返回元素x,y逐元素相等的值
您看这样怎么样？

```suggestion
该层返回 :math:'x==y' 按逐元素运算而得的真值。
```

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +代码示例:
麻烦您将“代码示例”像案例 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst 一样的粗体化一下~下同。一开始格式方面可能更改比较多，加油！

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +==========
如上，标题符号~

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. py:class:: paddle.fluid.layers. equal(x,y,cond=None,**ignored)
```suggestion
.. py:class:: paddle.fluid.layers.equal(x,y,cond=None,**ignored)
```

英文版本里面看起来equal这种函数名前面有个空格的样子，但是这是网页渲染出来的效果。请去掉所有这样的空格，否则无法正常被网页渲染。辛苦啦

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. py:class:: paddle.fluid.layers. array_read(array,i)
还是那个魔鬼空格，麻烦您杀掉它
```suggestion
.. py:class:: paddle.fluid.layers.array_read(array,i)
```

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. code-block:: python
```suggestion
::
```
请参照示例 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst ，使用:: 的方式处理非代码示例的文字示例块~~~

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * i(Variable|list)-输入数组中数据的索引
还是参数那三点~用-索引，参数:下一行没有空行，参数名粗体化，后面的我就不重复啦，麻烦您统一改一下
- \*\*i\*\* (type) - balabala

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +参数：array(LOD_TENSOR_ARRAY)-输入数组，用来计算数组长度
虽然只有一行，还是按照列表形式展现吧，统一起来好看。还是按照上面的要点~

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +代码示例:
**代码示例**：

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +提示：抛出异常-如果input不是变量或cond类型不是变量
```suggestion
抛出异常： ``TypeError`` - 如果input不是变量或cond类型不是变量
```
注意~  TypeError用双反引号标出来，github preview里面会看到灰底，在官网上显示效果就是英文那样的了。然后解释段落、参数解释段落中出现的api名字，也需要这样标出来，在官网上渲染效果和英文就一样了~后面遇到我会指出

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +该功能接受输入数据，根据是否返回minibatch用辅助函数创建全局变量。可通过以下所有操作命令访问全局变量。
```suggestion
该功能接受输入数据，根据是否返回minibatch用辅助函数( ``helper`` )创建全局变量。可通过以下所有操作命令访问全局变量。
```

helper是paddle里面的一个类我记得 @tink2123

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +该函数输入的所有变量作为局部变量传到LayerHelper构造器
```suggestion
该函数输入的所有变量作为局部变量传到 ``LayerHelper`` 构造器
```

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +reader也是变量。可以为由fluid.layers.open_files()生成的原始reader或者由fluid.layers.double_buffer()生成的装饰变量，等等。
```suggestion
reader也是变量。可以为由 ``fluid.layers.open_files()`` 生成的原始reader或者由 ``fluid.layers.double_buffer()`` 生成的装饰变量，等等。
```

把解释段落中api的名字用双反引号 ``api名字`` 标出来叭，然后前后各一个空格，在github preview中是灰底样式

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +
虽然只有一个参数，但还是按照列表统一格式

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * reader(Variable)-装饰有“batching”的reader变量
参数:
    - **reader** (Variable) - 待进行 “batching” 装饰的reader变量


注：review里看不到我写的缩进，麻烦您看raw代码

文字内容, @tink2123 劳烦审核一下

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * lod_levels(list)-整形数列表，声明数据
```suggestion
    * lod_levels(list)-整形数列表，声明数据Lod （level of details）信息
```
@tink2123

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. py:class:: class paddle.fluid.layers.Preprocessor(reader, name=None)
```suggestion
.. py:class:: paddle.fluid.layers.Preprocessor(reader, name=None)
```
有一个坑出现了orz。若原文api路径里面含有class，请删除。比如您这儿没有上述魔鬼空格，却有这个class，也是不能正常显示的。辛苦啦

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. py:class:: class paddle.fluid.layers.IfElse(cond, name=None)
```suggestion
.. py:class:: paddle.fluid.layers.IfElse(cond, name=None)
```
一个坑orz。为保证正常显示，请删除原文api中一开始的class

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +    * load_as_fp16(BOOLEAN)-如果为真，张量首先进行加载然后转换成float16数据类型。如果为假，张量无数据类型转换直接进行加载。默认为false。
```suggestion
    -  **load_as_fp16** (BOOLEAN)-如果为 ``True``，张量首先进行加载然后转换成float16数据类型。如果为 ``False``，张量无数据类型转换直接进行加载。默认为false。
```
函数值不翻译出来为好，用代码形式高亮即可~~

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. _cn_api_fluid_layers_array_read:
.. _cn_api_fluid_layers_array_read:

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +.. _cn_api_fluid_layers_array_read:
```suggestion
.. _cn_api_fluid_layers_array_read:
```

2018-11-19 02:50 UTC, haowang101779990 commented on layers_cn_hy_1114.rst
> +相关API::ref:'api_fluid_layers_array_read',:ref:'api_fluid_layers_array_write',ref:'api_fluid_layers_While'.
```suggestion
相关API :ref:`cn_api_fluid_layers_array_read` , :ref:`cn_api_fluid_layers_array_write` , :ref:`cn_api_fluid_layers_While` 。
```

需要注意以下几点，非常重要：
1. 格式为      [空格]:ref:`cn_api_fluid_layers_array_read`[空格]   其中，\` 为反引号，rst的语句中很少出现引号。包括api高亮，数学行内公式 :math:`some equation` 也是这样。 
2. 注意索引，此处的cn前面没有_,read后面没有:
3. 请注意在具体api前写的索引，确保：英文的: 与_, :后面注意不要有空格

辛苦检查一下，我也会帮您引用检查。

2018-11-28 07:17 UTC, shanyi15 commented
close via https://github.com/PaddlePaddle/FluidDoc/pull/359

2018-11-28 07:17 UTC, closed without merging