First translation by xx(second modified)
PaddlePaddle/docs pull request #344
Opened 2018-11-15 13:58 UTC by ShangCambridge

2018-11-19 03:38 UTC, haowang101779990 requested changes

2018-11-19 03:38 UTC, haowang101779990 commented on layers_cn.rst
> +'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
参照 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst
.. py:class:: 不需要做成标题
辛苦删除一下所有.. py:class:: 下面的 ’‘’‘’‘’‘’‘ 层

2018-11-19 03:38 UTC, haowang101779990 commented on layers_cn.rst
> +..  code-block:: python
例子最好使用 https://raw.githubusercontent.com/shanyi15/API-translation/master/layers_cn.rst 那个 ::的格式，在github previw中会用灰底显示即可

2018-11-19 03:38 UTC, haowang101779990 commented on layers_cn.rst
> +- input（Variable）: 作为索引序列的输入变量。
参数 ** **还没有改哦

2018-11-19 03:38 UTC, haowang101779990 commented on layers_cn.rst
> +:::::::::::::::::::::::
经过试验，还是最好统一使用例子中的标题符号，因为最后要和其他同学合并起来，符号不同的话rst默认是将其分级的。
```suggestion
>>>>>>>>>>>>
```
注意符号最好要长于符号上面的标题字

哭泣，辛苦改一下所有的api的主标题，符号一定是示例中的 >>>>>即可

2018-11-21 03:37 UTC, tink2123 reviewed
very good！！Only a few formatting errors

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +        - **x**(Variable) ：(Tensor) 要比例运算的输入张量（Tensor）。
(variable)前请增加一个空格

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +        $$Out = X + Y$$
因为我们的公式整个被写在了 math块里，因此不需要$$符号，辛苦xiaoxiao去掉。

下同

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +        $$Out = X / Y$$
同上

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +.. math::
344 和 345中间 请增加一个空行

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +        !!Out = (X || Y) &amp;&amp; !(X &amp;&amp; Y)!!
这里也不需要！！，辛苦去掉

下同

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +参数 **x** ：Sigmoid运算符的输入
863-865 每个参数前 请添加 “-”符号，作为项目号

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +参数 **x** ：Tanh运算符的输入
同 863-865

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +参数 **x** ：TanhShrink运算符的输入
同上，发现下面有同样的问题，请一致修改，不一一指出

2018-11-21 03:37 UTC, tink2123 commented on layers_cn.rst
> +        - **input** （Variable）：输入变量，格式为NCHW。
这里请去掉每个参数前的缩进，添加 - 符号

2018-11-23 03:28 UTC, tink2123 approved these changes
LGTM

2018-11-27 07:39 UTC, haowang101779990 approved these changes

2018-11-27 09:36 UTC, merged