Second translation by xx
PaddlePaddle/docs pull request #345
Opened 2018-11-15 15:50 UTC by ShangCambridge

2018-11-19 07:00 UTC, haowang101779990 requested changes
1. 参数粗体化时， \*\*argument\*\* 前后都必须有空格 
2. ``reduce_xxx`` 这几个同系列的函数参数说明是不一样的。我已经帮您改了一些，请您参照原文再看一遍
3. layers   line 289-302
4. pad_constant_like需要我们给他排个版orz，请您用github preview看看效果叭

辛苦啦~~~~~

2018-11-19 07:00 UTC, haowang101779990 commented on fluid_cn.rst
> +:::::::
```suggestion
>>>>>>>>>>>
```
麻烦将api标题如 https://github.com/PaddlePaddle/FluidDoc/pull/344 我comment那样该一下，以后的作品也麻烦标记如斯

2018-11-19 07:00 UTC, haowang101779990 commented on fluid_cn.rst
> +''''''''''''''''''''''''''''''''''''
```suggestion

```
https://github.com/PaddlePaddle/FluidDoc/pull/344

2018-11-19 07:00 UTC, haowang101779990 commented on fluid_cn.rst
> +    - **input（Variable）**: 作为索引序列的输入变量。
```suggestion
    - **input（Variable）** : 作为索引序列的输入变量。
```
后面那个**后面请确保有一个空格~~

2018-11-19 07:00 UTC, haowang101779990 commented on fluid_cn.rst
> +    - **win_size（int）**: 枚举所有子序列的窗口大小。
```suggestion
    - **win_size（int）** : 枚举所有子序列的窗口大小。
```

2018-11-19 07:00 UTC, haowang101779990 commented on fluid_cn.rst
> +    - **win_size（int）**: 枚举所有子序列的窗口大小。
下同

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **input**（Variable）：输入变量为Tensor或LoDTensor。
```suggestion
          - **input** （Variable）：输入变量为Tensor或LoDTensor。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **input**（Variable）：输入变量为Tensor或LoDTensor。
下同，麻烦您更改一下

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **dim**（list | int | None）：求和运算的维度。如果为None，则对输入的所有元素求和并返回单个元素的Tensor变量，否则必须在[−rank(input),rank(input)]范围内。如果dim [i] <0，则维度将减小为rank+dim[i]。
```suggestion
          - **dim** （list | int | None）：需要进行求和运算的维度。如果为None，则对输入的所有元素求和并返回具有单个元素的Tensor变量，否则该参数必须在 :math:`[−rank(input),rank(input)]` 范围内。如果 :math:`dim [i] <0` ，则减去的维度为 :math:`rank+dim[i]` 。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **keep_dim**（bool | False）：是否在输出Tensor中保留减小的维度。除非keep_dim为true，否则结果张量将比输入少一个维度。
```suggestion
          - **keep_dim** （bool | False）：是否在输出Tensor中保留减小的维度。除非 
``keep_dim`` 为true，否则结果张量将比输入少一个维度。
```

我这个review里面换行有些问题，这里只需要注意 
1. 参数第二个**后面和括号间有个空格，要不然官网无法正常渲染。（中文括号看起来像有一个空格一样，比较坑orz，可在github preview上正常看到粗体效果就ok了~~~
2. keep_dim是引用的api中的东西，建议使用[空格] \`\`api_part\`\`[空格]样式，在官网上就是代码高亮，在github preview上是灰色底的文字就ok了

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # x is a Tensor variable with following elements:
```suggestion
      # x 是具有如下元素的tensor：
```
请翻译出注释哈
我接下来帮您先翻了，随您取舍

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # Each example is followed by the corresponding output tensor.
接下来的示例中，我们在每处函数调用后面都标注出了它的结果张量。

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # x is a Tensor variable with shape [2, 2, 2] and elements as below:
```suggestion
      # x是一个形为[2, 2, 2]的Tensor变量，其内部元素如下所示:
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # Each example is followed by the corresponding output tensor.
接下来的示例中，我们在每处函数调用后面都标注出了它的结果张量。

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **dim**（list | int | None）：函数运算的维度。如果为None，则对输入的所有元素求和并返回单个元素的Tensor变量，否则必须在[−rank(input),rank(input)]范围内。如果dim [i] <0，则维度将减小为rank+dim[i]。
```suggestion
          - **dim**（list | int | None）：需要进行此函数运算的维度。如果为None，则将输入 ``input`` 的所有元素相乘， 并返回具有单个元素的Tensor变量，否则必须在 :math:`[−rank(input),rank(input)]` 范围内。如果 :math:`dim [i] <0` ，则将被减去的维度为 :math:`rank+dim[i]`  。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # x is a Tensor variable with following elements:
如上，请翻译注释

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +.. py:class:: paddle.fluid.layers.reduce_prod(input, dim=None, keep_dim=False, name=None)
```suggestion
.. py:class:: paddle.fluid.layers.reduce_min(input, dim=None, keep_dim=False, name=None)
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **input**（Variable）：输入变量为Tensor或LoDTensor。
```suggestion
          - **input** （Variable）：输入变量为Tensor或LoDTensor。
```
下同

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # x is a Tensor variable with following elements:
请翻译注释

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +      # x is a Tensor variable with following elements:
请翻译注释

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **dim**（list | int | None）：函数运算的维度。如果为None，则对输入的所有元素求和并返回单个元素的Tensor变量，否则必须在[−rank(input),rank(input)]范围内。如果dim [i] <0，则维度将减小为rank+dim[i]。
使用math元素
```suggestion
          - **dim** （list | int | None）：需要进行该函数运算的维度。如果为None，则计算输入 ``input`` 的所有元素的平均值，并返回具有单个元素的Tensor变量，否则必须在 
 :math:`[−rank(input),rank(input)]` 范围内。如果 :math:`dim [i] <0` ，则维度将减小为 :math:`rank+dim[i]` 。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **dim**（list | int | None）：函数运算的维度。如果为None，则对输入的所有元素求和并返回单个元素的Tensor变量，否则必须在[−rank(input),rank(input)]范围内。如果dim [i] <0，则维度将减小为rank+dim[i]。
如reduce sum中，使用math元素标注处公式
```suggestion
          - **dim** （list | int | None）：需要进行此函数运算的维度。如果为None，则对找出 ``input`` 张量所有元素的最小值，并返回单个元素的Tensor变量，否则必须在
 :math:`[−rank(input),rank(input)]` 范围内。如果 :math:`dim [i] <0` ，则将被减去的维度为 :math:`rank+dim[i]` 。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **keep_dim**（bool | False）：是否在输出Tensor中保留减小的维度。除非keep_dim为true，否则结果张量将比输入少一个维度。
```suggestion
          - **keep_dim** （bool | False）：是否在输出Tensor中保留减小的维度。除非 ``keep_dim`` 为true，否则结果张量将比输入少一个维度。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +返回：  减少的Tensor变量。
```suggestion
返回：  运算、减少维度之后的Tensor变量。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +返回：  减少的Tensor变量。
```suggestion
返回：  运算、减少维度之后的Tensor变量。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +计算给定维度上张量（Tensor）元素乘积。
计算给定维度上张量元素的最小值

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **dim**（list | int | None）：函数运算的维度。如果为None，则对输入的所有元素求和并返回单个元素的Tensor变量，否则必须在[−rank(input),rank(input)]范围内。如果dim [i] <0，则维度将减小为rank+dim[i]。
请按照上面几个reduce xxx的方式来更改。请对照原文，不是所有的都是“对所有元素求和”

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +          - **param_attr**(ParamAttr|None)：可学习权重 :math:`\[\alpha\]`参数属性。
```suggestion
          - **param_attr** (ParamAttr|None)：可学习权重 :math:`\[\alpha\]` 的参数属性。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +    $$y = max(0, x) + alpha min(0, x)$$
```suggestion
    \\y = max(0, x) + \alpha min(0, x)\\
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +返回： 输出Tensor与输入shape相同。
```suggestion
返回： 输出Tensor与输入 ``x`` shape相同。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +使用pad_value填充输入（Y），填充到每个axis边缘值的数量由X和Y的shape不同而指定。（（0，shape_x_0 - shape_y_0），...（0，shape_x_n - shape_y_n ））是每个axis唯一pad宽度。输入应该是k-D张量（k> 0且k <7）。
```suggestion
使用 ``pad_value`` 填充输入（Y），填充到每个axis边缘值的数量由X和Y的shape之差而定。（（0，shape_x_0 - shape_y_0），...（0，shape_x_n - shape_y_n ））是每个axis唯一pad宽度。输入应该是k-D（k维）张量（k> 0且k <7）。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +返回：填充张量（Tensor）变量。。
```suggestion
返回：填充后的张量（Tensor）变量。
```

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +
原文那里需要我们给重排一下版orz  review这里不好排版，您借助github preview来做吧。再次pr后我会上官网看看效果在商议。

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +
请翻译注释

2018-11-19 07:00 UTC, haowang101779990 commented on layers_cn.rst
> +
line 289-302 是重复编辑了吗？

2018-11-19 07:00 UTC, haowang101779990 commented on nets_cn.rst
> +''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
```suggestion

```

2018-11-19 07:00 UTC, haowang101779990 commented on nets_cn.rst
> +:::::::::::::::::::::::
```suggestion
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

2018-11-19 07:00 UTC, haowang101779990 commented on nets_cn.rst
> +simple_img_conv_pool由一个Convolution2d和一个Pool2d组成。
```suggestion
``simple_img_conv_pool`` 由一个Convolution2d和一个Pool2d组成。
```

2018-11-19 07:00 UTC, haowang101779990 commented on nets_cn.rst
> +    - **input**（Variable）:输入图像的格式为[N，C，H，W]。
```suggestion
    - **input** （Variable）:输入图像的格式为[N，C，H，W]。
```
下同

2018-11-20 06:54 UTC, haowang101779990 reviewed
数学公式，请使用示例中的\\来做。$官网识别不了orz

2018-11-20 06:54 UTC, haowang101779990 commented on layers_cn.rst
> +      # 接下来的示例中，我们在每处函数调用后面都标注出了它的结果张量。。
```suggestion
      # 接下来的示例中，我们在每处函数调用后面都标注出了它的结果张量。
```

2018-11-20 06:54 UTC, haowang101779990 commented on layers_cn.rst
> +    $$y = max(0, x) + alpha min(0, x)$$
比较令人伤心的是，经过试验。官网它识别不了$$符号，请使用\\\\吧，如同示例一样即可。辛苦啦

2018-12-05 10:55 UTC, shanyi15 commented
close via https://github.com/PaddlePaddle/FluidDoc/pull/422

2018-12-05 10:55 UTC, closed without merging