Dh 4 15
PaddlePaddle/docs pull request #348
Opened 2018-11-18 14:15 UTC by Mddct

15个翻译

2018-11-19 03:33 UTC, haowang101779990 requested changes
需要集中更改的问题如下：
1. 索引最后还有个: 麻烦统一改一下。此前的没问题。建议可以使用github preview当看到索引有下划线时基本上没问题\(≧▽≦)/
2. api的.. py:class::那个，如果原文中标示有class，请在译文中删除。详见comments
3. 请确保：参数粗体化时\*\*参数名\*\* 的前后都有空格。有时后面采用的中文括号（会看起来有个空格一样。

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +.. _cn_api_fluid_DataFeeder
```suggestion
.. _cn_api_fluid_DataFeeder:
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    ValueError - 如果某个变量不在该 Program 中。
```suggestion
    ``ValueError`` - 如果某个变量不在该 Program 中。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +根据 feed_list 和 iterable，将输入转换为 Executor 和 ParallelExecutor 所需的数据结构。
```suggestion
根据 feed_list 和 iterable，将输入转换为 ``Executor`` 和 ``ParallelExecutor`` 所需的数据结构。
```

引用的api名字，最好高亮一下以作提示和区分

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +如果想在多GPU 训练模型时预先单独将数据输入 GPU，可以使用 decorate_reader 函数。
```suggestion
如果想在多GPU 训练模型时预先单独将数据输入 GPU，可以使用 ``decorate_reader`` 函数。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +抛出异常：ValueError ，如果 drop_last 为 False 且 mini batch 不适合设备，则抛出 ValueError
```suggestion
抛出异常： ``ValueError`` - 如果 ``drop_last`` 为 False 且 mini batch 不适合设备，则抛出 
 ``ValueError``
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +.. _cn_api_fluid_DataFeeder
后面的好像都落下了，麻烦改一下叭

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +.. _cn_api_fluid_initializer_init_on_cpu
```suggestion
.. _cn_api_fluid_initializer_init_on_cpu:
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +强制变量在 cpu 上初始化
```suggestion
强制变量在 cpu 上初始化。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +.. _cn_api_fluid_initializer_ConstantInitializer
```suggestion
.. _cn_api_fluid_initializer_ConstantInitializer:
```
往后我就不comment出这一点啦，记得改一下~

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +.. py:class:: class paddle.fluid.DataFeeder(feed_list, place, program=None)
```suggestion
.. py:class::  paddle.fluid.DataFeeder(feed_list, place, program=None)
```
经过试验，麻烦要删除原文中带有的class，才能正常渲染orz

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +.. py:class:: class paddle.fluid.initializer.ConstantInitializer(value=0.0, force_cpu=False)
```suggestion
.. py:class:: paddle.fluid.initializer.ConstantInitializer(value=0.0, force_cpu=False)
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +.. py:class:: class paddle.fluid.initializer.NormalInitializer(loc=0.0, scale=1.0, seed=0)
```suggestion
.. py:class:: paddle.fluid.initializer.NormalInitializer(loc=0.0, scale=1.0, seed=0)
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +.. py:class:: class paddle.fluid.initializer.TruncatedNormalInitializer(loc=0.0, scale=1.0, seed=0)
```suggestion
.. py:class:: paddle.fluid.initializer.TruncatedNormalInitializer(loc=0.0, scale=1.0, seed=0)
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +#
```suggestion
::

```

::
并在下面添加一空行

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    ] # feed_vars_name is a list of variables' name.
```suggestion
    ] # feed_vars_name 是一个由变量名组成的列表。
```
请翻译出来注释~~

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    - **program**（Program） - 需要使用数据的 Program，如果 Program 为 None，则使用 default_main_program（）。 默认 None。
神坑orz，中文的（看起来就像有一个空格一样orz，但是它并没有空格
```suggestion
    - **program** (Program) - 需要使用数据的 Program，如果 Program 为 None，则使用 default_main_program（）。 默认 None。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    - **program**（Program） - 需要使用数据的 Program，如果 Program 为 None，则使用 default_main_program（）。 默认 None。
要是 **something** 前后没有正确地空格，官网上渲染不出来

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    - **drop_last**（bool） - 设备数量，默认 None。
空格问题，同上
```suggestion
    - **drop_last** （bool） - 设备数量，默认 None。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    - **num_places**（int） - 设备数量。 默认：None。
空格问题
```suggestion
    - **num_places** （int） - 设备数量。 默认：None。
```

2018-11-19 03:33 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +.. _cn_api_fluid_layers_ssd_loss
```suggestion
.. _cn_api_fluid_layers_ssd_loss:
```

2018-11-20 03:25 UTC, tink2123 reviewed
COOL！！

2018-11-20 03:25 UTC, tink2123 commented on doc/fluid/api/initializer_cn.rst
> +Random TruncatedNormal（高斯）分布初始化器
截断的高斯分布初始化器
英文这里最好加上一个空格，看起来更清晰====》Random Truncated Normal

2018-11-20 03:25 UTC, tink2123 commented on doc/fluid/api/layers_cn.rst
> +PolygonBoxTransform 算子。
PolygonBoxTransform ===》Polygon Box Transform

2018-11-21 07:10 UTC, haowang101779990 reviewed
辛苦辣，肉眼目前格式没问题~cool~把小问题调整后放网站预览

2018-11-21 07:10 UTC, haowang101779990 commented on doc/fluid/api/data_feeder_cn.rst
> +    - **iterable**（list | tuple） - 输入数据。
```suggestion
    - **iterable** （list | tuple） - 输入数据。
```

2018-11-21 07:10 UTC, haowang101779990 commented on doc/fluid/api/initializer_cn.rst
> +Random TruncatedNormal（高斯）分布初始化器
```suggestion
Random Truncated Normal（高斯）分布初始化器
```

2018-11-21 07:10 UTC, haowang101779990 commented on doc/fluid/api/layers_cn.rst
> +抛出异常: ValueError 如果 mining_type 是' hard_example '，抛出 ValueError。现在只支持 mining type 的类型为 max_negative。
```suggestion
抛出异常:  ``ValueError`` -  如果 mining_type 是' hard_example '，抛出 ValueError。现在只支持 mining type 的类型为 max_negative。
```

2018-12-05 10:55 UTC, shanyi15 commented
close via https://github.com/PaddlePaddle/FluidDoc/pull/422

2018-12-05 10:55 UTC, closed without merging