Dh 5 15
PaddlePaddle/docs pull request #364
Opened 2018-11-21 06:30 UTC by Mddct

15个翻译

2018-11-22 13:22 UTC, haowang101779990 requested changes
公式比较多，一些难排版的已经敲出来贴了个链接您复制过来吧~辛苦啦，赛高~ (^o^)／

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> + - **min** (float) - 要修剪的最小值。如果用户没有设置，将被设置为框架 ``-max``
```suggestion
 - **min** (float) - 要修剪的最小值。如果用户没有设置，将被 ``framework`` 设置为 ``-max`` 
```
framework应该是一个类

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +将张量值的范围压缩到 [min, max]。
```suggestion
将梯度值(gradient values)的范围压缩到 [min, max]。
```
这里我也觉得按照原文直译是否有些前言不搭后语。。。待商议

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +给定一个张量 ``t`` ，该操作将它的值压缩到 ``min`` 和 `max` 之间
```suggestion
给定一个张量 ``t`` ，该操作将它的值压缩到 ``min`` 和 ``max`` 之间
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> + - **min** (float，optional) - 要修剪的最小值。如果用户没有设置，将被设置为框架-max。
```suggestion
 - **min** (float，optional) - 要修剪的最小值。如果用户没有设置，将被 ``framework`` 设置为 ``-max`` 。
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +     initializer=UniformInitializer(low=-1.0, high=1.0, seed=0),
示例代码缩进~

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +该operator 限制了 输入张量 ``X``的L2范数不会超过 max_norm 。如果 ``X`` 的 ``L2`` 范数小于或等于 ``max_norm`` ,输出和 ``X`` 一样，如果 ``X`` 的L2范数大于 ``max_norm`` , ``X`` 将被线性缩放到L2范数等于 ``max_norm`` ,如以下公式所示:
```suggestion
该operator 限制了 输入张量 :math:`X` 的L2范数不会超过 :math:`max_norm` 。如果 :math:`X` 的 ``L2`` 范数小于或等于 :math:`max_norm` ,输出和 :math:`X` 一样，如果 :math:`X` 的L2范数大于 :math:`max_norm` , :math:`X` 将被线性缩放到L2范数等于 :math:`max_norm` ,如以下公式所示:
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +其中 ``norm（X）`` 代表 ``X`` 的 L2 范数
```suggestion
其中 :math:`norm（X）` 代表 :math:`X` 的 L2 范数
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +    initializer=UniformInitializer(low=-1.0, high=1.0, seed=0),
indent

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +            \\t\_list[i]=t\_list[i]∗\frac{clip\_norm}{(global\_norm,clip\_norm)}\\
```suggestion
            \\t\_list[i]=t\_list[i]∗\frac{clip\_norm}{max(global\_norm,clip\_norm)}\\
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +            \\global\_norm=\sqrt{\sum_{i=0}^{n-1}(l2norm(t\_list[i]))^2}\\
```suggestion
.. math::
            \\global\_norm=\sqrt{\sum_{i=0}^{n-1}(l2norm(t\_list[i]))^2}\\
```

弄成两块公式吧~吧其中二字夹在两块中间即可

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +如果 clip_norm>global_norm，t_list中的张量保持不变，否则它们都会按照全局比率缩减。
```suggestion
如果 :math:`clip_norm>global_norm` ， :math:`t_list` 中的张量保持不变，否则它们都会按照全局比率缩减。
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/clip_cn.rst
> +给定一个张量t_list和一个剪切比率 clip_norm，返回一个被剪切的张量列表list_clip和t_list中所有张量的全局范数(global_norm)。
```suggestion
给定一个张量列表 :math:`t_list` 和一个剪切比率 ``clip_norm`` ，返回一个被剪切的张量列表list_clipped和 :math:`t_list` 中所有张量的全局范数(global_norm)。
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +            \\param_out=param-learning\_rate∗grad\\
```suggestion
            \\param\_out=param-learning\_rate*grad\\
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +
经试验，请把每一个公式单独作为一个 .. math::块，在首、尾部加上换行就可以啦~ 给您敲出来了, 查看raw复制即可
https://raw.githubusercontent.com/haowang101779990/test_Fluid/master/AdamaxOptimizer_math.rst

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +  - **beta2** (float) - 第2极端估计的指数衰减率。
```suggestion
  - **beta2** (float) - 第2阶段估计的指数衰减率。
```

小笔误

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +  - **epsilon** (float) -非常小的浮点值得，为了数值稳定性质
```suggestion
  - **epsilon** (float) -非常小的浮点值，为了数值的稳定性质
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +目前 ``AdamaxOptimizer`` 不支持  sparse gradient
```suggestion
.. note::
    目前 ``AdamaxOptimizer`` 不支持  sparse gradient
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +            \\param_out=param-learning\_rate∗grad\\
中文的星号不ok

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +我们参考Adam paper第7节中的Adamax优化: https://arxiv.org/abs/1412.6980 ， Adamax是基于无穷大范数的Adam算法的一个变种。
```suggestion
我们参考Adam论文第7节中的Adamax优化: https://arxiv.org/abs/1412.6980 ， Adamax是基于无穷大范数的Adam算法的一个变种。
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +
```suggestion
```
笔误，删掉空行吧

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +
数学公式帮您打出来啦，打开链接复制即可~
https://raw.githubusercontent.com/haowang101779990/test_Fluid/master/DecayedAdagradOptimizer-math.rst

注意在复制的内容 即第一个 .. math::上面加一个空行，在最后再加一个空行

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +  - **epsilon** (float) - 非常小的浮点值得，为了数值稳定性
```suggestion
  - **epsilon** (float) - 非常小的浮点值，为了数值稳定性
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +``DecayedAdagradOptimizer`` 不支持 sparse gradient
```suggestion
.. note::
  ``DecayedAdagradOptimizer`` 不支持 sparse gradient
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +  - **ValueError**  如果 ``learning_rate`` , ``rho``,  ``epsilon`` , ``momentum``  为 None.
```suggestion
  - ``ValueError``  如果 ``learning_rate`` , ``rho`` ,  ``epsilon`` , ``momentum``  为 None.
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +.. math::
https://raw.githubusercontent.com/haowang101779990/test_Fluid/master/FtrlOptimizer.rst
公式排版比较奇幻，已经帮您排版好啦，替换成链接里的就ok~
这几个公式比较多，辛苦您啦~~~

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +在滑动窗口中累积参数的平均值。平均结果将保存在临时变量中，通过调用‘apply()’方法可应用于当前模型的参数变量。使用‘restore()’方法恢复当前模型的参数值
```suggestion
在滑动窗口中累积参数的平均值。平均结果将保存在临时变量中，通过调用 ``apply()`` 方法可应用于当前模型的参数变量。使用 ``restore()`` 方法恢复当前模型的参数值。

平均窗口的大小由 ``average_window_rate`` ， ``min_average_window`` ， ``max_average_window`` 以及当前更新次数决定。
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +在滑动窗口中累积参数的平均值。平均结果将保存在临时变量中，通过调用‘apply()’方法可应用于当前模型的参数变量。使用‘restore()’方法恢复当前模型的参数值
少翻译了一段，帮您翻出来了，自行取舍

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/param_attr_cn.rst
> +  - **learning_rate**  (float) – 参数的学习率. 优化的参数学习率为  global_lr∗parameter_lr∗scheduler_factor. Default 1.0
```suggestion
  - **learning_rate**  (float) – 参数的学习率. 优化的参数学习率为 :math:`global_lr∗parameter_lr∗scheduler_factor` . Default 1.0
```

2018-11-22 13:22 UTC, haowang101779990 commented on doc/fluid/api/profiler_cn.rst
> +不能使用 fluid.profiler.profiler``
```suggestion
不能使用 ``fluid.profiler.profiler`` 
```

2018-11-23 06:29 UTC, Mddct commented on doc/fluid/api/optimizer_cn.rst
> +.. math::
非常感谢 辛苦了

2018-11-23 07:08 UTC, luotao1 commented
http://172.19.57.47:8100/documentation/docs/zh/develop/advanced_usage/development/contribute_to_paddle/submit_pr_guide.html#permalink-7--
请注意commit的数量：
原因：如果仅仅修改一个文件但提交了十几个commit，每个commit只做了少量的修改，这会给评审人带来很大困扰。评审人需要逐一查看每个commit才能知道做了哪些修改，且不排除commit之间的修改存在相互覆盖的情况。

建议：每次提交时，保持尽量少的commit，可以通过git commit --amend补充上次的commit。对已经Push到远程仓库的多个commit，可以参考squash commits after push。

2018-11-23 10:17 UTC, haowang101779990 requested changes
还有一个数学公式
超链接引用的方式经过试验，已给您改为正确格式
如luotao老师所说此次在新的工作分支与本pr分支merge时，请选择squash的方式来减少commit的数量，或者git方式

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +原始论文： `http://www.jmlr.org/papers/volume12/duchi11a/duchi11a.pdf <http://www.jmlr.org/papers/volume12/duchi11a/duchi11a.pdf>`_
```suggestion
原始论文： http://www.jmlr.org/papers/volume12/duchi11a/duchi11a.pdf 
```

显式链接就显示写就行，经过试验，标准rst里面的这个格式官网不支持orz，此次提交请按luotao老师说的那样merge的时候squash一下~

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/param_attr_cn.rst
> +权重归一化。权范数是神经网络中权向量的再参数化，它将权向量的长度与其方向解耦。该paper对权值归一化的实现进行了讨论： `Weight Normalization: A Simple Reparameterization to Accelerate Training of Deep Neural Networks <https://arxiv.org/pdf/1602.07868.pdf>`_
```suggestion
权重归一化。权范数是神经网络中权向量的再参数化，它将权向量的长度与其方向解耦。该paper对权值归一化的实现进行了讨论：  `A Simple Reparameterization to Accelerate Training of Deep Neural Networks`_

 .. _A Simple Reparameterization to Accelerate Training of Deep Neural Networks: https://arxiv.org/pdf/1602.07868.pdf 
```

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/param_attr_cn.rst
> +权重归一化。权范数是神经网络中权向量的再参数化，它将权向量的长度与其方向解耦。该paper对权值归一化的实现进行了讨论： `Weight Normalization: A Simple Reparameterization to Accelerate Training of Deep Neural Networks <https://arxiv.org/pdf/1602.07868.pdf>`_
最后此次更改工作分支记得与pr分支merge的时候选择squash来减少commit数量

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/profiler_cn.rst
> +CUDA分析器。通过CUDA运行时应用程序编程接口对CUDA程序进行性能分析。分析结果将以键-值对格式或逗号分隔的格式写入output_file。用户可以通过output_mode参数设置输出模式，并通过配置参数设置计数器/选项。默认配置是[' gpustarttimestamp '， ' gpustarttimestamp '， ' gridsize3d '， ' threadblocksiz
```suggestion
CUDA分析器。通过CUDA运行时应用程序编程接口对CUDA程序进行性能分析。分析结果将以键-值对格式或逗号分隔的格式写入output_file。用户可以通过output_mode参数设置输出模式，并通过配置参数设置计数器/选项。默认配置是[' gpustarttimestamp '， ' gpustarttimestamp '， ' gridsize3d '， ' threadblocksize '， ' streamid '， ' enableonstart 0 '， ' conckerneltrace ']。然后，用户可使用 `NVIDIA Visual Profiler`_ 工具来加载这个输出文件以可视化结果。

.. _NVIDIA Visual Profiler: https://developer.nvidia.com/nvidia-visualprofiler
```

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/profiler_cn.rst
> +如果 state== ' All '，在profile_path 中写入文件 profile proto 。该文件记录执行期间的时间顺序信息。然后用户可以看到这个文件的时间轴，请参考 `https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/optimization/timeline.md <https://gith
```suggestion
如果 state== ' All '，在profile_path 中写入文件 profile proto 。该文件记录执行期间的时间顺序信息。然后用户可以看到这个文件的时间轴，请参考 
 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/optimization/timeline.md 
```

2018-11-23 10:17 UTC, haowang101779990 commented on doc/fluid/api/profiler_cn.rst
> +如果 state== ' All '，在profile_path 中写入文件 profile proto 。该文件记录执行期间的时间顺序信息。然后用户可以看到这个文件的时间轴，请参考 `https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/optimization/timeline.md <https://gith
```suggestion
如果 state== ' All '，在profile_path 中写入文件 profile proto 。该文件记录执行期间的时间顺序信息。然后用户可以看到这个文件的时间轴，请参考 
 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/optimization/timeline.md 
```

2018-11-23 10:27 UTC, haowang101779990 commented on doc/fluid/api/optimizer_cn.rst
> +
还有一个公式

2018-12-05 10:54 UTC, shanyi15 commented
close via https://github.com/PaddlePaddle/FluidDoc/pull/422

2018-12-05 10:54 UTC, closed without merging