增加ipu_shard和IpuCompiler的中文文档
PaddlePaddle/docs pull request #4118
Opened 2021-11-23 03:47 UTC by jianghaicheng

增加ipu_shard和IpuCompiler的中文文档

2021-11-26 13:29 UTC, zhao-han commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +.. py:class:: paddle.static.IpuCompiler(program, scope=None, ipu_strategy=None)
感觉缺少ipu_strategy对应的文档描述。

2021-11-26 13:29 UTC, zhao-han commented on docs/api/paddle/fluid/ipu_shard_cn.rst
> +    - **ipu_stage** (int, optional) – 指定被切分的模型的计算顺序，从0开始编号，（如‘0、1、2、3’），默认值None。按照数值大小对被切分的模型进行先后计算。
感觉ipu_index和ipu_stage这两个概念，会让客户难以理解。希望能有个更好的定义。

2021-11-26 13:29 UTC, zhao-han commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +该接口用于将初始化的Program进行转换，以便在ipu上运行该模型。用户可以通过 `feed_list` 、`fetch_list` 传入对计算图输入和输出描述的名称。
该接口对Program进行编译，以便在ipu上运行该模型。

2021-11-26 13:29 UTC, zhao-han commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +Program，转化之后的 ``Program`` 对象
编译之后的``Program`` 对象

2021-12-13 03:10 UTC, jianghaicheng commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +Program，转化之后的 ``Program`` 对象
OK

2021-12-13 03:11 UTC, jianghaicheng commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +该接口用于将初始化的Program进行转换，以便在ipu上运行该模型。用户可以通过 `feed_list` 、`fetch_list` 传入对计算图输入和输出描述的名称。
OK

2021-12-13 04:56 UTC, jianghaicheng commented on docs/api/paddle/static/IpuCompiler_cn.rst
> +.. py:class:: paddle.static.IpuCompiler(program, scope=None, ipu_strategy=None)
增加了ipu_strategy 的文档描述。

2021-12-14 11:51 UTC, qili93 requested changes

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +.. _cn_api_fluid_IPUCompiledProgram:
这里的API路径不对，得是 paddle.static.IPUCompiledProgram

https://github.com/PaddlePaddle/docs/blob/develop/docs/api/paddle/static/CompiledProgram_cn.rst

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +
错别字 sclae => scale，参阅改成 ` paddle.static.BuildStrategy`

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +    - **ipu_strategy** (IpuStrategy): 通过配置ipu_strategy，对计算图进行转换和优化，例如：计算图的float16模式、是否是训练模式、计算图需要用几个IPU等。默认为None。
添加，关于ipu_strategy更多信息，请参阅 ``paddle.static.IPUStrategy``

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +该接口用于将Program进行编译，以便在ipu上运行该。用户可以通过 `feed_list` 、`fetch_list` 传入计算图输入和输出的描述。
27/28行之间插入空行，“运行该”后面是？语句不完整。“的描述”可以去掉。

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +Program，编译之后的 ``Program`` 对象
这里是返回IPUCompiledProgram对象？

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUCompiledProgram_cn.rst
> +COPY-FROM: paddle.static.IPUCompiledProgram
这里应该是COPY-FROM: paddle.static.IPUCompiledProgram.compile ?

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/static/IPUStrategy_cn.rst
> +:api_attr: 声明式编程模式（静态图)
同上api路径都改成paddle.static开头，下面代码也需要相应的修改

2021-12-14 11:51 UTC, qili93 commented on docs/api/paddle/fluid/ipu_shard_cn.rst
> +.. py:function:: paddle.fluid.ipu_shard(ipu_index=None, ipu_stage=None)
路径不对，静态图的都以paddle.static开头

2021-12-15 06:57 UTC, jianghaicheng commented
OK 都解完了

2021-12-16 06:30 UTC, qili93 commented
文档预览链接 http://10.136.157.23:8090/documentation/docs/zh/api/index_cn.html?reviewVersion=jenkins-doc-review-1807

截图如下：

![IPUStategy](https://user-images.githubusercontent.com/16605440/146319676-09ac11a8-f96c-46f7-948f-2fedc980af28.png)


![image](https://user-images.githubusercontent.com/16605440/146319816-a22719d6-d83b-4629-b7f9-4082aba82b73.png)

![image](https://user-images.githubusercontent.com/16605440/146319837-8228e31f-9147-4d72-971e-db8c26c976de.png)

2021-12-29 08:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=4118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=4118) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jianghaicheng<br/>:x: yaozhixin<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/docs?pullRequest=4118) it.</sub>

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/fluid/ipu_shard_cn.rst
> +.. _cn_api_fluid_ipu_shard:
这个文件目录有误，请和API的公开路径一致，即 paddle/static/ipu_shard_cn.rst

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/fluid/ipu_shard_cn.rst
> +    - **ipu_index** (int, optional) - 指定Tensor在哪个ipu上计算，（如‘0、1’），默认值None。
ipu_index、ipu_stage的默认值为 None，表示 XXXX；这里需要把后半句写清楚；英文也同中文

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuCompiledProgram_cn.rst
> +IpuCompiledProgram根据 `ipu_config` 的配置将输入的Program转换和优化成ipu所需要的形式，例如：前向图提取、计算图转化、无用的scale算子删除等。关于ipu_config更多信息。请参阅  ``paddle.static.IpuConfig``。
这里可以用rst的相对引用，链接到  paddle.static.IpuConfig`，可以参考：https://github.com/PaddlePaddle/docs/wiki/%E9%A3%9E%E6%A1%A8%E6%96%87%E6%A1%A3%E7%9B%B8%E4%BA%92%E5%BC%95%E7%94%A8

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuCompiledProgram_cn.rst
> +    - **scope** (Scope): 该参数表示执行当前program所使用的作用域。如果没有指定scope，将使用全局scope，即paddle.static.global_scope()。
**scope** (Scope) -> **scope** (Scope，可选)
如果没有指定scope，将使用全局scope，即paddle.static.global_scope()。 ->
默认值为None，表示使用全局scope，即paddle.static.global_scope()。

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuCompiledProgram_cn.rst
> +    - **ipu_config** (IpuConfig): 通过配置ipu_config，对计算图进行转换和优化，例如：计算图的float16模式、是否是训练模式、计算图需要用几个IPU等。默认为None。
**ipu_config** (IpuConfig) -> **ipu_config** (IpuConfig，可选)
默认为None，表示XXX

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuConfig_cn.rst
> +:api_attr: 声明式编程模式（静态图)
这行不用写

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuConfig_cn.rst
> +``IpuConfig`` 使用户能更精准地控制 :ref:`cn_api_fluid_IpuCompiledProgram` 中计算图的建造方法，调用``IpuConfig``成员来获取对象。
调用``IpuConfig``成员来获取对象。 这句话不通顺吧

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuConfig_cn.rst
> +返回：IpuConfig实例。接收:ref:`cn_api_fluid_IpuGraphConfig`，:ref:`cn_api_fluid_IpuPipeliningConfig`，:ref:`cn_api_fluid_IpuHalfConfig`等接口传入的IPU构图配置信息，以及作为:ref:`cn_api_fluid_IpuCompiledProgram`的参数传递构图配置。
返回格式不对 应该是
返回
:::::::::
IpuConfig实例。xxx

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuGraphConfig_cn.rst
> +:api_attr: 声明式编程模式（静态图)
这行不用写

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuGraphConfig_cn.rst
> +    - **num_ipus** (int)- 指定IPU devices的个数，默认值为1。
**num_ipus** (int) -> **num_ipus** (int，可选)
有默认值的参数同理，不一一列举了

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuGraphConfig_cn.rst
> +    - **is_training** (bool)- 声明是训练还是推理，默认值为True。
默认值为True，表示为训练。

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuHalfConfig_cn.rst
> +:api_attr: 声明式编程模式（静态图)
这行不用写

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuHalfConfig_cn.rst
> +    - **enable_fp16** (bool)- 是否使能fp16运算。默认值为False。
默认值为False，表示 xxx

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuPipeliningConfig_cn.rst
> +:api_attr: 声明式编程模式（静态图)
这行不用写

2021-12-30 07:34 UTC, TCChenlong commented on docs/api/paddle/static/IpuPipeliningConfig_cn.rst
> +    - **num_ipus** (int)- 指定IPU devices的个数，默认值为1。
没有这个参数吧

2021-12-31 03:50 UTC, yaozhixin commented on docs/api/paddle/fluid/ipu_shard_cn.rst
> +.. _cn_api_fluid_ipu_shard:
resolved

2021-12-31 03:53 UTC, yaozhixin commented
@TCChenlong  hi, 您好，均已根据comments修改并对齐中英文版本，麻烦有空的话再帮忙review一下，十分感谢！

2022-01-04 06:31 UTC, TCChenlong commented on docs/api/paddle/static/IpuGraphConfig_cn.rst
> +.. py::function:: paddle.static.IpuGraphConfig
这里少了参数

2022-01-04 06:31 UTC, TCChenlong commented on docs/api/paddle/static/IpuHalfConfig_cn.rst
> +.. py::function:: paddle.static.IpuHalfConfig
少了参数

2022-01-04 06:31 UTC, TCChenlong commented on docs/api/paddle/static/IpuPipeliningConfig_cn.rst
> +.. py::function:: paddle.static.IpuPipeliningConfig
少了参数

2022-01-04 06:31 UTC, TCChenlong commented on docs/api/paddle/static/ipu_shard_cn.rst
> +note
注释的格式不对，可以参考：https://github.com/PaddlePaddle/docs/wiki/%E9%A3%9E%E6%A1%A8API%E6%96%87%E6%A1%A3%E4%B9%A6%E5%86%99%E8%A7%84%E8%8C%83#%E6%B3%A8%E8%A7%A3

2022-01-05 09:10 UTC, TCChenlong commented on docs/api/paddle/static/ipu_shard_cn.rst
> +.. note:
.. note: 与下文需要空一行，否则格式不对
![image](https://user-images.githubusercontent.com/11935832/148190952-437ca680-4680-4e6d-a57b-3c9af96dd101.png)

2022-01-05 09:10 UTC, TCChenlong commented on docs/api/paddle/static/ipu_shard_cn.rst
> +仅支持当enable_pipelining=True, ipu_stage才能被置为非None。请参阅 :ref:`cn_api_fluid_IpuPipliningConfig` 。
引用有个typo:
cn_api_fluid_IpuPipliningConfig -> cn_api_fluid_IpuPipeliningConfig

2022-01-05 09:10 UTC, TCChenlong commented on docs/api/paddle/static/IpuPipeliningConfig_cn.rst
> +通过``IpuPipeliningConfig`` 向IpuConfig实例中传递IPU构图的子图数据流水配置。
通过后面需要加一个空格

2022-01-05 09:10 UTC, TCChenlong commented on docs/api/paddle/static/IpuHalfConfig_cn.rst
> +通过``IpuHalfConfig`` 向IpuConfig实例中传递IPU构图的半精度运算配置。
通过后面需要加一个空格

2022-01-05 09:10 UTC, TCChenlong commented on docs/api/paddle/static/IpuGraphConfig_cn.rst
> +通过``IpuGraphConfig`` 向IpuConfig实例中传递IPU构图的Graph配置。
通过后面需要加一个空格
![image](https://user-images.githubusercontent.com/11935832/148191351-68ce0f7e-5475-4da6-a073-1258b6286133.png)

2022-01-19 10:24 UTC, qili93 approved these changes
LGTM

2022-01-21 06:39 UTC, TCChenlong approved these changes
LGTM

2022-01-21 06:49 UTC, merged