[IPU] add ipu intro doc
PaddlePaddle/docs pull request #4342
Opened 2022-03-24 10:02 UTC by gglin001

添加 IPU 的简要介绍，和安装指南

2022-03-25 08:09 UTC, wadefelix requested changes
![image](https://user-images.githubusercontent.com/1306724/160080417-042c2863-b747-44d6-a4ed-f17b00f8c2df.png)

2022-03-25 08:19 UTC, gglin001 commented
> ![image](https://user-images.githubusercontent.com/1306724/160080417-042c2863-b747-44d6-a4ed-f17b00f8c2df.png)

fixed!

2022-03-25 09:00 UTC, wadefelix commented on docs/guides/09_hardware_support/hardware_info_cn.md
> +| AI加速芯片 | IPU | Graphcore | GC200 | | [源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/ipu_docs/paddle_install_cn.html) |  | |
帮忙把此页里的这些链接都修改下
`[源码编译](/documentation/docs/guides/09_hardware_support/ipu_docs/index_cn.html)`

2022-03-25 09:18 UTC, gglin001 commented on docs/guides/09_hardware_support/hardware_info_cn.md
> +| AI加速芯片 | IPU | Graphcore | GC200 | | [源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/ipu_docs/paddle_install_cn.html) |  | |
fixed, 我只改了ipu 相关的这一条, 请问需要我来将其他设备的链接同时修改吗?

2022-03-25 09:19 UTC, wadefelix commented on docs/guides/09_hardware_support/hardware_info_cn.md
> +| AI加速芯片 | IPU | Graphcore | GC200 | | [源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/ipu_docs/paddle_install_cn.html) |  | |
不需要了，我们专门安排做一次清理

2022-03-25 09:26 UTC, gglin001 commented on docs/guides/09_hardware_support/hardware_info_cn.md
> +| AI加速芯片 | IPU | Graphcore | GC200 | | [源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/ipu_docs/paddle_install_cn.html) |  | |
ok

2022-03-25 13:48 UTC, qili93 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +- 通过源代码编译安装
第5行可以删掉？

2022-03-25 13:48 UTC, qili93 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +-it paddlepaddle/paddle:latest-dev-ipu bash
HOST_IPUOF_PATH 和 IPUOF_CONFIG_PATH 对用户而言有点难以理解，建议把文档最后面关于ipuof-configuration-file的链接提前一点放到这里

2022-03-25 13:48 UTC, qili93 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +```
这里其他硬件目前都支持通过 python -c "import paddle; paddle.utils.run_check()" 来进行检查，建议IPU也支持下

2022-03-25 13:48 UTC, qili93 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +`pwd`/build --config Release --target paddle_python -j$(nproc)
这里cmake命令建议参考 mkdir build && cd build 然后 cmake .. -DWITH_IPU=ON  ... 这样的格式

2022-03-25 14:50 UTC, gglin001 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +```
fixed;
但是目前是使用 CPUPlace 来跑模型测试， `run_check()` 对 IPUPlace 的支持将会在后续加入

2022-03-25 14:50 UTC, gglin001 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +-it paddlepaddle/paddle:latest-dev-ipu bash
fixed

2022-03-25 14:55 UTC, gglin001 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +-it paddlepaddle/paddle:latest-dev-ipu bash
这里确实容易让人困惑, 特别是当新用户需要自己去生成 ipuof 文件时, 我们暂时也没有更简单的方式去做这一说明.

2022-03-28 02:58 UTC, gglin001 commented
Docs-NEW  这个 CI 似乎对新的 push 无法正常触发

2022-03-29 02:29 UTC, qili93 approved these changes
LGTM

2022-03-29 03:06 UTC, Ligoml commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +# 您可以按照主机上的 ipuof 配置文件名称对下面的脚本进行修改，将 ipu.conf 改成相应的名称
主语不用“我们，您，用户，开发者”等，使用第二人称“你”

2022-03-29 03:06 UTC, Ligoml commented on docs/guides/09_hardware_support/index_cn.rst
> +- `Graphcore IPU芯片运行飞桨 <./ipu_docs/index_cn.html>`_ : 介绍如何在IPU环境上安装和使用飞桨。
<img width="950" alt="image" src="https://user-images.githubusercontent.com/39876205/160524628-87d301b1-23bb-49f8-86fb-f5afdca77561.png">
官网预览中没有正确显示目录结构，建议重新手动构建验证一下

2022-03-29 07:21 UTC, wadefelix commented on docs/guides/09_hardware_support/index_cn.rst
> +- `Graphcore IPU芯片运行飞桨 <./ipu_docs/index_cn.html>`_ : 介绍如何在IPU环境上安装和使用飞桨。
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/39876205/160524628-87d301b1-23bb-49f8-86fb-f5afdca77561.png">
> 
> 官网预览中没有正确显示目录结构，建议重新手动构建验证一下

@TCChenlong 可以直接在这里贴下帮助信息

2022-03-29 08:06 UTC, gglin001 commented on docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
> +# 您可以按照主机上的 ipuof 配置文件名称对下面的脚本进行修改，将 ipu.conf 改成相应的名称
fixed

2022-03-29 08:06 UTC, gglin001 commented on docs/guides/09_hardware_support/index_cn.rst
> +- `Graphcore IPU芯片运行飞桨 <./ipu_docs/index_cn.html>`_ : 介绍如何在IPU环境上安装和使用飞桨。
请问这里的目录结构是需要额外的配置吗？

2022-03-29 11:55 UTC, qili93 commented
手动生成的预览文件链接可以正确生成目录，链接如下：

	http://10.136.157.23:8090/documentation/docs/zh/faq/index_cn.html?reviewVersion=jenkins-doc-review-2163

2022-03-29 11:58 UTC, Ligoml approved these changes
LGTM

2022-03-29 11:58 UTC, merged