【Hackathon No.112】 PR.md
PaddlePaddle/docs pull request #4463
Opened 2022-04-03 14:02 UTC by ImNoBadBoy

【队名】：xd_no-bad

【序号】：112

【状态】：PR提交

2022-04-20 02:27 UTC, xymyeah requested changes

2022-04-20 02:27 UTC, xymyeah commented on docs/eval/【Hackathon No.112】 PR.md
> +Pytorch的分布式环境在曙光平台安装时需要手动编译torchversion，这一点上pytorch比较繁琐。但是pytorch的环境在曙光平台比较稳定，而paddle环境在曙光平台经常不稳定，有时候能运行，有时候不能运行。
『paddle环境在曙光平台经常不稳定，有时候能运行，有时候不能运行』为了后续paddle改善易用性，请补充详细点的不稳定的现象及问题描述

2022-04-20 03:37 UTC, ImNoBadBoy reviewed
已经添加了一些报错图片

2022-04-20 03:37 UTC, ImNoBadBoy commented on docs/eval/【Hackathon No.112】 PR.md
> +Pytorch的分布式环境在曙光平台安装时需要手动编译torchversion，这一点上pytorch比较繁琐。但是pytorch的环境在曙光平台比较稳定，而paddle环境在曙光平台经常不稳定，有时候能运行，有时候不能运行。
您好已经添加了一些报错图片，并把错误汇总到了最后一章节

2022-04-20 03:39 UTC, ImNoBadBoy commented
您好，已经对pr进行修改，添加了一些报错图片，已经添加了一些文字描述


https://github.com/PaddlePaddle/docs/pull/4463/files?short_path=a9cfb5f#diff-a9cfb5fe61e19af4915ff5149098a3f3558f8d055ed588969af5d6ee116a0a57


| |
缪孔苗
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/20/2022 ***@***.***> wrote：

@xymyeah requested changes on this pull request.

In docs/eval/【Hackathon No.112】 PR.md:

> +- 13、故需要提前下载whl文件，下载链接：
+```python
+https://www.paddlepaddle.org.cn/whl/rocm/stable.whl
+```  
+- 14、paddlepaddle_rocm-2.2.2-cp37-cp37m-linux_x86_64.whl，版本经过测试可以安装。安装指令:
+```python
+pip install paddlepaddle_rocm-2.2.2-cp37-cp37m-linux_x86_64.whl -i  https://pypi.tuna.tsinghua.edu.cn/simple/
+```  
+- 15、在安装完上述操作后还需要手动安装两个库opencv-python以及scipy
+```python
+pip install scipy -i https://pypi.tuna.tsinghua.edu.cn/simple/
+pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple/
+```  
+
+## （3）对比两者的易用性与区别
+Pytorch的分布式环境在曙光平台安装时需要手动编译torchversion，这一点上pytorch比较繁琐。但是pytorch的环境在曙光平台比较稳定，而paddle环境在曙光平台经常不稳定，有时候能运行，有时候不能运行。


『paddle环境在曙光平台经常不稳定，有时候能运行，有时候不能运行』为了后续paddle改善易用性，请补充详细点的不稳定的现象及问题描述

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-27 07:19 UTC, xymyeah requested changes

2022-04-27 07:19 UTC, xymyeah commented on docs/eval/【Hackathon No.112】 PR.md
> +另外，我们在曙光上使用paddle的方法为开启镜像的方式，但是曙光平台对docker镜像的支持不太好，每次镜像保持的时间最多为72小时，而且每次关闭镜像后，无法重新开启原先镜像。为了方便使用，希望能够支持 任务提交方式运行的paddle分布式框架。而且任务提交的方式还方便管理多节点运行。
https://zhuanlan.zhihu.com/p/366143771，可以按照这个教程用任务的方式来跑paddle任务，可以按照这种方式在跑一下paddle任务，后续会将相关文档会放到超算的用户手册上

2022-04-27 07:19 UTC, xymyeah commented on docs/eval/【Hackathon No.112】 PR.md
> +![image](https://user-images.githubusercontent.com/102226413/164143166-cde2793b-eb06-43a3-92d1-bfa68c2f1558.png)
第二个问题可以配置上
export NCCL_IB_HCA=mlx5_0
export NCCL_SOCKET_IFNAME=eno1
export NCCL_IB_DISABLE=0
试试，

或者用export NCCL_IB_DISABLE=1禁用相关配置

2022-04-27 07:19 UTC, xymyeah commented on docs/eval/【Hackathon No.112】 PR.md
> +![image](https://user-images.githubusercontent.com/102226413/164143166-cde2793b-eb06-43a3-92d1-bfa68c2f1558.png)
第二个问题可以配置上export NCCL_IB_HCA=mlx5_0试试，或者用export NCCL_IB_DISABLE=1禁用相关配置

2022-05-05 08:07 UTC, ImNoBadBoy commented on docs/eval/【Hackathon No.112】 PR.md
> +另外，我们在曙光上使用paddle的方法为开启镜像的方式，但是曙光平台对docker镜像的支持不太好，每次镜像保持的时间最多为72小时，而且每次关闭镜像后，无法重新开启原先镜像。为了方便使用，希望能够支持 任务提交方式运行的paddle分布式框架。而且任务提交的方式还方便管理多节点运行。
好的。
测试安装结果之前可以执行salloc指令，申请一个dcu，来进行安装测试。
![image](https://user-images.githubusercontent.com/102226413/166884375-b6fda498-486d-4b8c-93a8-a39a7d391d59.png)

申请一个节点
salloc -p kshdtest -N 1 -c 8 --gres=dcu:1
![image](https://user-images.githubusercontent.com/102226413/166884593-4862e6cf-f514-4810-a833-5fe483242acf.png)


登录节点
ssh j17r2n04


切换 rocm版本
module switch compiler/rocm/4.0.1


验证是否安装成功python -c "import paddle; paddle.utils.run_check()"
 
![image](https://user-images.githubusercontent.com/102226413/166884640-16ab4625-1981-4b86-8439-36d04d1216ac.png)

2022-05-05 08:09 UTC, ImNoBadBoy commented on docs/eval/【Hackathon No.112】 PR.md
> +![image](https://user-images.githubusercontent.com/102226413/164143166-cde2793b-eb06-43a3-92d1-bfa68c2f1558.png)
好的

2022-10-25 03:30 UTC, Ligoml approved these changes

2022-10-25 03:30 UTC, merged