【Hackathon No.27】为 Paddle 新增 frac 数学计算API
PaddlePaddle/docs pull request #4539
Opened 2022-04-08 10:32 UTC by Asthestarsfalll

add rst of paddle.frac

2022-04-12 02:50 UTC, dingjiaweiww approved these changes

2022-04-12 06:34 UTC, DDDivano requested changes

2022-04-12 06:34 UTC, DDDivano commented on docs/api/paddle/frac_cn.rst
> +     = paddle.rand([3,4],'float32')
[3,4] 怎么变成[3,3] 了

2022-04-12 08:28 UTC, Asthestarsfalll commented on docs/api/paddle/frac_cn.rst
> +     = paddle.rand([3,4],'float32')
抱歉，已修改

2022-04-12 12:19 UTC, luotao1 commented on docs/api/paddle/frac_cn.rst
> +代码示例
https://github.com/PaddlePaddle/docs/pull/4130/files
COPY-FROM: paddle.gcd
使用这种写法，保证中英文同步示例

2022-04-12 12:30 UTC, Asthestarsfalll commented on docs/api/paddle/frac_cn.rst
> +代码示例
已修改

2022-04-13 06:56 UTC, luotao1 commented on docs/api/paddle/Tensor_cn.rst
> +frac(name=None)
frac(x, name=None)

2022-04-13 07:12 UTC, Asthestarsfalll commented on docs/api/paddle/Tensor_cn.rst
> +frac(name=None)
对于Tensor.frac来说，并不需要显式地传入x

2022-04-14 11:01 UTC, DDDivano approved these changes

2022-04-14 12:01 UTC, merged