fix cn docs of paddle.vision.transforms.Normalize, paddle.vision.models.alexnet, paddle.vision.models.mobilenet, ops apis
PaddlePaddle/docs pull request #4704
Opened 2022-04-28 13:34 UTC by Liyulingyue

1. 添加参数
2. 使用copy-from

PADDLEPADDLE_PR=42380

https://github.com/PaddlePaddle/Paddle/pull/42380

2022-05-06 07:39 UTC, Ligoml commented on docs/api/paddle/vision/transforms/Normalize_cn.rst
> +    - keys (list[str]|tuple[str], 可选) – 与BaseTransform相同. 默认为None.
注意中英文标点符号不要混用

2022-05-18 09:10 UTC, Ligoml approved these changes

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/models/MobileNetV1_cn.rst
>  参数
num_classes：`,` --> `，`

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/models/MobileNetV2_cn.rst
>  参数
num_classes：`,` --> `，`

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/models/VGG_cn.rst
>  .. py:class:: paddle.vision.models.VGG(features, num_classes=1000)
需要把with_pool=True也加上

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/models/VGG_cn.rst
>  参数
- num_classes (int，可选) ，`int，` 后面多一个空格
- with_pool 后面多一个`:`

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/models/alexnet_cn.rst
>  参数
参数是不是少了 **kwargs

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/ops/PSRoIPool_cn.rst
spatial_scale是可选参数

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/ops/psroi_pool_cn.rst
中英文标点符号不要混用：
- `,` --> `，`
- `.` --> `。`
spatial_scale是可选参数

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/ops/roi_align_cn.rst
>      - name (str，可选）- 默认值为None。一般用户无需设置，具体用法请参见 :ref:`api_guide_Name`。
- 参数整体需要加粗
- 注意中英文标点符号不要混用
- 中英文字符之间最好空一格
- 注意参数是否可选

2022-05-18 09:10 UTC, Ligoml commented on docs/api/paddle/vision/transforms/Normalize_cn.rst
> +    - keys (list[str]|tuple[str]，可选) – 与BaseTransform相同。默认为None。
- 所有参数都需要加粗
- 注意参数是否可选，optional --> 可选
- 中英文字符之间最好加一个空格

2022-06-16 11:52 UTC, SigureMo requested changes

2022-06-16 11:52 UTC, SigureMo commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +  - **\*\*kwargs** (可选) - 附加的关键字参数，由调用者提供。
感觉是不是改成这样比较好，不然用户并不清楚到底可以提供哪些额外的参数（之前我就觉得这里没有提示用户可能会困惑）。

```suggestion
  - **\*\*kwargs** (可选) - 附加的关键字参数，具体可选参数请参见 :ref:`AlexNet <cn_api_paddle_vision_models_AlexNet>`。
```

英文里的 ref 应该是去掉 `cn_` 就好：

```
:ref:`AlexNet <api_paddle_vision_models_AlexNet>`
```

2022-06-16 11:53 UTC, SigureMo commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +  - **\*\*kwargs** (可选) - 附加的关键字参数，由调用者提供。
如果合适的话，在其余 [models 的 修复 PR](#4936) 我会应用统一这一更改

2022-06-17 03:05 UTC, Ligoml commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +  - **\*\*kwargs** (可选) - 附加的关键字参数，由调用者提供。
感觉这样蛮好的，请API的作者 @fuqianya 确认一下？

2022-06-17 05:22 UTC, fuqianya commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +  - **\*\*kwargs** (可选) - 附加的关键字参数，由调用者提供。
已确认，没啥问题~

2022-06-17 05:28 UTC, Ligoml commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +  - **\*\*kwargs** (可选) - 附加的关键字参数，由调用者提供。
> 如果合适的话，在其余 models 的 修复 PR（#4936）我会统一应用这一更改

非常欢迎呀~~

2022-06-17 05:50 UTC, merged