【Hackathon No.56 57 58 59】add doc of paddle.sparse.add subtract multiply divide
PaddlePaddle/docs pull request #4705
Opened 2022-04-28 13:39 UTC by gsq7474741

【Hackathon No.56 57 58 59】add docs for #41857

2022-04-29 11:17 UTC, TCChenlong commented on docs/api/paddle/sparse/sparse_multiply_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相乘，并将各个位置的输出元素保存到返回结果中。
相加算子 -> 相乘算子

2022-04-29 11:17 UTC, TCChenlong commented on docs/api/paddle/sparse/sparse_divide_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相除，并将各个位置的输出元素保存到返回结果中。
相除

2022-04-29 11:17 UTC, TCChenlong commented on docs/api/paddle/sparse/sparse_subtract_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相减，并将各个位置的输出元素保存到返回结果中。
相减

2022-04-29 13:00 UTC, gsq7474741 commented on docs/api/paddle/sparse/sparse_multiply_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相乘，并将各个位置的输出元素保存到返回结果中。
已修改

2022-04-29 13:00 UTC, gsq7474741 commented on docs/api/paddle/sparse/sparse_divide_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相除，并将各个位置的输出元素保存到返回结果中。
已修改

2022-04-29 13:00 UTC, gsq7474741 commented on docs/api/paddle/sparse/sparse_subtract_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相减，并将各个位置的输出元素保存到返回结果中。
已修改

2022-09-06 10:18 UTC, zhouwei25 reviewed
COPY-FROM: paddle.incubate.sparse.* 这里的示例代码都能成功对吧

2022-09-06 10:18 UTC, zhouwei25 commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +COPY-FROM: paddle.incubate.sparse.add
这里预览是可以成功的吗

2022-09-06 10:32 UTC, gsq7474741 commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +COPY-FROM: paddle.incubate.sparse.add
我看都这么写的，而且这个示例代码在ci的时候过了，是跑通了的

2022-09-06 14:54 UTC, SigureMo commented
预览见：http://preview-pr-4705.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/incubate/sparse/Overview_cn.html

2022-09-06 15:10 UTC, SigureMo requested changes
这些 API 文件名貌似不需要加 `sparse_` 前缀

<img width="220" alt="image" src="https://user-images.githubusercontent.com/38436475/188671046-9c717f87-5ec6-457b-bd54-8ac2272272da.png">

以及有一些代码风格检查没有过，需要在 docs 这个项目下同样注册 pre-commit 的 hooks

```python
pip install pre-commit==2.17.0  # 这个估计在 Paddle 那边已经安装过了
pre-commit install              # docs 目前为 API docs 引入了一些 hooks，因此这面也需要注册下
```

2022-09-06 15:10 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +逐元素相加算子，输入 ``x`` 与输入 ``y`` 逐元素相加，并将各个位置的输出元素保存到返回结果中。
在提及参数时，建议使用 :attr:\`x\` 和 :attr:\`y\`

2022-09-06 15:10 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +    - x (Tensor) - 输入的Tensor，数据类型为：float32、float64、int32、int64。
```suggestion
    - **x** (Tensor) - 输入的 Tensor，数据类型为 float32、float64、int32 或 int64。
```

- 参数名需要加粗
- 中英文间需要加空格，这个会提供一个自动化解决方案（上面提到的 pre-commit）
- 后面的`数据类型为`的格式是目前规范（discussing）中比较确定的一项内容，见：https://github.com/PaddlePaddle/docs/discussions/5243#discussioncomment-3526224

2022-09-06 15:10 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +    - name (str，可选） - 操作的名称(可选，默认值为None）。更多信息请参见 :ref:`api_guide_Name` 。
name 参数统一按照下面来写吧（格式可能需要稍微调整下）～

https://github.com/PaddlePaddle/docs/blob/924486dce1dc0989d2cc0c29c7c2fa23378613ad/docs/templates/common_docs.py#L42

2022-09-06 15:10 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +COPY-FROM: paddle.incubate.sparse.add
这个 `add` 是可以的，`is_same_shape` 还不确定，~~需要在 PR 描述里加上 `PADDLEPADDLE_PR=45086`~~（帮你加上了嘿嘿）之后重新触发 CI 再看看 http://preview-pr-4705.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/incubate/sparse/sparse_is_same_shape_cn.html

2022-09-06 15:10 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/Overview_cn.rst
> +    " :ref:`paddle.incubate.sparse.add` ", "逐元素加法"
没有渲染出链接：

<img width="527" alt="image" src="https://user-images.githubusercontent.com/38436475/188671194-4b6a828c-c03e-4eb9-bc79-29f80c283b84.png">

也许应该改成这样：

```suggestion
    " :ref:`paddle.incubate.sparse.add <cn_api_paddle_incubate_sparse_add>` ", "逐元素加法"
```

2022-09-06 18:11 UTC, gsq7474741 commented on docs/api/paddle/incubate/sparse/Overview_cn.rst
> +    " :ref:`paddle.incubate.sparse.add` ", "逐元素加法"
已更新 @SigureMo

2022-09-06 18:32 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/sparse_add_cn.rst
> +COPY-FROM: paddle.incubate.sparse.add
最新预览 `is_same_shape` 也是没问题的，见上面的链接

2022-09-06 18:57 UTC, SigureMo approved these changes
其他应该没啥问题了～

2022-09-06 18:57 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/add_cn.rst
> -逐元素相加算子，输入 :attr:`x` 与输入 :attr:`y` 逐元素相加，并将各个位置的输出元素保存到返回结果中。
一些格式上的和少许规范的内容我直接帮你改掉了 @gsq7474741 

这里是因为文档中要尽可能避免将「API」与「算子」进行混淆，最新的文档规范中的示例 paddle.add（不是 sparse 的这个）已经将「逐元素相加算子，」这一句删除了（于 #5244）

2022-09-06 18:57 UTC, SigureMo commented on docs/api/paddle/incubate/sparse/is_same_shape_cn.rst
> +返回两个 Tensor 形状比较的结果，判断输入 :attr:`x` 与输入 :attr:`y` 的形状是否相同，支持 DenseTensor、SparseCsrTensor 与 SparseCooTensor 之间任意两种的形状比较。
这里最好和英文是一致的，现在英文貌似少一些内容～

2022-09-07 09:17 UTC, gsq7474741 commented on docs/api/paddle/incubate/sparse/add_cn.rst
> -逐元素相加算子，输入 :attr:`x` 与输入 :attr:`y` 逐元素相加，并将各个位置的输出元素保存到返回结果中。
好的谢谢

2022-09-08 10:58 UTC, Ligoml approved these changes
good job！LGTM

2022-09-09 08:44 UTC, merged