[Dygraph] Add docs and tutorials of DataParallel
PaddlePaddle/docs pull request #4813
Opened 2022-05-19 08:26 UTC by haohongxiang

[Dygraph] Add docs and tutorials of DataParallel

2022-05-22 06:32 UTC, gongweibao requested changes

2022-05-22 06:32 UTC, gongweibao commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +数据并行使用手册
手册二字可以不用？

2022-05-22 06:32 UTC, gongweibao commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +.. image:: ./img/data_parallel.png
这个图的左半边代表什么含义？

2022-05-22 06:32 UTC, gongweibao commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +.. image:: ./img/data_parallel.png
右半边是否过于土了一点?

2022-05-22 06:32 UTC, gongweibao commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +.. code-block::
这个日志有什么有价值的信息？

2022-05-25 03:45 UTC, haohongxiang commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +数据并行使用手册
已删除

2022-05-25 03:46 UTC, haohongxiang commented on docs/guides/06_distributed_training/data_parallel_cn.rst
> +.. image:: ./img/data_parallel.png
已完善配图内容和风格

2022-05-26 05:05 UTC, gongweibao approved these changes
LGTM

2022-05-26 05:05 UTC, merged