修复paddle.amax、paddle.amin的参数问题
PaddlePaddle/docs pull request #4978
Opened 2022-07-01 02:59 UTC by ReganYue

中英文文档参数不一致。

2022-07-22 11:29 UTC, SigureMo commented
> paddle.static.save_inference_model中文文档需要修改，没有找到中文文档的文件。

全局搜索，屡试不爽(๑>؂<๑）

<img width="718" alt="image" src="https://user-images.githubusercontent.com/38436475/180428746-23458d01-fe46-49a9-9b63-a9605900c1dc.png">

> roi_perspective_transform没有在Web文档找到此API。但是有对应的文档文件碎片。

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/roi_perspective_transform_cn.html

是说这个嘛？貌似是个 fluid API 啊，fluid API 文档还需要修复嘛？

2022-07-22 11:40 UTC, SigureMo requested changes

2022-07-22 11:40 UTC, SigureMo commented on docs/api/paddle/fluid/nets/simple_img_conv_pool_cn.rst
> + Tensor, 输入input经过conv2d和pool2d之后输入的结果，数据类型与input相同
中文里应当用全角逗号（`，`）吧

上面也有一个

2022-07-23 01:51 UTC, ReganYue commented
> > paddle.static.save_inference_model中文文档需要修改，没有找到中文文档的文件。
> 
> 全局搜索，屡试不爽(๑>؂<๑）
> 
> <img alt="image" width="718" src="https://user-images.githubusercontent.com/38436475/180428746-23458d01-fe46-49a9-9b63-a9605900c1dc.png">
> 
> > roi_perspective_transform没有在Web文档找到此API。但是有对应的文档文件碎片。
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fluid/layers/roi_perspective_transform_cn.html
> 
> 是说这个嘛？貌似是个 fluid API 啊，fluid API 文档还需要修复嘛？

我也不知道，我是全局搜索，搜到这个API。

2022-07-23 01:51 UTC, ReganYue commented on docs/api/paddle/fluid/nets/simple_img_conv_pool_cn.rst
> + Tensor, 输入input经过conv2d和pool2d之后输入的结果，数据类型与input相同
收到，马上修改

2022-07-23 06:49 UTC, SigureMo requested changes
这些没有必要的空格可以删掉啦～

2022-07-23 06:49 UTC, SigureMo commented on docs/api/paddle/fluid/nets/simple_img_conv_pool_cn.rst
> + Tensor， 输入input经过conv2d和pool2d之后输入的结果，数据类型与input相同
```suggestion
Tensor，输入input经过conv2d和pool2d之后输入的结果，数据类型与input相同。
```

2022-07-23 06:49 UTC, SigureMo commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +Tensor，对于输入为LoDTensor的情况，返回CTC贪婪解码器的结果，即2-D LoDTensor，形状为[Lp，1]，数据类型为int64。 “ Lp”是所有输出序列长度的总和。如果结果中的所有序列均为空，则结果LoDTensor将为[-1]，其中LoD为[[]]。对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为
```suggestion
Tensor，对于输入为LoDTensor的情况，返回CTC贪婪解码器的结果，即2-D LoDTensor，形状为[Lp，1]，数据类型为int64。“Lp”是所有输出序列长度的总和。如果结果中的所有序列均为空，则结果LoDTensor将为[-1]，其中LoD为[[]]。对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
```

2022-07-24 14:25 UTC, ReganYue commented
中文文档fluid 的 API 恢复完毕

2022-07-26 08:00 UTC, momozi1996 commented on docs/api/paddle/amax_cn.rst
> +   - **axis** （int|list|tuple，可选）- 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
这里（int|list|tuple，可选） 注意加空格；
预览效果看起来是这样的：
![image](https://user-images.githubusercontent.com/79295425/180954763-e2ef7bcf-def1-497d-b6aa-f8cd62883fa2.png)

2022-07-26 08:05 UTC, momozi1996 commented on docs/api/paddle/amin_cn.rst
> +   - **axis** （int | list | tuple，可选）- 求最小值运算的维度。如果为None，则计算所有元素的最小值并返回包含单个元素的Tensor变量，否则必须在 :math:`[−x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] < 0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
文档预览是这样的
![image](https://user-images.githubusercontent.com/79295425/180955800-7f5e5218-6994-4163-8910-c86c3033cc8e.png)

2022-07-26 08:07 UTC, momozi1996 commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为LoDTensor的情况，返回CTC贪婪解码器的结果，即2-D LoDTensor，形状为[Lp，1]，数据类型为int64。“Lp”是所有输出序列长度的总和。如果结果中的所有序列均为空，则结果LoDTensor将为[-1]，其中LoD为[[]]。对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_s
能否分几个小段？目前挤在一起了，看起来不太美观。

![image](https://user-images.githubusercontent.com/79295425/180956306-4ca14c9f-9709-4ff7-8708-1e042a403c90.png)

2022-07-26 08:08 UTC, momozi1996 reviewed
注意一下问题，辛苦修改一下！ 谢谢！

2022-07-27 07:03 UTC, ReganYue commented
> 注意一下问题，辛苦修改一下！ 谢谢！

好的好的！

2022-07-27 07:32 UTC, ReganYue commented
PADDLEPADDLE_PR=4978

2022-07-27 07:49 UTC, SigureMo requested changes

2022-07-27 07:49 UTC, SigureMo commented on docs/api/paddle/amax_cn.rst
> +   - **axis** (int \| list \| tuple，可选) - 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
这个有必要转义吗？`|` 在 rst 中有什么特殊意义吗？应该只需要加空格就好吧？

2022-07-27 07:51 UTC, SigureMo commented
> PADDLEPADDLE_PR=4978

这个应该需要放在最上面 PR 描述里，这里的 comment 应该不起作用

ref: https://github.com/PaddlePaddle/docs/wiki/%5BBeta%5D%E9%A3%9E%E6%A1%A8%E6%96%87%E6%A1%A3%E9%A2%84%E8%A7%88%E5%B7%A5%E5%85%B7

2022-07-27 07:52 UTC, SigureMo commented on docs/api/paddle/amax_cn.rst
> +   - **axis** (int \| list \| tuple，可选) - 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
突然发现上一行少了个空格 [doge]

```diff
-    - **x** (Tensor)- Tensor，支持数据类型为float32，float64，int32，int64，维度不超过4维。
+    - **x** (Tensor) - Tensor，支持数据类型为float32，float64，int32，int64，维度不超过4维。
```

2022-07-27 07:53 UTC, ReganYue commented on docs/api/paddle/amax_cn.rst
> +   - **axis** (int \| list \| tuple，可选) - 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
> 这个有必要转义吗？`|` 在 rst 中有什么特殊意义吗？应该只需要加空格就好吧？

我在测试~~~

2022-07-27 07:55 UTC, ReganYue commented on docs/api/paddle/amax_cn.rst
> +   - **axis** (int \| list \| tuple，可选) - 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
> 突然发现上一行少了个空格 [doge]

收到  感谢感谢

2022-07-27 08:33 UTC, SigureMo requested changes

2022-07-27 08:33 UTC, SigureMo commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
对于 rst 来说，空一行才是换行。仅仅换行只是为了美观折断过长的行，这样并不会渲染成两个段落（`<p>`），只会在两行间加一个空格

```rst
这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落
这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落

这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落
```

最终会渲染为

```html
<p>这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落 这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落</p>

<p>这是一个段落这是一个段落这是一个段落这是一个段落这是一个段落</p>
```

2022-07-27 08:35 UTC, ReganYue commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
😁😁😁😁

2022-07-27 08:36 UTC, SigureMo commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
PS: 嫌麻烦咱可以直接把这个文件恢复了，毕竟是 fluid 下的 :joy:

2022-07-27 08:37 UTC, ReganYue commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
没事没事  感谢大佬指导我学习！

2022-07-29 07:42 UTC, Ligoml commented on docs/api/paddle/amax_cn.rst
> +   - **axis** (int | list | tuple，可选) - 求最大值运算的维度。如果为None，则计算所有元素的最大值并返回包含单个元素的Tensor变量，否则必须在 :math:`[-x.ndim, x.ndim]` 范围内。如果 :math:`axis[i] <0`，则维度将变为 :math:`x.ndim+axis[i]`，默认值为None。
(int|list|tuple，可选)
多余的空格删一下吧
另外数据类型之间用、隔开

2022-07-29 09:58 UTC, Ligoml commented on docs/api/paddle/fluid/layers/ctc_greedy_decoder_cn.rst
> +对于输入为Tensor的情况，返回一个元组，(output, output_length)，其中，output是一个形状为 [batch_size, N]，类型为int64的Tensor。output_length是一个形状为[batch_size, 1]，类型为int64的Tensor，表示Tensor输入下，每个输出序列的长度。
对，这个是fluid下的api，后面会逐步废弃

2022-07-29 10:00 UTC, Ligoml approved these changes
LGTM for amin、amax

2022-08-03 12:29 UTC, Ligoml approved these changes
good job! LGTM

2022-08-04 11:39 UTC, merged