fix docs bugs
PaddlePaddle/docs pull request #5030
Opened 2022-07-05 07:13 UTC by xiongjunfeng

1.IPUPlace的源代码 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/device/__init__.py#L81 显示这是一个function，而中文版API https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/IPUPlace_cn.html 却标注为class，认为应该以源代码为准，因此修改了 docs/api/paddle/device/IPUPlace_cn.rst

2.docs/api/paddle/fft/fft_cn.rst 中错误的将一个句号换行了，造成 中文版API https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/fft/fft_cn.html#canshu 页面上参数部分，参数axis的描述被作为参数n的后续描述了。因此修改该部分错误。

2022-07-05 07:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5030) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5030) before we can accept your contribution.<br/><hr/>**xiong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/docs?pullRequest=5030) it.</sub>

2022-08-03 09:14 UTC, Ligoml approved these changes
good job！ LGTM
另外 fft和fftn的示例代码可以做一些修改，使用paddle api替换掉np~

2022-08-03 09:15 UTC, Ligoml commented
cla还没有完成签署，完成后可以合入pr @xiongjunfeng

2022-08-03 10:25 UTC, SigureMo requested changes

2022-08-03 10:25 UTC, SigureMo commented on docs/api/paddle/fft/fft_cn.rst
>    值必须是 "forward"，"backward"，"ortho" 之一，默认值为 "backward"。三种缩放模式对应
<img width="901" alt="image" src="https://user-images.githubusercontent.com/38436475/182585648-2e19cbaf-5a37-45ab-a610-1727739a5db7.png">

这两处的换行也应一并删掉～

2023-02-02 08:09 UTC, Ligoml commented on docs/api/paddle/fft/fft_cn.rst
>    值必须是 "forward"，"backward"，"ortho" 之一，默认值为 "backward"。三种缩放模式对应
应该是被其他人改过了

2023-10-20 06:45 UTC, closed without merging