【PaddlePaddle Hackathon 3】5 新增 API bucketize
PaddlePaddle/docs pull request #5089
Opened 2022-07-27 08:08 UTC by Li-fAngyU

增加paddle.bucketize的中文文档。

该算子的实现PR为https://github.com/PaddlePaddle/Paddle/pull/44195

2022-07-29 09:39 UTC, sunzhongkai588 commented on docs/api/paddle/buckiteze_cn.rst
> +Tensor(与 ``x`` 维度相同)，如果参数 ``out_int32`` 为False，则返回数据类型为int32的Tensor，否则将返回int64的Tensor。
这部分和**out_int32**参数描述相悖。**out_int32** 为**False**时，返回数据类型应为**int64**？

2022-07-29 09:39 UTC, sunzhongkai588 commented on docs/api/paddle/Tensor_cn.rst
> +请参考 :ref:`cn_api_tensor_bucketize`
参考上下文API，仅需展示关键信息，详细信息跳转即可

2022-07-29 10:37 UTC, Li-fAngyU commented on docs/api/paddle/buckiteze_cn.rst
> +Tensor(与 ``x`` 维度相同)，如果参数 ``out_int32`` 为False，则返回数据类型为int32的Tensor，否则将返回int64的Tensor。
谢谢提醒，这里我是直接参考searchsort API的，然后我顺便修改了searchsort_cn.rst 文件里的描述。

2022-07-29 10:39 UTC, Li-fAngyU commented
Done

2022-07-29 10:48 UTC, SigureMo requested changes

2022-07-29 10:48 UTC, SigureMo commented on docs/api/api_label
> +paddle.bucketize .. _api_paddle_bucketize:
API name 和 API label 之间应该用 `\t` 隔开～

2022-07-29 10:48 UTC, SigureMo commented on docs/api/paddle/Tensor_cn.rst
> +bucketize(x, sorted_sequence, out_int32=False, right=False, name=None)
作为 Tensor 的方法出现时，应该不需要第一个参数 `x` 吧？

2022-07-29 10:48 UTC, SigureMo commented on docs/api/paddle/bucketize_cn.rst
> +    - **x** (Tensor) - 输入的N维Tensor，支持的数据类型：float32、float64、int32、int64。
数据类型顺序也要与英文一致呀～

```suggestion
    - **x** (Tensor) - 输入的N维Tensor，支持的数据类型：int32、int64、float32、float64。
```

下同～

2022-07-29 10:48 UTC, SigureMo commented on docs/api/paddle/bucketize_cn.rst
> +    - **right** (bool，可选) - 根据给定 ``x`` 在 ``sorted_sequence`` 查找对应的上边界或下边界。默认值为False，表示在 ``sorted_sequence`` 的查找给定 ``x`` 的下边界。
这个参数和英文描述不太一样呀～

2022-07-29 10:55 UTC, Li-fAngyU commented on docs/api/paddle/bucketize_cn.rst
> +    - **right** (bool，可选) - 根据给定 ``x`` 在 ``sorted_sequence`` 查找对应的上边界或下边界。默认值为False，表示在 ``sorted_sequence`` 的查找给定 ``x`` 的下边界。
这个参数描述是和[searchsorted] (https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/searchsorted_cn.html#searchsorted)一致的，是否需要修改到与英文描述一致呢？

2022-07-29 11:01 UTC, SigureMo commented on docs/api/paddle/bucketize_cn.rst
> +    - **right** (bool，可选) - 根据给定 ``x`` 在 ``sorted_sequence`` 查找对应的上边界或下边界。默认值为False，表示在 ``sorted_sequence`` 的查找给定 ``x`` 的下边界。
对于本 API 里的这个参数的话，英文里应该是 `x` 而不是 `values`，这个问题只在本 API 存在，应该是 copy 后忘记修改了～

然后这两个 API 有一个共性问题就是中文文档都没有翻译 `If the value of the sorted_sequence is nan or inf, return the size of the innermost dimension.`，个人认为应该都加上～

2022-07-29 11:02 UTC, Li-fAngyU commented on docs/api/paddle/bucketize_cn.rst
> +    - **right** (bool，可选) - 根据给定 ``x`` 在 ``sorted_sequence`` 查找对应的上边界或下边界。默认值为False，表示在 ``sorted_sequence`` 的查找给定 ``x`` 的下边界。
好的，感谢提醒！

2022-07-29 11:28 UTC, Li-fAngyU commented
Done

2022-08-03 07:14 UTC, Ligoml approved these changes
good job！@Li-fAngyU @SigureMo 
LGTM

2022-08-04 02:36 UTC, merged