1220 improve cnapi
PaddlePaddle/docs pull request #509
Opened 2018-12-20 07:55 UTC by haowang101779990

一些说明的优化

2018-12-20 08:37 UTC, fseasy requested changes

2018-12-20 08:37 UTC, memeda commented on doc/fluid/api_cn/layers_cn.rst
>  这个过程可以通过如下公式表现：
我认为这个公式没有说得特别清楚：
（1）如果X是一个tensor的list，那么应该明确X是tensor列表，X_i 是列表中一个tensor； 对应的 W是权值列表，W_i 是列表中的一个权值（就是这里很疑惑，现在公式里W_i 与 X_i 做矩阵乘法，但是下面说W又是权值，而不是权值列表）
（2）如果X是一个tensor，这种情况下的公式是怎样的呢？或者说，介绍里说“可以同时是tensor列表”，那是否可以不是“tensor列表”，如果不是，公式是怎样的呢，我觉得需要说清楚

2018-12-20 08:37 UTC, memeda commented on doc/fluid/api_cn/layers_cn.rst
> +	- **axis** (int) - 指出应该将哪些输入维度(唯一的) flatten 到输出的前一个维度。axis的值必须在[0,R]范围内，其中R是输入张量的秩。当 axis= 0 时，输出张量的形状为 (1，d_0 \* d_1 \*… d_n) ，其输入张量的形状为(d_0, d_1，… d_n)。
`指出应该将哪些输入维度(唯一的) flatten 到输出的前一个维度。`这个感觉不太清楚；
```suggestion
 	- **axis** (int) - flatten
 	flatten的划分轴，[0, axis) 轴数据被flatten
 	flatten到输出矩阵的0轴，[axis, R)被flatten
 	flatten到输出矩阵的1轴，其中R是输入张量的秩。axis的值必须在[0,R]范围内。当 axis= 0 时，输出张量的形状为 (1，d_0 \* d_1 \*… d_n) ，其输入张量的形状为(d_0, d_1，… d_n)。
```

2018-12-20 08:37 UTC, memeda commented on doc/fluid/api_cn/layers_cn.rst
> +返回: 一个二维张量，它包含输入张量的内容，输入维数将沿给定轴flatten到输出的前一个维度，剩余的输入维数flatten到输出的后一个维度。
```suggestion
 返回: 一个二维张量，它包含输入张量的内容，但维数发生变化。输入的[0, axis)维将沿给定轴flatten到输出的前一个维度，剩余的输入维数flatten到输出的后一个维度。
```

2018-12-20 08:37 UTC, memeda commented on doc/fluid/api_cn/layers_cn.rst
> +	- **inplace** (bool) - 如果在多个操作符中使用x，则 ``inplace`` 必须设置为False。如果该标志设置为True，则直接对输入x本身进行reshape操作，张量变量x的形状将会被改变，因此在其他操作中再使用x时会造成错误。如果为False，则保留输入变量x的原形状，并输出一个新的张量变量，该张量变量的数据是从输入x复制的，但是其形状已经经过reshape操作进
按上面的理解，似乎就是说：
inplace=True的reshape之后，这个变量本身的shape发生了变化，这个变化可能导致一些企图用原始的输入维度的操作错误；
我认为凡是懂inplace这个含义的，上面的意思应该都是不言自明的，但是doc的写法 “多个操作符中使用x”似乎让问题更加复杂，让人觉得是不是存在图计算过程中，一些时序的问题，具体来说：
actionA(T)
reshape(T, replace=True)
actionB(T)
如果inplace-reshape只影响actionB的操作，那么我觉得完全符合预期，不用写得复杂；如果会影响actionA的操作，那么这个问题就大了，就需要说明如何影响，该如何具体操作了

2019-03-12 07:27 UTC, shanyi15 commented
is https://github.com/PaddlePaddle/Paddle/pull/15681/ fix the English version? @haowang101779990

2019-03-12 08:58 UTC, haowang101779990 commented on doc/fluid/api_cn/layers_cn.rst
> +	- **inplace** (bool) - 如果在多个操作符中使用x，则 ``inplace`` 必须设置为False。如果该标志设置为True，则直接对输入x本身进行reshape操作，张量变量x的形状将会被改变，因此在其他操作中再使用x时会造成错误。如果为False，则保留输入变量x的原形状，并输出一个新的张量变量，该张量变量的数据是从输入x复制的，但是其形状已经经过reshape操作进
英文已经更新该参数的说明

2019-03-12 09:31 UTC, shanyi15 commented on doc/fluid/api_cn/layers_cn.rst
>  这个过程可以通过如下公式表现：
已加icafe需求

2019-03-12 09:46 UTC, shanyi15 approved these changes

2019-03-12 09:51 UTC, merged