【PaddlePaddle Hackathon 3】16 新增 API paddle.take
PaddlePaddle/docs pull request #5099
Opened 2022-07-30 04:12 UTC by S-HuaBomb

增加 `paddle.take` 的中文文档。

RFC 的链接为：[20220714_api_design_for_take.md](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220714_api_design_for_take.md)
该算子的实现 PR 链接为：https://github.com/PaddlePaddle/Paddle/pull/44741
PADDLEPADDLE_PR=44741

2022-08-05 08:07 UTC, Ligoml commented on docs/api/paddle/take_cn.rst
> +.. py:function:: paddle.take(input, index, name)
take(input, index, name=None)

2022-08-05 08:10 UTC, Ligoml commented on docs/api/paddle/take_cn.rst
> +- `Tensor` - 返回一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同。
<img width="625" alt="image" src="https://user-images.githubusercontent.com/39876205/183032630-551c5716-c6ba-4bfa-a394-0832fbf3c521.png">
Tensor和index为什么要使用斜体？

2022-08-05 08:54 UTC, S-HuaBomb commented on docs/api/paddle/take_cn.rst
> +.. py:function:: paddle.take(input, index, name)
Done

2022-08-05 08:55 UTC, S-HuaBomb commented on docs/api/paddle/take_cn.rst
> +- `Tensor` - 返回一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同。
已经改回正体，
Done

2022-08-05 16:18 UTC, SigureMo requested changes

2022-08-05 16:18 UTC, SigureMo commented on docs/api/paddle/Tensor_cn.rst
> +take(input, index, name=None)
作为 Tensor 的方法应该不需要第一个参数～

2022-08-05 16:18 UTC, SigureMo commented on docs/api/paddle/take_cn.rst
> +- Tensor - 返回一个新的 Tensor，其中包含给定索引处的输入元素。结果与 index 的形状相同。
这里已经是`返回`了，不需要再加返回啦～

```suggestion
Tensor，其中包含给定索引处的输入元素。与 index 的形状相同。
```

2022-08-05 16:18 UTC, SigureMo commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +.. _cn_api_paddle_vision_models_AlexNet:
注意不要把没有修改的文件提交了哦，这是 https://github.com/PaddlePaddle/Paddle/issues/44671 提到的问题，暂时还没办法解决，也确实容易误操作，不过暂时先自己注意一下吧～如果可以的话尽可能恢复下～（大小写不敏感文件系统可能不太好处理，如果不能直接恢复的话，可以试试比如 revert 的命令来恢复，实在不行的话只能重新提 PR 了）

2022-08-05 16:18 UTC, SigureMo commented on docs/api/paddle/Tensor_cn.rst
> +返回：一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同
这里还有一个用 ` 包裹的，也许我们应该用

```rst
:attr:`arg_name`
```

这样？目前 Paddle 文档中引用某一个参数经常会使用这个，比如 [argmax](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/argmax_cn.html) 源码和渲染分别为

<img width="911" alt="image" src="https://user-images.githubusercontent.com/38436475/183118111-67c469bc-6026-411e-aabb-9818d2d6b433.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/38436475/183118145-b7d58ded-104d-400d-8958-3644c1e059f1.png">

看起来虽然一样，但应该仅仅是 Paddle 前端没有为两者样式做区分，比如 sphinx-rtd-theme 两者区别就是比较明显的

<img width="720" alt="image" src="https://user-images.githubusercontent.com/38436475/183118903-6d31e2bb-7456-480d-9dae-7149799813f6.png">

@BrilliantYuKaimin 有什么建议嘛？

2022-08-07 03:12 UTC, BrilliantYuKaimin commented on docs/api/paddle/Tensor_cn.rst
> +返回：一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同
在 rst 中用一个 \` 包裹的表示斜体，用两个 \` 包裹的表示代码块。既然 :attr:\`arg_name\` 和 \`\`arg_name\`\` 确实可以渲染出不同的效果，那么当然应该使用 :attr:\`arg_name\`。

2022-08-07 05:56 UTC, S-HuaBomb commented on docs/api/paddle/Tensor_cn.rst
> +take(input, index, name=None)
Done

2022-08-07 05:58 UTC, S-HuaBomb commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +.. _cn_api_paddle_vision_models_AlexNet:
感谢建议。这个问题的确很令人困扰，可以按照你们的方案避免同名。
Done

2022-08-07 05:58 UTC, S-HuaBomb commented on docs/api/paddle/Tensor_cn.rst
> +返回：一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同
Thx，Done

2022-08-07 06:01 UTC, S-HuaBomb commented on docs/api/paddle/Tensor_cn.rst
> +返回：一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同
Thx，Done

2022-08-07 06:01 UTC, S-HuaBomb commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +.. _cn_api_paddle_vision_models_AlexNet:
Thx，Done

2022-08-07 20:34 UTC, SigureMo commented
<img width="805" alt="image" src="https://user-images.githubusercontent.com/38436475/183309895-c8a8336e-fd4f-4c10-a974-26fe4333c524.png">

看样子还有些代码风格检查没有过，需要本地安装 pre-commit（这个 repo 里也需要初始化下），之后相应的文件随便加点什么后 commit 以触发 pre-commit 的自动修复（最好是些没什么影响的，比如在某一行后加些空格，这些之后会在触发 pre-commit 后自动删除，如果没有自动删的话手动记得删一下 :joy:）

2022-08-08 01:24 UTC, S-HuaBomb commented
> 



> <img alt="image" width="805" src="https://user-images.githubusercontent.com/38436475/183309895-c8a8336e-fd4f-4c10-a974-26fe4333c524.png">
> 
> 看样子还有些代码风格检查没有过，需要本地安装 pre-commit（这个 repo 里也需要初始化下），之后相应的文件随便加点什么后 commit 以触发 pre-commit 的自动修复（最好是些没什么影响的，比如在某一行后加些空格，这些之后会在触发 pre-commit 后自动删除，如果没有自动删的话手动记得删一下 😂）

很奇怪，我修改 take_cn.rst 之后 commit 却没有触发 pre-commit，环境中已经安装了。不过 take_cn.rst 的问题应该是最后空了两行，我手动删了一行。
THX，done

2022-08-08 01:24 UTC, S-HuaBomb commented
> 



> <img alt="image" width="805" src="https://user-images.githubusercontent.com/38436475/183309895-c8a8336e-fd4f-4c10-a974-26fe4333c524.png">
> 
> 看样子还有些代码风格检查没有过，需要本地安装 pre-commit（这个 repo 里也需要初始化下），之后相应的文件随便加点什么后 commit 以触发 pre-commit 的自动修复（最好是些没什么影响的，比如在某一行后加些空格，这些之后会在触发 pre-commit 后自动删除，如果没有自动删的话手动记得删一下 😂）

很奇怪，我修改 take_cn.rst 之后 commit 却没有触发 pre-commit，环境中已经安装了。不过 take_cn.rst 的问题应该是最后空了两行，我手动删了一行。
THX，done

2022-08-08 06:45 UTC, Ligoml commented on docs/api/paddle/vision/models/alexnet_cn.rst
> +.. _cn_api_paddle_vision_models_AlexNet:
这个问题现在有团队在解决了，预期Q3完成~

2022-08-08 06:47 UTC, Ligoml commented
> > 
> 
> > <img alt="image" width="805" src="https://user-images.githubusercontent.com/38436475/183309895-c8a8336e-fd4f-4c10-a974-26fe4333c524.png">
> > 看样子还有些代码风格检查没有过，需要本地安装 pre-commit（这个 repo 里也需要初始化下），之后相应的文件随便加点什么后 commit 以触发 pre-commit 的自动修复（最好是些没什么影响的，比如在某一行后加些空格，这些之后会在触发 pre-commit 后自动删除，如果没有自动删的话手动记得删一下 😂）
> 
> 很奇怪，我修改 take_cn.rst 之后 commit 却没有触发 pre-commit，环境中已经安装了。不过 take_cn.rst 的问题应该是最后空了两行，我手动删了一行。 THX，done

因为这个格式检查的pr上周五合入的， @SigureMo 贡献的pr

2022-08-08 07:26 UTC, S-HuaBomb commented
> 

在新的仓库中使用 pre-commit 需要先运行 `pre-commit install`。

我用 pre-cpmmit 会有这个问题：
![image](https://user-images.githubusercontent.com/39048551/183362205-7ea228fb-bc0d-4fe4-92d8-3951ab5040f5.png)
它检查了之前提到的由于大小写出问题的文件，因为它们一直被标为修改文件在暂存区，restore 也没有用。我删除了空了两行的地方，这次应该好了。
Thx，done

2022-08-08 08:03 UTC, SigureMo commented
> 在新的仓库中使用 pre-commit 需要先运行 pre-commit install。

嗯嗯，首先全局用 `pip install pre-commit` 是全局安装这个工具

之后每个 repo 都需要 `pre-commit install` 将 git hooks 注册到具体的这一个 repo

> 我用 pre-commit 会有这个问题：

嗯对的，我本地也用不了 pre-commit，现在都是在 codespace 上修改文档开发的（那个 issue 里我也有说），就很麻烦……

2022-08-08 08:06 UTC, SigureMo commented on docs/api/paddle/Overview_cn.rst
> +    " :ref:`paddle.take <cn_api_tensor_take>` ", "输出给定索引处的输入元素，结果与 index 的形状相同"
<img width="923" alt="image" src="https://user-images.githubusercontent.com/38436475/183370161-13284232-2b0e-4ed1-b250-889e85a4d21a.png">

还有问题，这个是说在句尾多了一个空格

2022-08-08 08:55 UTC, S-HuaBomb commented on docs/api/paddle/Overview_cn.rst
> +    " :ref:`paddle.take <cn_api_tensor_take>` ", "输出给定索引处的输入元素，结果与 index 的形状相同"
Thx，done

2022-08-11 02:41 UTC, Ligoml commented on docs/api/paddle/Tensor_cn.rst
> +返回：一个新的 Tensor，其中包含给定索引处的输入元素。结果与 `index` 的形状相同
「仅仅是 Paddle 前端没有为两者样式做区分」
给前端加一个需求吧

2022-08-23 12:40 UTC, SigureMo requested changes

2022-08-23 12:40 UTC, SigureMo commented on docs/api/paddle/take_cn.rst
> +    - ``clip``：将超出范围的索引剪裁到允许的最小（大）范围；
嵌套列表需要上下各空一行。可参考 [reStructuredText Primer（Lists and Quote-like blocks）](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks)

英文这里保持一致格式吧，也用列表的形式，不过可能也需要注意添加空行

2022-08-24 07:27 UTC, S-HuaBomb commented on docs/api/paddle/take_cn.rst
> +    - ``clip``：将超出范围的索引剪裁到允许的最小（大）范围；
Thx，done

2022-08-25 09:23 UTC, Ligoml approved these changes
good job！LGTM

2022-08-30 07:45 UTC, merged