【PaddlePaddle Hackathon 3 No.17】为 Paddle 新增 sgn 文档
PaddlePaddle/docs pull request #5107
Opened 2022-08-04 15:46 UTC by peachlcy

add docs of paddle.sgn
PADDLEPADDLE_PR=44568
- https://github.com/PaddlePaddle/Paddle/pull/44568

2022-08-04 16:39 UTC, SigureMo commented
这个 API 应该也能通过 `Tensor.sgn` 访问吧，这样的话也需要在 `docs/api/paddle/Tensor/Overview_en.rst` 和 `docs/api/paddle/Tensor_cn.rst` 添加下相关内容～可参考 #5089

2022-08-04 16:52 UTC, SigureMo requested changes

2022-08-04 16:52 UTC, SigureMo commented on docs/api/paddle/sgn_cn.rst
> +对于复数张量，此函数返回一个新的张量，其元素与 input 元素的角度相同且绝对值为 1。
这两句与英文的顺序正好是反的，应当两者顺序也是一致的～

2022-08-04 16:52 UTC, SigureMo commented on docs/api/paddle/sgn_cn.rst
> +    - **x** (Tensor) – 输入 Tensor，数据类型为 float16， float32， float64， complex64 或 complex128。
```suggestion
    - **x** (Tensor) – 输入 Tensor，数据类型为 float16、float32、float64、complex64 或 complex128。
```

2022-08-04 16:52 UTC, SigureMo commented on docs/api/paddle/sgn_cn.rst
> +Tensor，输出正负号或复数的单位向量，数据的 shape 大小及数据类型和输入 ``x`` 一致。
这里的话中文应该没问题，英文有点简单了可以修改下，两者也需要一致～

2022-08-09 13:24 UTC, peachlcy commented on docs/api/paddle/sgn_cn.rst
> +Tensor，输出正负号或复数的单位向量，数据的 shape 大小及数据类型和输入 ``x`` 一致。
done

2022-08-09 13:29 UTC, SigureMo approved these changes
LGTM~

2022-08-11 03:59 UTC, Ligoml approved these changes
good job！LGTM

2022-08-11 08:42 UTC, merged