fix nn.Pad1D/2D/3D class issue
PaddlePaddle/docs pull request #5126
Opened 2022-08-11 08:39 UTC by liyongchao911

1. 文档参数部分，对于默认参数加上可选，optional标识，与其他文档保持一致
2. 示例代码部分可以将numpy.prod改成paddle.prod, 并删除import numpy as np

2022-08-11 08:54 UTC, SigureMo requested changes

2022-08-11 08:54 UTC, SigureMo commented on docs/api/paddle/multiplex_cn.rst
> +>>>>>>> 946e985763dcc3ae0f029147b8141c3af4fd9d9a
这里处理冲突出问题啦～

2022-08-11 08:54 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **mode** (str, 可选) - padding的四种模式，分别为 ``'constant'``, ``'reflect'``, ``'replicate'`` 和 ``'circular'``。
```suggestion
  - **mode** (str，可选) - padding的四种模式，分别为 ``'constant'``, ``'reflect'``, ``'replicate'`` 和 ``'circular'``。
```

这里是中文逗号～

2022-08-11 08:54 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +
示例代码直接 COPY-FROM 吧，如果 copy 失败了可以找我，我们一起解决呀～

2022-08-11 13:37 UTC, liyongchao911 commented on docs/api/paddle/nn/Pad1D_cn.rst
> +
Done！

2022-08-11 13:58 UTC, SigureMo requested changes

2022-08-11 13:58 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +COPY-FROM: Paddle.nn.layer.common.Pad1D(Layer):code-example1
这里格式不太对

```
COPY-FROM: paddle.nn.Pad1D
```

在确定唯一的情况下，不建议加一个 `:name:` 属性哒，英文那面也删一下

2022-08-11 13:58 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **value** (float32， 可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为0.0。
改为中文逗号后后面不需要加空格

2022-08-11 13:58 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **value** (float32， 可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为0.0。
注意本地需要用 pre-commit 来处理下代码风格的问题，比如这里的空格

2022-08-11 17:44 UTC, SigureMo requested changes
辛苦先合并下上游修改～

2022-08-11 17:44 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
>      否则填充的格式为[pad_left, pad_right]。
`list[int]` 统一小写吧，英文一起改下

中文的话，同一个参数不需要折行，折行会在中间加空格。

这里的 `如果是int` 中间不应该没有空格，是不是没有合并上游修改，现在最新的 develop 是这样的：

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/38436475/184196298-2596a773-4747-462e-8b3a-29262878aabb.png">

COPY-FROM 我也在那个 PR 里加了，所以重新合并下上游吧

2022-08-11 17:44 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **value** (float32， 可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为0.0。
这里应该直接写 `float`，`float32` 不是 Python 原生的数据类型

2022-08-11 17:44 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **name** (str， 可选) - 该参数供开发人员打印调试信息时使用，具体用法请参见 :ref:`api_guide_Name` ，缺省值为None。
这里可以改成这个：

https://github.com/PaddlePaddle/docs/blob/6dc68c907618eff2b3fdddc973e528d8ab4cd68f/docs/templates/common_docs.py#L42

英文可同步修改为：

https://github.com/PaddlePaddle/docs/blob/6dc68c907618eff2b3fdddc973e528d8ab4cd68f/docs/templates/common_docs.py#L9

可能需要注意 copy 过来后改一下格式～

2022-08-11 17:44 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **value** (float32， 可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为0.0。
```
:math:`0.0`
```

这里的数字默认值可以这样写～

2022-08-15 06:49 UTC, closed without merging

2022-08-15 06:50 UTC, liyongchao911 commented
issue a new PR # 5136 instead!