update Paddle2onnx doc
PaddlePaddle/docs pull request #5130
Opened 2022-08-12 04:29 UTC by yeliang2258

update Paddle2onnx doc

2022-08-12 06:13 UTC, Ligoml commented on docs/guides/advanced/model_to_onnx_cn.md
> +</p>
图像采用如下格式即可正确显示：
```
![](./images/paddle2onnx1.png)
```

2022-08-15 03:26 UTC, jiangjiajun requested changes

2022-08-15 03:26 UTC, jiangjiajun commented on docs/guides/advanced/model_to_onnx_cn.md
> +wget https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/model_zoo/classification/images/ILSVRC2012_val_00000010.jpeg
这两个命令无法下载到真正的文件，需提供raw data链接

2022-08-15 03:26 UTC, jiangjiajun commented on docs/guides/advanced/model_to_onnx_cn.md
> +```
上面这段代码出现的太突兀，如果只是展示如何加载模型和推理，只需加载模型和使用一个fake数据推理即可。 无需再出现preprocess和postprocess接口的调用

2022-08-15 03:26 UTC, jiangjiajun commented on docs/guides/advanced/model_to_onnx_cn.md
> +1. 目前 Paddle2ONNX 已经支持 170 多个 Paddle OP，多数 Paddle 的模型都可顺利导出为 ONNX 格式，如果在转换中遇到不支持的 OP，请到 Paddle2ONNX Repo 下提 Issue，我们都会尽快支持。如果量化模型转换问题可以先参考文档，如果还是不能解决，也请到 Paddle2ONNX 下提 Issue：[量化模型导出说明](https://githu
改为

- PaddleSlim量化模型导出ONNX，参考[量化导出说明文档](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/quantize.md)

如在导出ONNX过程遇到问题，欢迎通过[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX.git)开源项目Issue方式反馈。

2022-08-15 03:26 UTC, jiangjiajun commented on docs/guides/advanced/model_to_onnx_cn.md
> +1. 模型转换过程会将 Paddle 的算子逐一转换为 ONNX 的算子。由于 ONNX 的算子随版本迭代不断升级，不同的推理引擎对 ONNX 算子版本支持也不完全一致，因此，使用 Paddle2ONNX 对 Paddle 模型进行转换时，需要指定 ONNX 的算子版本，此参数应根据待部署的推理引擎进行设置，在转换中可以使用 Paddle2ONNX 的 opset_version 选项进行指定，
参数选项没看到在哪里写

2022-08-15 03:32 UTC, yeliang2258 commented on docs/guides/advanced/model_to_onnx_cn.md
> +```
之前的要求是要给一个实际的例子，比如这里就是给一个图片分类

2022-08-15 05:25 UTC, jiangjiajun approved these changes

2022-08-15 06:58 UTC, Ligoml commented on docs/guides/advanced/model_to_onnx_cn.md
> +目前官方支持加载 ONNX 模型并进行推理的深度学习框架，除飞桨外，还有 PyTorch, MXNet， Caffe2, ML.NET，TensorRT 和 Microsoft CNTK 等主流框架都对 ONNX 有着不同程度的支持；并且 TensorFlow 也非官方的支持 ONNX。除深度学习框架外，大多推理引擎或者国产硬件，比如如 RK、地平线、鲲云等也都支持加载 ONNX 模型进行推理，
<img width="263" alt="image" src="https://user-images.githubusercontent.com/39876205/184589708-5437d7f3-7ba8-42ea-a934-2784242a684b.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/39876205/184589543-feb179e3-02a4-4fac-bd64-e46d927ed2fa.png">

注意中英文标点符号不要混用，建议统一使用中文顿号 ```、```

2022-08-15 06:58 UTC, Ligoml commented on docs/guides/advanced/model_to_onnx_cn.md
> +import numpy as np
代码中好像没有用到np？

2022-08-15 06:58 UTC, Ligoml commented on docs/guides/advanced/model_to_onnx_cn.md
> +使用 Paddle 完成模型训练之后，转换成 ONNX 协议只需要调用 paddle.onnx.export 接口，便会在指定的路径下生成 ONNX 模型。关于 paddle.onnx.export 接口更详细的使用方法，请参考 [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/onnx/export_c
请参考 [API 文档]

2022-08-15 07:54 UTC, Ligoml approved these changes
LGTM

2022-08-16 02:53 UTC, merged