update paddle.nn.Pad1D/2D/3D cn docs
PaddlePaddle/docs pull request #5136
Opened 2022-08-15 06:49 UTC by liyongchao911

- add "可选" for the default parameters
- fix some format issue

PADDLEPADDLE_PR=45068

2022-08-15 07:10 UTC, SigureMo requested changes
这几篇有相同的问题，辛苦修改一下～

此外可以一起修改下相应的 function API（`paddle.nn.functional.pad`），我记得梦柳是建议成对修改的～

2022-08-15 07:10 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **padding** (Tensor|list[int]|int) - 填充大小。如果是 int，则在所有待填充边界使用相同的填充，
中文里同一个参数不建议折行，直接把下一行放在`，`后面即可

2022-08-15 07:10 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **value** (float，可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为 0.0。
这里的默认值用：

```
:math:`0.0`
```

2022-08-15 07:10 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **data_format** (str，可选)  - 指定输入的 format，可为 ``'NCL'`` 或者 ``'NLC'``，默认值为 ``'NCL'``。
format 翻译一下吧，参考其他的大多翻译成了`数据格式`

2022-08-15 07:10 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
>      填充输入边界值；``'circular'`` 为循环填充输入。默认值为 ``'constant'``。
这里也不应该折行，我建议使用列表的方式来展示各个可选值的意义：

```rst
  - **mode** (str，可选) - padding 的模式，可选值为 ``'constant'``, ``'reflect'``, ``'replicate'`` 和 ``'circular'``。默认值为 ``'constant'``。
    - ``'constant'`` 表示填充常数 ``value``；
    - ``'reflect'`` 表示填充以输入边界值为轴的映射；
    - ``'replicate'`` 表示填充输入边界值；
    - ``'circular'`` 为循环填充输入。
```

2022-08-15 10:20 UTC, SigureMo requested changes

2022-08-15 10:20 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +    - ``'circular'`` 为循环填充输入。
<img width="845" alt="image" src="https://user-images.githubusercontent.com/38436475/184617217-62676336-c456-4c72-8cb5-f52c670a4bca.png">

这里渲染不太对，我发现是缩进少一个空格，唔，可以找一个在线预览的网站来调整下，不然每次都等预览出来才知道问题。

比如 https://livesphinx.herokuapp.com/

2022-08-15 10:20 UTC, SigureMo commented on docs/api/paddle/nn/Pad1D_cn.rst
> +  - **mode** (str，可选) - padding 的四种模式，分别为 ``'constant'``, ``'reflect'``, ``'replicate'`` 和 ``'circular'``。
这里各个可选值在中文用`、`隔开

另外，默认值没啦 :joy:，记得加回来。英文那边也要同步修改下

2022-08-15 10:20 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **x** (Tensor) - Tensor，format 可以为 ``'NCL'``, ``'NLC'``, ``'NCHW'``, ``'NHWC'``, ``'NCDHW'``或 ``'NDHWC'``，默认值为 ``'NCHW'``，数据类型支持 float16, float32, float64, int32, int64。
这里同样要用`、`隔开

2022-08-15 10:20 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +    - 3. 当输入维度为 5 时，pad 的格式为[pad_left, pad_right, pad_top, pad_bottom, pad_front, pad_back]。
这里要么直接用有序列表 `1.2.3.`，要么直接用无序列表 `-`，不要两者混在一起，另外这里缩进也少一个空格（rst 貌似 3 缩进），可利用上面那个在线预览调整下

2022-08-15 10:20 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **value** (float32，可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为:math:`0.0`。
这里的 `float`

2022-08-15 15:19 UTC, SigureMo requested changes
辛苦再稍微修改一下～

2022-08-15 15:19 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +     - ``'circular'`` 为循环填充 ``x``。具体结果可见以下示例。
这里列表还是有问题，需要空行：

<img width="835" alt="image" src="https://user-images.githubusercontent.com/38436475/184656401-ffedb2b3-a3ed-4808-b029-70dec9d22649.png">

这里它将紧贴着的渲染成了 `<dl>`，可参考 https://zh-sphinx-doc.readthedocs.io/en/latest/rest.html#id18 ，这里有说「列表可以嵌套，但是需跟父列表使用空行分隔」，所以可能需要写成这样：

```text
  - **mode** (str，可选) - padding 的四种模式，分别为 ``'constant'``、 ``'reflect'``、 ``'replicate'`` 和 ``'circular'``，默认值为 ``'constant'``。

     - ``'constant'`` 表示填充常数 ``value``；
     - ``'reflect'`` 表示填充以 ``x`` 边界值为轴的映射；
     - ``'replicate'`` 表示填充 ``x`` 边界值；
     - ``'circular'`` 为循环填充 ``x``。具体结果可见以下示例。
 
  - **value** (float32，可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为:math:`0.0`。
```

非常抱歉并不是很熟悉嵌套列表，所以之前有点误导

2022-08-15 15:19 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **value** (float32，可选) - 以 ``'constant'`` 模式填充区域时填充的值。默认值为:math:`0.0`。
这里的 `float32` 貌似还没有改成 `float`

2022-08-15 15:19 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **data_format** (str，可选)  - 指定 ``x`` 的数据格式，可为 ``'NCL'``, ``'NLC'``, ``'NCHW'``, ``'NHWC'``, ``'NCDHW'``或 ``'NDHWC'``，默认值为 ``'NCHW'``。
这里的可选值也应该是用`、`分割，上面也有很多处，需要都改掉。

另外，中文标点符号和中英文之间不需要加空格，所以`、`两侧不应该有空格。

2022-08-17 09:40 UTC, SigureMo requested changes
应该没有其他问题了

英文目测没问题，预览的话好像看不了

2022-08-17 09:40 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **x** (Tensor) - Tensor，format 可以为 ``'NCL'``、``'NLC'``、``'NCHW'``、``'NHWC'``、``'NCDHW'`` 或 ``'NDHWC'``，默认值为 ``'NCHW'``，数据类型支持float16、float32、float64、int32、int64。
这个文件代码风格检查没过，这里 float16 前少一个空格，用 pre-commit 格式化下吧

2022-08-17 09:40 UTC, SigureMo commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **mode** (str，可选) - padding 的四种模式，分别为 ``'constant'``、``'reflect'``、``'replicate'`` 和``'circular'``，
<img width="815" alt="image" src="https://user-images.githubusercontent.com/38436475/185086417-587630c0-49da-4ae0-ae35-49f0904cba86.png">

这里还是少一个空格

2022-08-17 12:30 UTC, liyongchao911 commented on docs/api/paddle/nn/functional/pad_cn.rst
> +  - **mode** (str，可选) - padding 的四种模式，分别为 ``'constant'``、``'reflect'``、``'replicate'`` 和``'circular'``，
done！

2022-08-17 19:05 UTC, SigureMo approved these changes
LGTM，中文源码和预览应该可以了，英文源码目测是 ok 的，但预览貌似没有构建上不敢确定。

2022-08-18 05:23 UTC, SigureMo commented
@Ligoml 我觉得没啥问题啦，交给你啦～～～

2022-08-19 09:35 UTC, Ligoml approved these changes
good job！
LGTM

2022-08-23 06:05 UTC, merged