【PaddlePaddle Hackathon 3 No.14】为 Paddle 新增 remainder_ API
PaddlePaddle/docs pull request #5156
Opened 2022-08-19 06:30 UTC by zrr1999

https://github.com/PaddlePaddle/Paddle/pull/45266

2022-08-26 06:16 UTC, Ligoml commented
paddle.remainder_的中文文档也需要单独创建一个文件

2022-08-26 08:20 UTC, zrr1999 commented
> paddle.remainder_的中文文档也需要单独创建一个文件

好的，已经添加

2022-08-26 09:27 UTC, Ligoml commented
> > paddle.remainder_的中文文档也需要单独创建一个文件
> 
> 好的，已经添加

我指的是paddle.remainder_ ，inplace的这个API也需要自己的文档哈~ 另外paddle.remainder因为一些原因缺失了中文文档，感谢补充

2022-08-26 09:49 UTC, zrr1999 commented
> paddle.reshape_

好的，这部分也已经添加啦

2022-08-29 14:25 UTC, SigureMo requested changes

2022-08-29 14:25 UTC, SigureMo commented on docs/api/paddle/remainder__cn.rst
> +remainder
```suggestion
remainder_
```

2022-08-29 14:25 UTC, SigureMo commented on docs/api/paddle/remainder__cn.rst
> +.. py:function:: paddle.remainder(x, y, name=None)
```suggestion
.. py:function:: paddle.remainder_(x, y, name=None)
```

2022-08-29 14:25 UTC, SigureMo commented on docs/api/api_label
> +paddle.remainder	.. _cn_api_tensor_remainder:
这里的映射是用来生成英文文档的 label 的

```suggestion
paddle.remainder	.. _api_tensor_remainder:
```

2022-08-29 14:25 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +        - x（Tensor）- 多维 Tensor。数据类型为 float32 、float64、int32 或 int64。
参数名 `x` 需要加粗（`**x**`）

下同

paddle.mod 最好也改一下～

2022-08-29 14:25 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +        - name（str，可选）- 操作的名称(可选，默认值为 None）。更多信息请参见 :ref:`api_guide_Name`。
改用这个吧，注意调整格式（比如参数名也需要加粗）

https://github.com/PaddlePaddle/docs/blob/a817547f68f636d1ff07ceb293dcc529ea66aad9/docs/templates/common_docs.py#L42

2022-08-29 14:25 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +.. _cn_api_tensor_remainder:
有点奇怪的是，这个页面（<https://preview-pr-5156.paddle-docs-preview.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/remainder_cn.html>）无法渲染在侧边栏，在该页面也无法渲染侧边栏

https://github.com/PaddlePaddle/Paddle/blob/126940b344022c44cc220a7e0214fcf300957b7e/python/paddle/tensor/math.py#L787

另外 mod 和 remainder 只是 alias 关系，也许我们可以有一个规范来避免这种重复 @BrilliantYuKaimin （这个和 mod 内容基本是一致的）

2022-08-29 15:05 UTC, zrr1999 commented on docs/api/paddle/remainder_cn.rst
> +        - name（str，可选）- 操作的名称(可选，默认值为 None）。更多信息请参见 :ref:`api_guide_Name`。
好的已修改

2022-08-29 15:05 UTC, zrr1999 commented on docs/api/paddle/remainder_cn.rst
> +        - x（Tensor）- 多维 Tensor。数据类型为 float32 、float64、int32 或 int64。
好的已修改

2022-08-29 15:17 UTC, SigureMo approved these changes
LGTM～～～

2022-08-30 06:26 UTC, SigureMo approved these changes

2022-08-30 06:26 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +        - **name**（str，可选） - 具体用法请参见 :ref:`api_guide_Name` ，一般无需设置，默认值为 None。
<img width="748" alt="image" src="https://user-images.githubusercontent.com/38436475/187364870-03cf5871-a883-423c-a8d8-c0089fc9b44f.png">

这里将全角括号 `（` 改为空格 + 半角括号 ` (` 即可

```rst
        - **x** (Tensor) - 多维 Tensor。数据类型为 float32 、float64、int32 或 int64。
        - **y** (Tensor) - 多维 Tensor。数据类型为 float32 、float64、int32 或 int64。
        - **name** (str，可选) - 具体用法请参见 :ref:`api_guide_Name` ，一般无需设置，默认值为 None。
                  ^ 空格 空格 ^
```

2022-08-30 06:39 UTC, zrr1999 commented on docs/api/paddle/remainder_cn.rst
> +        - **name**（str，可选） - 具体用法请参见 :ref:`api_guide_Name` ，一般无需设置，默认值为 None。
好的感谢，已修改

2022-08-30 06:40 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +   ``paddle.remainder`` 遵守 broadcasting，如您想了解更多，请参见 :ref:`cn_user_guide_broadcasting` 。
`broadcasting` 在中文里就用`广播`吧，尽可能都翻译一下

2022-08-30 06:45 UTC, zrr1999 commented on docs/api/paddle/remainder_cn.rst
> +   ``paddle.remainder`` 遵守 broadcasting，如您想了解更多，请参见 :ref:`cn_user_guide_broadcasting` 。
好的，已修改

2022-08-30 08:02 UTC, Ligoml commented on docs/api/paddle/remainder_cn.rst
> +.. _cn_api_tensor_remainder:
这个很神奇，因为代码里就是这么写的：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/math.py#L787

也就是说这三个API拥有同一个ID，所以官网只会生成其中一个API文档，这个我之前提过，解决办法就是def 三个API，然后分别管理文档

2022-08-30 08:08 UTC, Ligoml approved these changes
LGTM for docs

2022-08-30 08:11 UTC, SigureMo commented on docs/api/paddle/remainder_cn.rst
> +.. _cn_api_tensor_remainder:
```python
def mod(x, y, name=None):
    return remainder(x, y, name)

mod.__doc__ = remainder.__doc__
```

这样？呃……好麻烦……

2022-08-31 06:27 UTC, merged