【PaddlePaddle Hackathon 3】13 新增 API triu_indices
PaddlePaddle/docs pull request #5161
Opened 2022-08-19 08:17 UTC by Rayman96

PADDLEPADDLE_PR=45168

https://github.com/PaddlePaddle/Paddle/pull/45168

2022-08-20 18:22 UTC, SigureMo requested changes
- 中英文内容上要尽可能保持一致
- 需要在 Overview 中添加索引，可参考 #5089（如果这个函数无法作为 Tensor 一个方法进行访问的话，不需要像那个 PR 一样修改 Tensor 相关的一些内容）

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +返回行数和列数已知的二维矩阵中上三角矩阵元素的行列坐标，其中上三角矩阵为原始矩阵某一对角线右上部分元素的子矩阵。
中文文档貌似缺失「Indices are ordered based on row and then columns.」的翻译

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +    - **offset** (int，可选) - 确定从指定二维平面中获取对角线的位置。
这里描述感觉和英文不一样呀，另外缺少默认值的描述。

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +    - **dtype** (int，可选) - 指定输出张量的数据类型，默认值为 int64。
这里英文缺少默认值描述，中文缺少数据类型可选值描述。

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +Tensor，二维矩阵的上三角矩阵行坐标和列坐标。数据类型和参数 dtype 一致。
这里也和英文不是很一致。

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +    - **dtype** (int，可选) - 指定输出张量的数据类型，默认值为 int64。
dtype 的类型怎么会是 int 呢？typo？

2022-08-20 18:22 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +COPY-FROM: paddle.triu_indices
示例代码中文没问题，英文那边在只有一个示例代码的情况下不推荐添加 name 属性

```diff
      Examples:
          .. code-block:: python
-             :name: triu_indices-example    # 删去 name 行
+                                            # 中间空一行，避免解析为 rst directive 的属性
              import paddle
              # example 1, default offset value
              data1 = paddle.triu_indices(4,4,0)
```

2022-08-21 09:40 UTC, Rayman96 commented
上述已修改，关于col是否可以取None的文档部分待讨论后确定最终版本

2022-08-23 10:41 UTC, SigureMo requested changes
此外还需要注意下代码风格问题，可以安装 pre-commit 自动修复，如果安装后 commit 前报错可以参考 #5140 手动修复

2022-08-23 10:41 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +        col输入默认为None，此时将col设置为row的取值，代表输入为正方形矩阵。
中文文档不建议折行，直接跟在后面即可

需要加 `，可选`，英文同

2022-08-23 10:41 UTC, SigureMo commented on docs/api/paddle/triu_indices_cn.rst
> +    - **dtype** (str|np.dtype|paddle.dtype，可选) - 指定输出张量的数据类型，默认值为 int64。
这里相对于英文缺少可选值的描述

2022-08-23 10:59 UTC, Rayman96 commented on docs/api/paddle/triu_indices_cn.rst
> +        col输入默认为None，此时将col设置为row的取值，代表输入为正方形矩阵。
中文几处折行都已修改，中英文都已补充“可选”

2022-08-23 10:59 UTC, Rayman96 commented on docs/api/paddle/triu_indices_cn.rst
> +    - **dtype** (str|np.dtype|paddle.dtype，可选) - 指定输出张量的数据类型，默认值为 int64。
已补充

2022-08-23 11:55 UTC, SigureMo commented
```bash
pip install pre-commit==2.17.0
pre-commit run --files docs/api/paddle/Overview_cn.rst
pre-commit run --files docs/api/paddle/triu_indices_cn.rst
```

仍然有代码风格问题，主要是中英文间没有添加空格，可尝试运行上面的命令来修复这两个文件里的问题

2022-08-23 13:19 UTC, SigureMo approved these changes
LGTM，之后等个预览再看看，估计是没问题了

2022-08-23 13:20 UTC, Rayman96 commented
> LGTM，之后等个预览再看看，估计是没问题了

嗯嗯好的

2022-08-23 13:30 UTC, Rayman96 commented
> LGTM，之后等个预览再看看，估计是没问题了

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/35597076/186170749-2fc54341-e933-4ced-b017-a8ce7560e033.png">
看起来好像可以了

2022-08-24 07:09 UTC, Ligoml approved these changes
good job！LGTM

2022-08-25 09:04 UTC, merged