update PixelShuffle api
PaddlePaddle/docs pull request #5192
Opened 2022-08-25 11:11 UTC by liyongchao911

fix some format issue

2022-08-26 05:35 UTC, SigureMo requested changes
整体上没啥问题，改下小问题应该就可以了～

2022-08-26 05:35 UTC, SigureMo commented on docs/api/paddle/nn/PixelShuffle_cn.rst
上面那些 shape 的描述可以参考 PixelUnshuffle 改成 :math:\`xxx\`，

<img width="873" alt="image" src="https://user-images.githubusercontent.com/38436475/186828116-23092029-bab9-4c8e-ac7b-e827f2d3d050.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/38436475/186828090-0127b529-926d-40d1-8ac3-2e631fa1919a.png">

明显 PixelUnshuffle 好看很多

2022-08-26 05:35 UTC, SigureMo commented on docs/api/paddle/nn/PixelShuffle_cn.rst
下同（nn.functional.pixel_shuffle）

2022-08-26 05:35 UTC, SigureMo commented on docs/api/paddle/nn/PixelShuffle_cn.rst
英文也要改一下～

2022-08-26 07:55 UTC, SigureMo requested changes

2022-08-26 07:55 UTC, SigureMo commented on docs/api/paddle/nn/PixelShuffle_cn.rst
> +该算子将一个形为 :math:`[N, C, H, W]` 或是 :math:`[N, H, W, C]` 的 Tensor 重新排列成形为 :math:`[N, C/r**2, H*r, W*r]` 或 :math:`[N, H*r, W*r, C/r**2]`  的 Tensor。这样做有利于实现步长（stride）为 :math:`1/r` 的高效 sub-pixel（亚像素）卷积。详见
<img width="877" alt="image" src="https://user-images.githubusercontent.com/38436475/186851675-84578e51-e2f5-4cea-9ea3-f3fd76055bd9.png">

LaTeX 里用 `a^b` 表示乘方而不是 `a**b`，用 `a \times b` 或者直接不写表示乘，而不是 `a*b`，英文同

另外 functional 下的没改，英文同

2022-08-26 08:44 UTC, Ligoml commented
改的部分都ok，另外还有几个API的参数没加粗，一起改了吧~

<img width="500" alt="image" src="https://user-images.githubusercontent.com/39876205/186863358-572711e5-3c45-43bc-baab-f15d4e1bb6df.png">

2022-08-29 08:02 UTC, SigureMo approved these changes
LGTM～～～～～

2022-08-29 09:12 UTC, Ligoml approved these changes
good job！LGTM

2022-08-29 09:40 UTC, merged