Paddle 文档修复 test=document_fix
PaddlePaddle/docs pull request #5211
Opened 2022-08-27 02:54 UTC by mrcangye

1. paddle.nn.Sigmoid
    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Sigmoid_cn.html#sigmoid](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Sigmoid_cn.html#sigmoid)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Sigmoid_en.html#sigmoid](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Sigmoid_en.html#sigmoid)
    存在问题：公式问题，PR修复

2. paddle.nn.functional.silu

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/silu_cn.html#silu](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/silu_cn.html#silu)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/silu_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/silu_en.html)
    存在问题：公式问题，PR修复

3. paddle.nn.SmoothL1Loss

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/SmoothL1Loss_cn.html#smoothl1loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/SmoothL1Loss_cn.html#smoothl1loss)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/SmoothL1Loss_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/SmoothL1Loss_en.html)
    存在问题：出现op用语，zi公式未能成功显示，代码示例没有结果输出，PR修复

4. paddle.nn.functional.smooth_l1_loss

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/smooth_l1_loss_cn.html#smooth-l1-loss](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/smooth_l1_loss_cn.html#smooth-l1-loss)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/smooth_l1_loss_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/smooth_l1_loss_en.html)
    存在问题：出现op用语，zi公式未能成功显示，代码示例没有结果输出，PR修复

5. paddle.nn.Softmax

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Softmax_cn.html#softmax](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Softmax_cn.html#softmax)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Softmax_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Softmax_en.html)
    存在问题：出现op用语，PR修复

6. paddle.nn.functional.softmax

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/softmax_cn.html#softmax](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/softmax_cn.html#softmax)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softmax_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softmax_en.html)
    存在问题：出现op用语，PR修复

7. paddle.nn.Softplus

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Softplus_cn.html#softplus](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Softplus_cn.html#softplus)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Softplus_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/Softplus_en.html)
    存在问题：公式问题，PR修复

8. paddle.nn.functional.softplus

    [中：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/softplus_cn.html#softplus](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/softplus_cn.html#softplus)
    [英：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softplus_en.html](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softplus_en.html)
    存在问题：公式问题，PR修复

2022-08-27 07:56 UTC, SigureMo requested changes

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/functional/sigmoid_cn.rst
>  参数
下面参数 `x` 类型 Tensor 缺少括号，后面 `数据类型为 float32，float64。`，`，`改为`、`

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/functional/silu_cn.rst
下面参数 `x` 需要加粗

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/functional/softmax_cn.rst
下面三个参数名没有加粗

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/Softmax_cn.rst
下面参数名 `axis` 没有加粗

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/Softplus_cn.rst
>  其中，:math:`x` 为输入的 Tensor
同参数名没加粗……

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/Softplus_cn.rst
>  其中，:math:`x` 为输入的 Tensor
`nn.functional.softplus` 有同样问题

2022-08-27 07:56 UTC, SigureMo commented on docs/api/paddle/nn/SmoothL1Loss_cn.rst
下面参数类型里的 `string` 改为 `str`

`nn.functional.smooth_l1_loss` 同

2022-09-01 13:35 UTC, mrcangye commented
@SigureMo 大佬有空再审核下

2022-09-02 19:35 UTC, SigureMo commented on docs/api/paddle/nn/functional/softplus_cn.rst
> + - **threshold** (float，可选) - Softplus 激活计算公式中的 :math:`threshold` 值。默认值为 20。
关于参数使用 attr，这里我觉得因为明确说明了 `公式中的`，因此我觉得使用 math 的优先级比 attr 更高些，而且这个是在陈述自己这个参数而不是引用别的参数。@BrilliantYuKaimin 觉得如何？

以及是否将目前规范（草案）中下述表述进行修改？

```diff
- 在文档的源文件中应当用 :attr:`x` 这样的形式来表示一个参数。
+ 在文档的源文件中应当用 :attr:`x` 这样的形式来引用一个参数。
```

「引用」这一表述是否准确我不太确定，可能需要再调整

2022-09-02 19:39 UTC, SigureMo commented
一些最近规范中比较确定的部分我直接修改了，还没有确定的部分或者可能有争议的部分暂时没改，以及[参数可选值详情是否需要以列表的形式展开](https://github.com/PaddlePaddle/docs/discussions/5243#discussioncomment-3539418)的问题将会在规范中进一步讨论以确定。

本 PR 可能会稍等等再 merge，可以先改好英文那边的 PR～

2022-09-03 00:23 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/functional/softplus_cn.rst
> + - **threshold** (float，可选) - Softplus 激活计算公式中的 :math:`threshold` 值。默认值为 20。
是的，在这样的语境下应该使用 math。

把「引用」换成「提及」如何？

2022-09-03 00:24 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Sigmoid_cn.rst
> +        sigmoid(x) = \frac{1}{1 + e^{-x}}
```suggestion
        sigmoid(x) = \frac{1}{1 + \mathrm{e}^{-x}}
```

2022-09-03 00:24 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Silu_cn.rst
> +    silu(x) = \frac{x}{1 + e^{-x}}
```suggestion
    silu(x) = \frac{x}{1 + \mathrm{e}^{-x}}
```

2022-09-03 00:32 UTC, BrilliantYuKaimin reviewed
自然对数的底 $\mathrm e$ 建议使用正体形式。

2022-09-03 00:32 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Softplus_cn.rst
>      \text{为了保证数值稳定性，当}\,beta * x > threshold\,\text{时，函数转变为线性函数 x}。
```suggestion
    \text{为了保证数值稳定性，当}\,beta * x > threshold\,\text{时，函数转变为线性函数} x。
```

2022-09-03 00:32 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/functional/sigmoid_cn.rst
> +    sigmoid(x) = \frac{1}{1 + e^{-x}}
```suggestion
    sigmoid(x) = \frac{1}{1 + \mathrm{e}^{-x}}
```

2022-09-03 00:32 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/functional/silu_cn.rst
> +    silu(x) = \frac{x}{1 + e^{-x}}
```suggestion
    silu(x) = \frac{x}{1 + \mathrm{e}^{-x}}
```

2022-09-03 00:32 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Silu_cn.rst
>  其中，:math:`x` 为输入的 Tensor
```suggestion
其中 :math:`x` 为输入的 Tensor。
```

2022-09-03 00:46 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/SmoothL1Loss_cn.rst
> +    - **input** (Tensor)：输入 `Tensor`，数据类型为 float32。其形状为 :math:`[N, C]`，其中 :math:`C` 为类别数。对于多维度的情形下，它的形状为 :math:`[N, C, d_1, d_2, ..., d_k]`，k >= 1。
```suggestion
    - **input** (Tensor)：输入 `Tensor`，数据类型为 float32。其形状为 :math:`[N, C]`，其中 :math:`C` 为类别数。对于多维度的情形下，它的形状为 :math:`[N, C, d_1, d_2, ..., d_k]`，:math:`k \geqslant 1`。
```

2022-09-03 00:47 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Softmax_cn.rst
> +    - **axis** (int，可选) - 指定对输入 Tensor 进行运算的轴。:attr:`axis` 的有效范围是 :math:`[-D, D)`，D 是输入 Tensor 的维度，``axis`` 为负值时与 :math:`axis + D` 等价。默认值为 -1。
```suggestion
    - **axis** (int，可选) - 指定对输入 Tensor 进行运算的轴。:attr:`axis` 的有效范围是 :math:`[-D, D)`，:math:`D` 是输入 Tensor 的维度，``axis`` 为负值时与 :math:`axis + D` 等价。默认值为 -1。
```

2022-09-03 00:48 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/functional/smooth_l1_loss_cn.rst
> +    - **input** (Tensor) - 输入 `Tensor`，数据类型为 float32。其形状为 :math:`[N, C]`，其中 :math:`C` 为类别数。对于多维度的情形下，它的形状为 :math:`[N, C, d_1, d_2, ..., d_k]`，k >= 1。
```suggestion
    - **input** (Tensor) - 输入 `Tensor`，数据类型为 float32。其形状为 :math:`[N, C]`，其中 :math:`C` 为类别数。对于多维度的情形下，它的形状为 :math:`[N, C, d_1, d_2, ..., d_k]`，:math:`k \geqslant 1`。
```

2022-09-03 00:55 UTC, BrilliantYuKaimin commented on docs/api/paddle/nn/Softplus_cn.rst
> +    softplus(x) = \frac{1}{beta} * \log(1 + e^{beta * x}) \\
这里还是写成分段函数的形式吧。math 环境里不应该出现这样的长句。

另外建议用 `\beta` 代替 `beta`，用 `\varepsilon` 代替 `threshold`。这样可以缩短公式的长度。后面解释参数的地方也同样地修改。

2022-09-03 06:46 UTC, SigureMo commented on docs/api/paddle/nn/functional/softplus_cn.rst
> + - **threshold** (float，可选) - Softplus 激活计算公式中的 :math:`threshold` 值。默认值为 20。
> 把「引用」换成「提及」如何？

赞同～

2022-09-03 06:52 UTC, SigureMo commented on docs/api/paddle/nn/Softplus_cn.rst
> +    softplus(x) = \frac{1}{beta} * \log(1 + e^{beta * x}) \\
@mrcangye 这个和英文的一起改吧，我这边还没申请 Paddle repo 下的 write 权限，目前那边我还改不了

2022-09-24 20:24 UTC, SigureMo approved these changes
LGTMeow~

2022-09-26 06:23 UTC, SigureMo commented
@Ligoml 有空瞅瞅这个 PR，已经很久了

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/Silu_cn.rst
> +    silu(x) = \frac{x}{1 + \mathrm{e}^{-x}}
<img width="488" alt="image" src="https://user-images.githubusercontent.com/39876205/192957609-6000e476-a6eb-4c1a-b39d-04cc1c40cadc.png">

中文文档ok，但是英文文档好像不太对

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/SmoothL1Loss_cn.rst
> +    loss(x,y) = \frac{1}{n}\sum_{i}z_i
```suggestion
    loss(x, y) = \frac{1}{n}\sum_{i}z_i
```

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/Softmax_cn.rst
>  .. py:class:: paddle.nn.Softmax(axis=-1, name=None)
示例代码中的第三方库numpy可以不引入，试着改一下？

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/Softplus_cn.rst
>  Softplus 激活层
示例代码中的import numpy删一下吧

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/functional/softmax_cn.rst
>  .. py:function:: paddle.nn.functional.softmax(x, axis=-1, dtype=None, name=None)
同paddle.nn.Softmax，改一下示例代码

2022-09-29 06:50 UTC, Ligoml commented on docs/api/paddle/nn/functional/softplus_cn.rst
>  softplus 激活层
同paddle.nn.Softplus，删一下numpy

2022-10-08 06:14 UTC, Ligoml approved these changes
good job！
LGTM

2022-10-08 06:38 UTC, merged