【PaddlePaddle Hackathon 3 No.20】为 Paddle 新增 vsplit API
PaddlePaddle/docs pull request #5213
Opened 2022-08-27 09:33 UTC by Asthestarsfalll

增加paddle.vsplit的中文文档

2022-08-29 18:25 UTC, SigureMo requested changes
这个 API 可以通过 paddle.vsplit 访问到吧，那需要在 docs/api/paddle/Overview_cn.rst 添加相关内容

另外最好也在 docs/api/api_label 添加一下英文文档 label

2022-08-29 18:25 UTC, SigureMo commented on docs/api/paddle/vsplit_cn.rst
> +       - **x** (Tensor) - 输入变量，数据类型为 bool、float16、float32、float64、uint8、int8、int32、int64 的多维 Tensor。
这里缺少 `A Tensor whose dimension must be greater than 2.` 的翻译

2022-08-29 18:25 UTC, SigureMo commented on docs/api/paddle/vsplit_cn.rst
> +       - **num_or_sections** (int|list|tuple) - 如果 ``num_or_sections`` 是一个整数，则表示 Tensor 平均划分为相同大小子 Tensor 的数量。如果 ``num_or_sections`` 是一个 list 或 tuple，那么它的长度代表子 Tensor 的数量，它的元素可以是整数或者形状为[1]的 Tensor，依次
英文缺少 `在 list 或 tuple 中，` 及之后的内容

2022-08-29 18:25 UTC, SigureMo commented on docs/api/paddle/vsplit_cn.rst
> +COPY-FROM: paddle.vsplit
<img width="462" alt="image" src="https://user-images.githubusercontent.com/38436475/187270660-7871a9d7-4104-4f67-a4ed-e0b938952ac9.png">

在 PR 描述里加上 `PADDLEPADDLE_PR=44853` 后 rerun 下 CI 吧

2022-08-30 12:41 UTC, Asthestarsfalll commented on docs/api/paddle/vsplit_cn.rst
> +       - **x** (Tensor) - 输入变量，数据类型为 bool、float16、float32、float64、uint8、int8、int32、int64 的多维 Tensor。
down

2022-08-30 12:41 UTC, Asthestarsfalll commented on docs/api/paddle/vsplit_cn.rst
> +       - **num_or_sections** (int|list|tuple) - 如果 ``num_or_sections`` 是一个整数，则表示 Tensor 平均划分为相同大小子 Tensor 的数量。如果 ``num_or_sections`` 是一个 list 或 tuple，那么它的长度代表子 Tensor 的数量，它的元素可以是整数或者形状为[1]的 Tensor，依次
down

2022-08-30 12:42 UTC, Asthestarsfalll commented on docs/api/paddle/vsplit_cn.rst
> +COPY-FROM: paddle.vsplit
down

2022-08-30 19:01 UTC, SigureMo requested changes
其余应该没什么问题了

2022-08-30 19:01 UTC, SigureMo commented on docs/api/paddle/vsplit_cn.rst
> +       - **x** (Tensor) - 输入变量，数据类型为 bool、float16、float32、float64、uint8、int8、int32、int64 的多维 Tensor， 其维度必须大于 2。
这个参数最好做到和英文完全一致吧，包括顺序

以及英文貌似没有 `uint8` 和 `int8`，哪个是正确的呢？

2022-08-30 19:01 UTC, SigureMo commented on docs/api/paddle/vsplit_cn.rst
> +分割后的 Tensor 列表。
```suggestion

list[Tensor]，分割后的 Tensor 列表。
```

2022-09-02 07:42 UTC, Ligoml commented
@Asthestarsfalll 请尽快处理一下文档的意见哈

2022-09-02 08:42 UTC, Asthestarsfalll commented
> @Asthestarsfalll 请尽快处理一下文档的意见哈

已处理

2022-09-02 08:59 UTC, SigureMo approved these changes
LGTM~~~

2022-09-08 07:33 UTC, Ligoml approved these changes
LGTM

2022-09-09 08:51 UTC, merged