cn api fix bugs
PaddlePaddle/docs pull request #523
Opened 2019-01-02 07:52 UTC by haowang101779990

1. ParallelExecutor关于 “可用执行场所“ 描述的补充，英文原文为 active places
2. batch_norm is_test 参数和 fuse with relu参数

2019-01-03 02:35 UTC, gongweibao requested changes

2019-01-03 02:35 UTC, gongweibao commented on doc/fluid/api_cn/fluid_cn.rst
> +     1. 如果feed参数为dict类型，那么传入 ``ParallelExecutor`` 的数据量 *必须* 大于可用的执行场所数目（即CPU或GPU的卡数）。否则，C++端将会抛出异常。应额外注意核对数据集的最后一个batch是否比可用执行场所数目（即CPU或GPU的卡数）大。
CPU核数或GPU卡数

2019-01-08 02:56 UTC, gongweibao approved these changes
LGTM

2019-01-09 05:47 UTC, shanyi15 approved these changes
LGTM

2019-01-09 05:48 UTC, merged