add frexp
PaddlePaddle/docs pull request #5276
Opened 2022-09-14 11:30 UTC by Zheng-Bicheng

新增frexp api

2022-09-16 04:16 UTC, Ligoml commented on docs/api/paddle/frexp_cn.rst
> +COPY-FROM: paddle.frexp
<img width="283" alt="image" src="https://user-images.githubusercontent.com/39876205/190555455-1c675045-695f-4899-8926-d0a5bb666937.png">

没有生效，检查一下格式

2022-09-16 04:16 UTC, Ligoml commented on docs/api/paddle/frexp_cn.rst
> +::::::::::
和英文文档保持同步吧

2022-09-16 11:40 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +COPY-FROM: paddle.frexp
不好意思，没有写过这种格式的文档，修改了一下，您再看看现在有没有生效了

2022-09-16 11:45 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +::::::::::
已经保持同步了，您再看一下

2022-09-22 14:59 UTC, SigureMo requested changes
少一些文件的修改，可参考 #5213

2022-09-22 14:59 UTC, SigureMo commented on docs/api/paddle/frexp_cn.rst
> +.. _cn_api_paddle_tensor_math_frexp:
同英文，暴露的是 `paddle.frexp` 的话这里最好改一下

2022-09-22 16:09 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +.. _cn_api_paddle_tensor_math_frexp:
已经修改

2022-09-23 06:05 UTC, Ligoml commented on docs/api/paddle/frexp_cn.rst
> +::::::::::
![image](https://user-images.githubusercontent.com/39876205/191900653-896d67d4-48f6-4c1f-8c91-5bd97a58876a.png)

折行显示需要空一行

2022-09-23 06:06 UTC, Ligoml commented on docs/api/paddle/frexp_cn.rst
> +.. py:function:: paddle.frexp(x)
加一下name的介绍吧

2022-09-23 06:13 UTC, SigureMo commented
> 少一些文件的修改，可参考 #5213

这个还没有改，需要添加到 docs/api/api_label 和 docs/api/paddle/Overview_cn.rst

2022-09-23 06:14 UTC, SigureMo commented on docs/api/paddle/frexp_cn.rst
> +COPY-FROM: paddle.tensor.math.frexp
这里也改成 paddle.frexp

2022-09-23 14:58 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +::::::::::
已经解决

2022-09-23 14:58 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +.. py:function:: paddle.frexp(x)
已经添加

2022-09-23 15:05 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +COPY-FROM: paddle.tensor.math.frexp
已经添加

2022-09-23 15:05 UTC, Zheng-Bicheng commented on docs/api/paddle/frexp_cn.rst
> +COPY-FROM: paddle.tensor.math.frexp
> > 少一些文件的修改，可参考 #5213
> 
> 这个还没有改，需要添加到 docs/api/api_label 和 docs/api/paddle/Overview_cn.rst

修改了

2022-09-26 07:01 UTC, Ligoml approved these changes
LGTM for docs

2022-09-26 07:35 UTC, SigureMo approved these changes
LGTM~~eow~~ for docs ~~~

2022-09-29 07:19 UTC, merged