fix some cn docs (fix some expression in introduction parts)
PaddlePaddle/docs pull request #5285
Opened 2022-09-17 17:10 UTC by Liyulingyue

1. 修复语言表达
2. 修复字体没有加粗的问题

2022-09-17 18:25 UTC, SigureMo commented
- 「呀，是新的 PR！」
- <img width="197" alt="image" src="https://user-images.githubusercontent.com/38436475/190871342-4d84ca18-e070-458c-80bf-5d6b23df4a8a.png">
- 「没看见没看见」

2022-09-17 18:26 UTC, SigureMo requested changes

2022-09-17 18:26 UTC, SigureMo commented on docs/api/paddle/abs_cn.rst
> +    - **x** (Tensor) 输入的 Tensor，数据类型为：float32、float64。
还给改错了 [doge]，中间的 `-` 咋没了

2022-09-17 22:31 UTC, Liyulingyue commented on docs/api/paddle/abs_cn.rst
> +    - **x** (Tensor) 输入的 Tensor，数据类型为：float32、float64。
改完了改完了/doge

2022-09-18 17:11 UTC, SigureMo commented
- <img width="324" alt="image" src="https://user-images.githubusercontent.com/38436475/190919707-c0c40d95-c17d-4485-abc7-186d1eb4d240.png">
- <img width="180" alt="image" src="https://user-images.githubusercontent.com/38436475/190919719-2de3dd4c-8093-4b5a-a38b-0eb7b34499fb.png">
- [DOGEEEEEEEEEE]
<!-- -\s{1,3}([\w_]+)\s{0,3}[(（]([\w\d_\[\]\.]+(\|[\w\d_\[\]\.]+)*([，,]\s{0,3}(可选|optional))?)[)）]\s{0,3}[-–:：]\s{0,3}([^\n]+) -->

2022-09-18 17:25 UTC, SigureMo approved these changes
LGT喵喵喵

2022-09-21 12:27 UTC, Ligoml approved these changes
good job！LGTM

2022-09-22 02:59 UTC, merged