Create [Tutorials-4] —3D image classification from CT scans.ipynb
PaddlePaddle/docs pull request #5384
Opened 2022-10-28 08:20 UTC by WangXi2016

2022-10-28 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/docs?pullRequest=5384) it.</sub>

2022-11-22 07:35 UTC, shiyutang requested changes
1. 存在重复import的random、os、zipfle等，最好import的内容都在一个block中实现，其他位置不出现。
2. 完整数据集链接实际是论文链接，不是数据集链接，需修改。
3. 第四部分下的block L37-L42 存在代码冗余，建议全部去除，直接当成参数传入。
4. dataset类的空格太多，建议报错方法间一行代码。其他部分的空格也需要注意删减。
5. 存在由于使用面向过程思想，代致的代码逻辑结构不明晰，建议训练和predict部分均修改为trainer 和 predictor，使用面向对象的编程方式优化代码。
6. 代码运行完成，无报错，能得到预期效果。

2022-12-07 03:02 UTC, momozi1996 commented
@WangXi2016  hello~~ ~请按照RD的意见好好修改哈～～

2022-12-23 12:39 UTC, WangXi2016 commented
@shiyutang 已经按照要求修改，第二条的完整数据集链接，参考的原文档就是的这个链接。

2023-01-12 02:58 UTC, shiyutang commented
建议二维CNN | Conv2D的图片可以适当缩小；三维CNN | Conv3D的图片可以适当缩小。其他无明显问题。

2023-01-14 08:01 UTC, WangXi2016 commented
> 
已缩小图片 @shiyutang

2023-01-17 08:50 UTC, shiyutang approved these changes
LGTM

2023-01-31 06:07 UTC, sunzhongkai588 commented
不是特别熟悉3D方面的数据，有些问题可能是我理解有问题，辛苦简短回答一下～
1. “3D深度” 是什么意思？
![image](https://user-images.githubusercontent.com/70642955/215659024-4517c7b8-d89c-495a-a051-e0cfa54f7063.png)
2. “体积“可以旋转嘛？用词是否准确
![image](https://user-images.githubusercontent.com/70642955/215659374-6df2224a-d3ef-4170-8afd-42286f8c6334.png)
3. “变异性”是？如果是专有名词，可以在后面加括号和英文
![image](https://user-images.githubusercontent.com/70642955/215679816-d69e2895-514d-4d17-b078-2a25548c0370.png)

2023-02-02 06:17 UTC, WangXi2016 commented
我修改了一下，看看会不会更好理解一些 sunzhongkai588

2023-02-02 07:56 UTC, sunzhongkai588 approved these changes
LGTM

2023-02-03 03:58 UTC, jzhang533 reviewed
```
2、导入相关库
```
这个小节里的代码实现里，假定了用户要在AIStudio上运行这个教程。实际上，不应该有这样的假定。

```
当我们说卷积神经网络（CNN）时，通常是指用于图像分类的二维CNN。但是，现实世界中还使用了其他两种类型的卷积神经网络，即1维CNN和3维CNN。在本指南中，我们将介绍1D和3D CNN及其在现实世界中的应用。我假设您已经大体上熟悉卷积网络的概念。 初学者可能会理解为1维CNN处理一维的数据，2维CNN处理二维的数据，这是错误的！！！

在卷积神经网络（CNN）中，一维和二维滤波器并不是真正的一维和二维。这是只是描述的惯例。
```
- 这个段落，没有讲清楚1D、2D、3D卷积的含义。虽然加感叹号说那么理解不对，但也没说正确的理解是什么。建议进一步查阅资料，重新组织这个段落的语言。
- 出现了两种术语：1维CNN 和 1D CNN，建议统一。

2023-02-04 07:18 UTC, WangXi2016 commented
@jzhang533 貌似不大好描述我直接删掉了，该段落下面就是各种维度的卷积的描述，名词已经统一

2023-02-06 06:29 UTC, jzhang533 approved these changes
LGTM

2023-02-06 06:29 UTC, merged