[Tutorials_2]__Crowd_Instance_level_Human_Parsing_Dataset_数据集上使用DeepLabV3+实现多分类语义分割 test=document_fix
PaddlePaddle/docs pull request #5419
Opened 2022-11-17 03:44 UTC by WangXi2016

[Tutorials_2]__Crowd_Instance_level_Human_Parsing_Dataset_数据集上使用DeepLabV3+实现多分类语义分割.ipynb

2022-11-17 03:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/docs?pullRequest=5419) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/docs?pullRequest=5419) it.</sub>

2022-11-21 12:38 UTC, Bobholamovic requested changes
Review意见如下：
1. 请签署CLA协议。
2. 请为ipynb文件更换名称，建议使用尽可能简单、清晰的语言，如一个偏正短语。可参考项目中已有的其它ipynb文件名称：`image_ocr.ipynb`、`image_search.ipynb`、`landmark_detection.ipynb`等。
3. 介绍部分对于语义分割任务的介绍文字过于简短了，建议丰富之，最好能添加一些参考资料的链接供感兴趣的读者阅读。
4. 环境设置部分，导入模块请遵照Python标准库、第三方库、自定义模块的顺序，三者之间用空格分隔，即如下形式：

```python
import os
import io
from glob import glob

import cv2
import numpy as np
import paddle
import paddle.nn as nn
import matplotlib.pyplot as plt
from scipy.io import loadmat
from PIL import Image as PilImage
from paddle.nn import functional as F
```

5. 缺少环境依赖安装部分教程，请补充。
6. 缺少对数据集处理方式的描述。文章表述中应该明确告诉读者，`从xxx下载数据集，并存放到yyy，数据集目录结构为：...`，而不是仅给出链接。
7. 『数据集类定义』一节，`MyDataset`代码展示部分请用backticks包围，否则会被按照markdown语法解析。
8. 文章中`DeepLabv3+`和`DeepLabV3+`名称不统一。
9. 代码部分，类的方法间用一个空行隔开。
10. 部分句子缺少句号。请检查文中的标点符号。
11. `mIOU`的正确写法为`mIoU`。
12. 代码中的注释有时是中文，有时是英文，建议统一。
13. 『六、模型预测』中『训练集展示』和『验证集展示』的名称不妥，看内容应该是『训练集上模型推理结果展示』和『验证集上模型推理结果展示』。此处还有几个问题：1) 为什么要展示训练集上模型推理的结果？2) 标题风格与之前的小节不一致（没有加编号）。3) 缺少对实验结果的分析与讨论。
14. 『热编码』是否指的是『独热编码（one-hot encoding）』？
15. 文中有『Mean Pixel Accuracy(MPA，平均像素精度)：是PA的一种简单提升』的表述，但没有提到过PA的全称和概念。
16. 第六节中此处是否为笔误：
![image](https://user-images.githubusercontent.com/21275753/203056806-1db48a11-810e-4b6e-a39e-f5fd996326ed.png)
17. 缺少总结部分。

2022-12-07 03:03 UTC, momozi1996 commented
@WangXi2016  hello~ 请按照RD的意见好好修改一下～

2023-03-08 05:56 UTC, sunzhongkai588 commented
@WangXi2016  remind~ 请按照意见好好修改一下

2023-03-08 05:56 UTC, momozi1996 commented
您的邮件我已经收到，我会尽快给您回复，多谢您！

2024-12-03 03:58 UTC, closed without merging

2024-12-03 03:59 UTC, momozi1996 commented
您的邮件我已经收到，我会尽快给您回复，多谢您！