Update LSTM examples
PaddlePaddle/docs pull request #5493
Opened 2022-12-07 18:03 UTC by edencfc

Update LSTM forecast examples

2022-12-14 01:35 UTC, wj-Mcat requested changes
你的案例非常好，不过我这边针对于 auto-encoder有几点建议：
1.  添加 requirements.txt文件，从而提供你这个案例中所需要的所有依赖包。
2. 移除 temp_forecast.ipynb 文件
3.  !wget -O NAB.zip https://bj.bcebos.com/* 这个链接无法下载对应的文件，请确保无误之后再次上传。
4.   参数命名上面的小建议：data_reader -> data_loader, 模型权重保存是：’model’ -> “best_model.pdparams”
5. 第六小节中，可以使用 subfig 将图弄到一起，避免 notebook 的篇幅过长。

2022-12-14 01:52 UTC, wj-Mcat commented
你的案例非常好，不过我这边针对stock_forecast有几点建议：
1.  添加 requirements.txt文件，从而提供你这个案例中所需要的所有依赖包。
2. 你的示例如果只能够运行在 2.4.* 上面，我建议你在 notebook 当中用 assert写上一个版本判断逻辑，这样可强制开发者升级版本。
3. 我本地运行import dnutils的代码报错：

```shell
File ~/miniconda3/envs/paddlenlp/lib/python3.8/site-packages/dnutils/__init__.py:8, in <module>
      3 from .debug import (out, stop, trace, stoptrace, err, warn, ok)
      5 from .tools import (ifnone, ifnot, allnone, allin, allequal, allnot, edict, idxif, first, fst, last, LinearScale,
      6                     mapstr, chunks, pairwise, project, isnone, is_not_none, where, where_not, str2bool)
----> 8 from .signals import add_handler, rm_handler, enable_ctrlc
     10 from .threads import Lock, RLock, Condition, Event, Semaphore, BoundedSemaphore, Barrier, Relay, Thread, \
     11     SuspendableThread, sleep, waitabout, Timer
     13 from .logs import (loggers, newlogger, getlogger, DEBUG, INFO, WARNING, ERROR, CRITICAL, expose, inspect,
     14                    active_exposures, exposure, set_exposure_dir)

File ~/miniconda3/envs/paddlenlp/lib/python3.8/site-packages/dnutils/signals.py:25, in <module>
     23 SIGBUS = signal_.SIGBUS
     24 SIGCHLD = signal_.SIGCHLD
---> 25 SIGCLD = signal_.SIGCLD
     26 SIGCONT = signal_.SIGCONT
     27 SIGFPE = signal_.SIGFPE

AttributeError: module 'signal' has no attribute 'SIGCLD'
```
其版本也是最新的：dnutils==0.3.12

我建议去掉dnutils的依赖，这个包star 为0，不推荐使用。如果想要使用，请多环境下测试，确保程序能够正常运行。

2022-12-16 01:58 UTC, wj-Mcat commented
请在这个 pr 上面更新，你本地push 的时候记得要push origin lstm-01 branch。

我看你已经发了好几个 pr，后续我将把其他的几个 pr 都关掉，所有的commit 将会集中在这个 pr 中来。

2022-12-16 05:39 UTC, edencfc commented
auto-encoder是文档已有的示例，我提交的是气温趋势预测和股票趋势预测两个示例，也就是temp_forecast.ipynb 和 stock_forecast.ipynb

2022-12-16 06:47 UTC, edencfc commented
三个示例不是一起的，不建议文档添加requirements.txt文件，看了下其它方向的示例，也没有都没有加requirements.txt文件

2022-12-16 15:54 UTC, wj-Mcat commented
> 三个示例不是一起的，不建议文档添加requirements.txt文件，看了下其它方向的示例，也没有都没有加requirements.txt文件

我看你的依赖是有点多，所以用 requirements.txt 是更规范一点，如果你觉得麻烦，就需要在notebook当中都写上。

2022-12-16 15:55 UTC, wj-Mcat commented
不好意思我把你其他两个pr 给关掉了，如果内容不是重复的话，你可以 reopen。

2022-12-17 00:12 UTC, edencfc commented
> > 三个示例不是一起的，不建议文档添加requirements.txt文件，看了下其它方向的示例，也没有都没有加requirements.txt文件
> 
> 我看你的依赖是有点多，所以用 requirements.txt 是更规范一点，如果你觉得麻烦，就需要在notebook当中都写上。

现在每个notebook的依赖最多2个，都写上了（常用的numpy、pandas、matplotlib、sklearn不用写吧？）

2022-12-17 00:14 UTC, edencfc commented
> 不好意思我把你其他两个pr 给关掉了，如果内容不是重复的话，你可以 reopen。
> 
> 等你调整完了，你可以艾特我来继续 review 。

已经在这个pr里更新了，可以看到么？

2022-12-20 06:09 UTC, momozi1996 commented
> > 不好意思我把你其他两个pr 给关掉了，如果内容不是重复的话，你可以 reopen。
> > 等你调整完了，你可以艾特我来继续 review 。
> 
> 已经在这个pr里更新了，可以看到么？

@wj-Mcat  hi～ @edencfc  大家对齐一下更改的状态？

2022-12-20 06:20 UTC, wj-Mcat approved these changes
LGTM

2022-12-30 03:22 UTC, merged