update_install_doc
PaddlePaddle/docs pull request #643
Opened 2019-02-21 08:56 UTC by shanyi15

2019-02-21 09:08 UTC, wopeizl approved these changes

2019-02-21 09:08 UTC, wopeizl approved these changes

2019-02-22 07:23 UTC, JiabinYang requested changes

2019-02-22 07:23 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/compile/compile_CentOS.md
> +3. 创建并进入满足编译环境的Docker容器：
创建并进入我们为您准备的配置好编译环境的Docker容器

2019-02-22 07:23 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/Tables.md
> -</p>
这里为什么删除了

2019-02-22 07:23 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/compile/compile_MacOS.md
> -请使用以下命令卸载PaddlePaddle（使用docker安装PaddlePaddle的用户请进入包含PaddlePaddle的容器中使用以下命令，请使用相应版本的pip）：
这个部分为啥要删掉

2019-02-22 07:23 UTC, JiabinYang commented on doc/fluid/beginners_guide/install/index_cn.rst
>  - 如果您希望使用 `pip <https://pypi.org/pypi/>`_ 进行安装PaddlePaddle可以直接使用以下命令:
这里最好加上：我们默认提供的安装包是支持AVX，MKL的安装包如果有其他的需求请参阅附录安装包表

2019-02-22 07:27 UTC, shanyi15 commented on doc/fluid/beginners_guide/install/Tables.md
> -</p>
这个表格我挪到Docker安装那篇独立的文档里了

2019-02-22 08:18 UTC, shanyi15 commented
Done @JiabinYang

2019-02-22 11:24 UTC, JiabinYang approved these changes

2019-02-22 11:33 UTC, merged