[Docathon][Add CN Doc No.35-37]
PaddlePaddle/docs pull request #6442
Opened 2024-01-03 12:05 UTC by Kaedeharai

### PR types

Others

### PR changes

Docs

### Description

补充缺失的中文api文档 ：
#6193 

 **[No37] paddle.incubate.distributed.utils.io.save_for_auto.save_for_auto_inference
这个连英文文档都没有**

添加中文文档：
paddle.incubate.distributed.utils.io.dist_save.save
paddle.incubate.distributed.utils.io.dist_save.save_for_auto_inference

英文文档链接：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_en.html
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_en.html

@sunzhongkai588 @SylarTiaNII

2024-01-15 07:51 UTC, SylarTiaNII requested changes
提了一些修改意见

2024-01-15 07:51 UTC, SylarTiaNII commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_cn.rst
> +    保存模型参数以进行自动并行推理。支持 dp + mp + pp + shardin(stage1)、dp + sharding stage2-3。
shardin -> sharding

2024-01-15 07:51 UTC, SylarTiaNII commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_cn.rst
> +    - **cvt2cpu**: 在使用分片阶段 3 时将参数移动到 CPU。如果不使用分片阶段 3, 则 var 无效。
分片阶段3 -> sharding stage 3
与前文描述保持一致。

2024-01-25 05:29 UTC, SylarTiaNII approved these changes
LGTM

2024-02-20 09:08 UTC, sunzhongkai588 commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_cn.rst
> +                如果是字符串, 格式必须为 num+'G/M/K'，例如 3G、2K、10M 等。默认值为 3G。
```suggestion
    - **obj** (Object) : 要保存的对象。
    - **path** (str|BytesIO) : 保存的对象的路径/缓冲区。如果保存在当前目录中，则输入路径字符串将用作文件名。
    - **protocol** (int, 可选): pickle 模块的协议版本必须大于 1 且小于 5。默认值为 4。
    - ****configs** (dict, 可选): 可选的关键字参数。目前支持以下选项：
            
            1. use_binary_format(bool):
               在 paddle.save 中使用。当保存的对象是静态图形变量时, 可以指定 ``use_binary_for_var``。
               如果为 True , 则在保存单个静态图变量时, 以 c++ 二进制格式保存文件;否则, 请将其保存为 pickle 格式。
               默认值为 False.

            2. gather_to(int|list|tuple|None):
               指定要保存的全局进程。默认值为 None.
               None 表示分布式保存不收集到单个卡上。
            
            3. state_type(str):
               值可以是 'params' 或 'opt'，指定保存参数或优化器状态。
            
            4. max_grouped_size(str|int):
               限制对象组在一段时间内传输的最大大小（位数）。
               如果是字符串, 格式必须为 num+'G/M/K'，例如 3G、2K、10M 等。默认值为 3G。
```

2024-02-20 09:08 UTC, sunzhongkai588 commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_cn.rst
> +.. _cn_api_paddle_incubate_distributed_utils_io_idst_save_save:
```suggestion
.. _cn_api_paddle_incubate_distributed_utils_io_dist_save_save:
```

2024-02-20 09:08 UTC, sunzhongkai588 commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_cn.rst
> +.. _cn_api_paddle_incubate_distributed_utils_io_idst_save_save_for_auto_inference:
```suggestion
.. _cn_api_paddle_incubate_distributed_utils_io_dist_save_save_for_auto_inference:
```

2024-02-20 09:08 UTC, sunzhongkai588 commented on docs/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_cn.rst
> +            其他，参数将保存为名称 path_preifx_dist{global_rank}.pdparams 和 path_preifx_dist{global_rank}.pdattrs。
```suggestion
    - **path_prefix**:  要保存的路径前缀。如果 `path_preifx` 以路径分隔符结尾, 则路径将作为目录进行处理，参数将保存在其中，并自动命名为 saved_parameters。除此之外，参数将保存为名称 path_preifx_dist{global_rank}.pdparams 和 path_preifx_dist{global_rank}.pdattrs。
```

2024-04-09 04:06 UTC, closed without merging