add doc
PaddlePaddle/docs pull request #83
Opened 2018-09-21 10:10 UTC by chenjiaoAngel

2018-09-21 10:16 UTC, shanyi15 commented
您好，目前看还是有dockerfile

2018-09-25 02:33 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/index_anakin_ch.rst
> +
这里的写法是否能在预览工具上试一下呢？效果是？

2018-09-25 02:41 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/index_anakin_ch.rst
> +   Anakin的安装指南 [`install_anakin ->`](./install_anakin.md)
如果需要改toctree的话，请在https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/advanced_usage/deploy/index_anakin.rst 这个文件的基础上改动，而不是新建

2018-09-25 02:41 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +下文称Anakin为AK，运算操作为OP,本文参考Tensorflow的Parser编写,参考代码目录为tools/external_converter_v2/parser/tensorflow
为了方便用户理解本文的功能，请在开头交代背景、目的等信息。

2018-09-25 02:41 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
Parser的功能是.....

2018-09-25 02:41 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
全文的句号请使用中文句号

2018-09-25 02:41 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
这些框架的名字其实不是全大写的，请核对～

2018-09-25 02:46 UTC, Superjomn requested changes

2018-09-25 02:46 UTC, Superjomn commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
FLUID -> Paddle， FLUID不是一个框架，只是 Paddle 的一个版本。

2018-09-25 02:46 UTC, Superjomn commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> ++ 最大的不同是与FLUID或TENSORFLOW这种OP粒度很细的框架，AK的模型中OP的粒度很粗，这是为了节省访存开销.这会导致解析这些框架的模型时存在大量的合并操作.
FLUID -> Paddle

2018-09-25 03:26 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/index_anakin_ch.rst
> +
好的

2018-09-25 03:26 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/index_anakin_ch.rst
> +   Anakin的安装指南 [`install_anakin ->`](./install_anakin.md)
嗯，已经在这个上面添加了。另一个index_anakin_ch.rst已经被删除了

2018-09-25 03:27 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +下文称Anakin为AK，运算操作为OP,本文参考Tensorflow的Parser编写,参考代码目录为tools/external_converter_v2/parser/tensorflow
好的，已经修改，请查阅

2018-09-25 03:27 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
好的，已经修改，请查阅

2018-09-25 03:27 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
好的，已经修改，请查阅

2018-09-25 03:27 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +功能是将其他深度学习框架(如CAFFE，FLUID，TENSORFLOW，ONNEX)的模型转换为AK的模型.对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
好的，已经修改，请查阅

2018-09-25 03:27 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> ++ 最大的不同是与FLUID或TENSORFLOW这种OP粒度很细的框架，AK的模型中OP的粒度很粗，这是为了节省访存开销.这会导致解析这些框架的模型时存在大量的合并操作.
好的，已经修改，请查阅

2018-09-25 03:54 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/index_anakin_ch.rst
> +
看到已经修改了doc/fluid/advanced_usage/deploy/index_anakin.rst，doc/fluid/advanced_usage/deploy/index_anakin_ch.rst整个文件应该可以删掉了

2018-09-25 03:54 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/index_anakin.rst
> +   anakin_parser_design.md
这里需要和文件名对应：anakin_parser_design_ch.md，可以修改文件名，或者修改这里。

2018-09-25 03:56 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design_ch.md
> +Parser功能是将其他深度学习框架(如caffe，tensorflow，onnx)的模型转换为AK的模型。对AK的作用是屏蔽不同框架间的差异，这种差异包括模型存储、OP的定义、图差异
全文中，深度学习框架的写法最好是：Caffe、TensorFlow、ONNX、Paddle、Fluid这样

2018-09-25 06:31 UTC, chenjiaoAngel commented on doc/fluid/advanced_usage/deploy/index_anakin.rst
> +   anakin_parser_design.md
已修改，请查阅

2018-09-25 06:36 UTC, shanyi15 commented on doc/fluid/advanced_usage/deploy/anakin_parser_design.md
> + 1. 在config.yaml中填写你的Parser运行的必要信息，包括ProtoPath和SavePath等.OPTIONS/Framework改为你的Parser的类型，TARGET下填写对应的参数列表
文中句号请统一改为中文句号～

2018-09-25 07:44 UTC, shanyi15 commented
LGTM，请 @Superjomn 再次确认

2018-09-25 08:58 UTC, Superjomn requested changes
还有一处

2018-09-25 08:58 UTC, Superjomn commented on doc/fluid/advanced_usage/deploy/anakin_parser_design.md
> + + 最大的不同是与Fluid或TensorFlow的模型中OP粒度很细，而AK的模型中OP的粒度很粗（目的是为了节省访存开销）。这会导致解析这些框架的模型时存在大量的合并操作
Fluid ?

2018-09-26 06:51 UTC, shanyi15 commented
请 @chenjiaoAngel 用预览工具预览一下文档，谢谢！
参考：https://github.com/PaddlePaddle/FluidDoc#preview-with-ppo

2018-09-28 03:00 UTC, chenjiaoAngel commented
<img width="932" alt="5fd40d9e47d3cf9ed6adf7fbc2c3a80d" src="https://user-images.githubusercontent.com/38650344/46185667-7b92a780-c30d-11e8-9347-0a06f14485d8.png">
<img width="925" alt="606ab73efd659cc2e362aa622679fe83" src="https://user-images.githubusercontent.com/38650344/46185671-81888880-c30d-11e8-86d8-1b04f9233436.png">
<img width="921" alt="0f301fe27eb3206e07c25ac076c7d4cf" src="https://user-images.githubusercontent.com/38650344/46185674-864d3c80-c30d-11e8-9c1d-4b7ccb99af94.png">


<img width="939" alt="0b6cae47a825043bf2043303f3d2e4e9" src="https://user-images.githubusercontent.com/38650344/46185651-7170a900-c30d-11e8-88f4-87309e1692a4.png">

2018-09-28 09:22 UTC, shanyi15 commented
有些地方没写句号，有些地方有多余的空格，还有项目符号没能正确显示。
![image](https://user-images.githubusercontent.com/35982308/46199984-004be880-c343-11e8-8b35-2f910cc7b936.png)

2018-09-28 09:55 UTC, chenjiaoAngel commented
请查看最新的，这个已经修改好。截图那个是昨天的
<img width="800" alt="image" src="https://user-images.githubusercontent.com/38650344/46201752-823e1080-c347-11e8-99f9-75942e52980a.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/38650344/46201772-8bc77880-c347-11e8-8704-89d8ef3e20d6.png">

<img width="907" alt="image" src="https://user-images.githubusercontent.com/38650344/46201784-93871d00-c347-11e8-9ade-557383e0838b.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/38650344/46201791-9c77ee80-c347-11e8-8b59-95780e7ccdce.png">
<img width="915" alt="image" src="https://user-images.githubusercontent.com/38650344/46201802-a3066600-c347-11e8-8e3f-705f1057ab14.png">

2018-09-28 09:56 UTC, shanyi15 commented
请最后贴一个改对的图哈，谢谢！

2018-09-28 09:58 UTC, shanyi15 commented
看到还有其他文档的修改～可否一并确认下效果

2018-10-08 02:50 UTC, shanyi15 commented on doc/fluid/menu.json
> +    "sections": [
这个文件是不是传错了呢

2018-10-08 02:53 UTC, shanyi15 commented
![image](https://user-images.githubusercontent.com/35982308/46590739-3ed26780-cae8-11e8-8205-be07965e2dda.png)
这两个文件是不是传错了呢

2018-10-08 03:26 UTC, shanyi15 commented
LGTM，请 @Superjomn 再看一下

2018-10-08 08:45 UTC, shanyi15 commented
看到文档里面还是有一些地方写成了Fluid（包括之前就已有的文档），请统一检查一下，改成PaddlePaddle，谢谢！

2018-10-08 10:31 UTC, chenjiaoAngel commented
![Uploading image.png…]()
![Uploading image.png…]()

由于Anakin内部model转换代码写的是Fluid到Anakin，如果在convert_paddle_to_anakin.md文中将FLuid改为PaddlePaddle话，可能会造成读者歧义，与代码内容不一样
由于Anakin内部model转换代码写的是Fluid到Anakin，如果在convert_paddle_to_anakin.md文中将FLuid改为PaddlePaddle话，可能会造成读者歧义，与代码内容不一样

2018-10-08 10:46 UTC, chenjiaoAngel commented
<img width="592" alt="image" src="https://user-images.githubusercontent.com/38650344/46604333-7c56e500-cb28-11e8-8175-5db416997cd3.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/38650344/46604356-8973d400-cb28-11e8-8709-6b4149c5ba9c.png">

由于Anakin内部model转换代码写的是Fluid到Anakin，如果在convert_paddle_to_anakin.md文中将FLuid改为PaddlePaddle话，可能会造成读者歧义，与代码内容不一样

2018-10-09 02:59 UTC, shanyi15 approved these changes
LGTM

2018-10-09 03:42 UTC, Superjomn requested changes
麻烦全局把所有的 Fluid 替换成 Paddle，Fluid也不是官方版本名。 谢谢

另外，你们自己repo里面的文档，请把 Fluid 统一为 Paddle，Paddle和Caffe才是一个层次的，不是Fluid。

2018-10-10 02:22 UTC, chenjiaoAngel commented
@Superjomn 已经修改好，请查看

2018-10-10 02:24 UTC, Superjomn approved these changes
LGTM

2018-10-10 02:26 UTC, merged