link default
PaddlePaddle/docs pull request #873
Opened 2019-05-30 05:45 UTC by xsrobin

2019-05-30 06:13 UTC, acosta123 commented on doc/fluid/user_guides/models/index_cn.rst
> +-  `DuReader in PaddlePaddle Fluid <https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/machine_reading_comprehension/README.md>`__
正确链接应为https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/unarchived/machine_reading_comprehension/README.md

2019-05-30 06:16 UTC, acosta123 commented on doc/fluid/user_guides/models/index_cn.rst
> +- `Deep Attention Matching Network <https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/deep_attention_matching_net>`__
正确链接应为
https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/unarchived/deep_attention_matching_net/README.md

2019-05-30 06:25 UTC, acosta123 requested changes
有的链接放错了，建议修改

2019-06-01 09:50 UTC, shanyi15 commented
close via https://github.com/PaddlePaddle/FluidDoc/pull/876

2019-06-01 09:50 UTC, closed without merging